---
result: 
timestamp: '2016-05-25T11:17:08-07:00'
duration: 27.211
triggeredBy: adamleff
url: http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/14/
version: 
git_ref: adamleff/data_collector
git_commit: dce9f5072e96f25c5d987678b89c60c63a96eeb9
failures: {}
stages:
  chef-build:
    result: 
    timestamp: '2016-05-25T11:17:42-07:00'
    duration: 0.0
    url: http://manhattan.ci.chef.co/job/chef-build/23/
    parameters:
      GIT_REF: adamleff/data_collector
      APPEND_TIMESTAMP: true
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef
      GIT_COMMIT: dce9f5072e96f25c5d987678b89c60c63a96eeb9
      PROJECT: chef
      PROMOTE: 'false'
      PIPELINE_TRIGGER_BUILD_NUMBER: '14'
      ADHOC_BUILD: 'true'
      GIT_BRANCH: origin/adamleff/data_collector
      PIPELINE_TRIGGER_JOB_NAME: chef-trigger-ad_hoc
    runs:
      aix-6.1-powerpc:
        result: 
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 0.0
        builtOn: chef-aix-6-powerpc-builder-88f619
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/23/
        omnibusTiming: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 499.991
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 127.7446
          Health check: 18.4631
          chef-complete: 0.0
          clean-static-libs: 0.2592
          openssl-customization: 0.1382
          version-manifest: 0.0848
          shebang-cleanup: 0.0069
          gem-permissions: 1.8041
          chef-remove-docs: 0.0939
          chef-appbundle: 41.0093
          chef: 78.2149
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 375.455
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 67.3126
          Health check: 12.3431
          chef-complete: 0.0
          clean-static-libs: 0.096
          openssl-customization: 0.0958
          version-manifest: 0.0351
          shebang-cleanup: 0.0105
          gem-permissions: 1.3344
          chef-remove-docs: 0.0314
          chef-appbundle: 29.4743
          chef: 55.8764
      el-5:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 529.018
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 159.4705
          Health check: 20.4271
          chef-complete: 0.0
          clean-static-libs: 0.2807
          openssl-customization: 0.1105
          version-manifest: 0.0323
          shebang-cleanup: 0.0151
          gem-permissions: 2.0079
          chef-remove-docs: 0.0519
          chef-appbundle: 39.4146
          chef: 79.0941
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 414.735
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 89.5614
          Health check: 15.4972
          chef-complete: 0.0
          clean-static-libs: 0.1574
          openssl-customization: 0.1101
          version-manifest: 0.0347
          shebang-cleanup: 0.0079
          gem-permissions: 1.1183
          chef-remove-docs: 0.0337
          chef-appbundle: 31.4702
          chef: 63.2037
      el-6:
        result: 
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 0.0
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/23/
        omnibusTiming: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 434.806
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 90.1719
          Health check: 21.0691
          chef-complete: 0.0
          clean-static-libs: 0.1604
          openssl-customization: 0.1385
          version-manifest: 0.0741
          shebang-cleanup: 0.0157
          gem-permissions: 1.7102
          chef-remove-docs: 0.054
          chef-appbundle: 33.9188
          chef: 64.4923
      el-7:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 423.051
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 132.6588
          Health check: 7.6773
          chef-complete: 0.0
          clean-static-libs: 0.1051
          openssl-customization: 0.0716
          version-manifest: 0.0163
          shebang-cleanup: 0.0034
          gem-permissions: 1.2306
          chef-remove-docs: 0.0424
          chef-appbundle: 30.2928
          chef: 54.1949
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 534.948
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 107.1026
          Health check: 0.0567
          chef-complete: 0.0
          clean-static-libs: 0.3402
          openssl-customization: 0.1159
          version-manifest: 0.0344
          shebang-cleanup: 0.006
          gem-permissions: 2.5247
          chef-remove-docs: 0.1337
          chef-appbundle: 46.0351
          chef: 91.4186
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 368.272
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 57.9601
          Health check: 0.0516
          chef-complete: 0.0
          clean-static-libs: 0.1963
          openssl-customization: 0.0852
          version-manifest: 0.0333
          shebang-cleanup: 0.0078
          gem-permissions: 1.4256
          chef-remove-docs: 0.0498
          chef-appbundle: 29.2894
          chef: 57.2598
      freebsd-9:
        result: 
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 0.0
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/23/
        omnibusTiming: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 410.943
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 75.5326
          Health check: 0.0518
          chef-complete: 0.0
          clean-static-libs: 0.2034
          openssl-customization: 0.093
          version-manifest: 0.073
          shebang-cleanup: 0.0077
          gem-permissions: 1.5341
          chef-remove-docs: 0.0687
          chef-appbundle: 30.22
          chef: 61.1999
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 315.832
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 73.5927
          Health check: 5.1751
          chef-complete: 0.0
          clean-static-libs: 0.0474
          openssl-customization: 0.0478
          version-manifest: 0.0277
          shebang-cleanup: 0.0041
          gem-permissions: 0.6446
          chef-remove-docs: 0.0227
          chef-appbundle: 40.1429
          chef: 48.3736
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 292.935
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 15.5496
          Health check: 0.3197
          chef-complete: 0.0
          clean-static-libs: 0.0688
          openssl-customization: 0.0484
          version-manifest: 0.0154
          shebang-cleanup: 0.0114
          gem-permissions: 0.8766
          chef-remove-docs: 0.041
          chef-appbundle: 19.6526
          chef: 53.3512
      nexus-7:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 350.151
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 90.6574
          Health check: 5.6242
          chef-complete: 0.0
          clean-static-libs: 0.0486
          openssl-customization: 0.0499
          version-manifest: 0.0315
          shebang-cleanup: 0.0058
          gem-permissions: 0.7049
          chef-remove-docs: 0.0236
          chef-appbundle: 23.586
          chef: 91.5244
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 486.832
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 13.113
          Health check: 0.0462
          chef-complete: 0.0
          clean-static-libs: 0.0918
          openssl-customization: 0.0688
          version-manifest: 0.0398
          shebang-cleanup: 0.0067
          gem-permissions: 1.009
          chef-remove-docs: 0.0321
          chef-appbundle: 25.9685
          chef: 49.0952
      solaris-10-sun4v:
        result: 
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 0.0
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/23/
        omnibusTiming: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 483.323
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 129.2285
          Health check: 15.2595
          chef-complete: 0.0
          clean-static-libs: 0.1951
          openssl-customization: 0.1336
          version-manifest: 0.0849
          shebang-cleanup: 0.0054
          gem-permissions: 1.7638
          chef-remove-docs: 0.047
          chef-appbundle: 43.3485
          chef: 74.4591
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 381.449
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/23/
        omnibusTiming:
          Packaging: 70.8468
          Health check: 9.9763
          chef-complete: 0.0
          clean-static-libs: 0.1162
          openssl-customization: 0.0827
          version-manifest: 0.0148
          shebang-cleanup: 0.0067
          gem-permissions: 1.2262
          chef-remove-docs: 0.0326
          chef-appbundle: 30.5511
          chef: 55.4836
      windows-2008r2:
        result: 
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 0.0
        builtOn: chef-windows-2008r2-builder-db26a1
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/23/
        omnibusTiming: {}
      windows-2008r2-i386:
        result: 
        timestamp: '2016-05-25T11:17:42-07:00'
        duration: 0.0
        builtOn: chef-windows-2008r2-i386-builder-de9752
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/23/
        omnibusTiming: {}
  chef-trigger-ad_hoc:
    result: SUCCESS
    timestamp: '2016-05-25T11:17:08-07:00'
    duration: 27.211
    url: http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/14/
    causes:
    - shortDescription: Started by user Adam Leff
      userId: adamleff
      userName: Adam Leff
    parameters:
      GIT_REF: adamleff/data_collector
      EXPIRE_CACHE: false
    runs: {}
