---
result: 
timestamp: '2016-05-24T12:37:42-07:00'
duration: 25.579
triggeredBy: adamleff
url: http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/13/
version: 
git_ref: adamleff/data_collector
git_commit: e36916fb35c0d314237dd81574f4ac5ff18592cb
failures: {}
stages:
  chef-build:
    result: 
    timestamp: '2016-05-24T12:38:16-07:00'
    duration: 0.0
    url: http://manhattan.ci.chef.co/job/chef-build/22/
    parameters:
      GIT_REF: adamleff/data_collector
      APPEND_TIMESTAMP: true
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef
      GIT_COMMIT: e36916fb35c0d314237dd81574f4ac5ff18592cb
      PROJECT: chef
      PROMOTE: 'false'
      PIPELINE_TRIGGER_BUILD_NUMBER: '13'
      ADHOC_BUILD: 'true'
      GIT_BRANCH: origin/adamleff/data_collector
      PIPELINE_TRIGGER_JOB_NAME: chef-trigger-ad_hoc
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 1051.548
        builtOn: chef-aix-6-powerpc-builder-88f619
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 380.3803
          Health check: 0.9987
          chef-complete: 0.0
          clean-static-libs: 0.0
          openssl-customization: 0.1928
          version-manifest: 0.0689
          shebang-cleanup: 0.0085
          gem-permissions: 1.8652
          chef-remove-docs: 0.0635
          chef-appbundle: 55.3949
          chef: 79.4607
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 493.997
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 127.2463
          Health check: 18.1538
          chef-complete: 0.0
          clean-static-libs: 0.1969
          openssl-customization: 0.1571
          version-manifest: 0.0892
          shebang-cleanup: 0.0075
          gem-permissions: 1.7286
          chef-remove-docs: 0.0487
          chef-appbundle: 42.3739
          chef: 75.3286
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 377.731
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 66.8311
          Health check: 12.9292
          chef-complete: 0.0
          clean-static-libs: 0.1022
          openssl-customization: 0.0963
          version-manifest: 0.0356
          shebang-cleanup: 0.0099
          gem-permissions: 1.3301
          chef-remove-docs: 0.0317
          chef-appbundle: 31.3092
          chef: 57.3169
      el-5:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 535.622
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 160.5683
          Health check: 20.8791
          chef-complete: 0.0
          clean-static-libs: 0.2664
          openssl-customization: 0.1266
          version-manifest: 0.0318
          shebang-cleanup: 0.0064
          gem-permissions: 2.1195
          chef-remove-docs: 0.0664
          chef-appbundle: 39.0894
          chef: 77.7093
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 402.293
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 100.0936
          Health check: 15.4599
          chef-complete: 0.0
          clean-static-libs: 0.1216
          openssl-customization: 0.1069
          version-manifest: 0.0743
          shebang-cleanup: 0.0098
          gem-permissions: 1.2653
          chef-remove-docs: 0.0578
          chef-appbundle: 30.5741
          chef: 59.872
      el-6:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 586.687
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 158.9181
          Health check: 22.404
          chef-complete: 0.0
          clean-static-libs: 0.2775
          openssl-customization: 0.2549
          version-manifest: 0.1357
          shebang-cleanup: 0.0446
          gem-permissions: 2.2032
          chef-remove-docs: 0.0822
          chef-appbundle: 47.5342
          chef: 89.0468
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 442.071
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 90.1909
          Health check: 20.855
          chef-complete: 0.0
          clean-static-libs: 0.1781
          openssl-customization: 0.1357
          version-manifest: 0.0656
          shebang-cleanup: 0.3253
          gem-permissions: 1.4753
          chef-remove-docs: 0.067
          chef-appbundle: 34.3275
          chef: 64.3954
      el-7:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 424.445
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 133.2526
          Health check: 7.9918
          chef-complete: 0.0
          clean-static-libs: 0.0905
          openssl-customization: 0.093
          version-manifest: 0.0172
          shebang-cleanup: 0.0038
          gem-permissions: 1.2362
          chef-remove-docs: 0.0378
          chef-appbundle: 30.1305
          chef: 56.1584
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 524.653
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 106.0082
          Health check: 0.0372
          chef-complete: 0.0
          clean-static-libs: 0.3461
          openssl-customization: 0.1116
          version-manifest: 0.0291
          shebang-cleanup: 0.0059
          gem-permissions: 2.4101
          chef-remove-docs: 0.1076
          chef-appbundle: 45.4122
          chef: 92.8433
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 384.783
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 58.3461
          Health check: 0.0766
          chef-complete: 0.0
          clean-static-libs: 0.1838
          openssl-customization: 0.0832
          version-manifest: 0.0375
          shebang-cleanup: 0.0066
          gem-permissions: 1.3944
          chef-remove-docs: 0.051
          chef-appbundle: 30.6643
          chef: 57.9524
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 667.487
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 139.2034
          Health check: 0.0878
          chef-complete: 0.0
          clean-static-libs: 0.3727
          openssl-customization: 0.1424
          version-manifest: 0.0566
          shebang-cleanup: 0.0084
          gem-permissions: 2.7985
          chef-remove-docs: 0.0918
          chef-appbundle: 48.9047
          chef: 105.332
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 408.705
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 74.329
          Health check: 0.0525
          chef-complete: 0.0
          clean-static-libs: 0.2201
          openssl-customization: 0.0848
          version-manifest: 0.0196
          shebang-cleanup: 0.0077
          gem-permissions: 1.533
          chef-remove-docs: 0.0614
          chef-appbundle: 29.1901
          chef: 60.7703
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 278.386
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 73.902
          Health check: 5.2315
          chef-complete: 0.0
          clean-static-libs: 0.0482
          openssl-customization: 0.0484
          version-manifest: 0.0291
          shebang-cleanup: 0.0045
          gem-permissions: 0.7939
          chef-remove-docs: 0.0231
          chef-appbundle: 22.8943
          chef: 47.5532
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 261.813
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 17.7558
          Health check: 0.3884
          chef-complete: 0.0
          clean-static-libs: 0.084
          openssl-customization: 0.0594
          version-manifest: 0.0273
          shebang-cleanup: 0.0229
          gem-permissions: 1.0485
          chef-remove-docs: 0.0468
          chef-appbundle: 24.2039
          chef: 42.5126
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 438.671
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 12.8155
          Health check: 0.0457
          chef-complete: 0.0
          clean-static-libs: 0.0928
          openssl-customization: 0.0686
          version-manifest: 0.0382
          shebang-cleanup: 0.0062
          gem-permissions: 0.9728
          chef-remove-docs: 0.0307
          chef-appbundle: 23.129
          chef: 48.5793
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 1970.38
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 111.9863
          Health check: 0.1662
          chef-complete: 0.0
          clean-static-libs: 0.8095
          openssl-customization: 0.9405
          version-manifest: 0.1634
          shebang-cleanup: 0.0466
          gem-permissions: 10.932
          chef-remove-docs: 0.332
          chef-appbundle: 344.5618
          chef: 471.1262
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 493.089
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 130.8392
          Health check: 14.7422
          chef-complete: 0.0
          clean-static-libs: 0.1927
          openssl-customization: 0.1241
          version-manifest: 0.0724
          shebang-cleanup: 0.0064
          gem-permissions: 1.7913
          chef-remove-docs: 0.0886
          chef-appbundle: 40.4591
          chef: 73.0885
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 368.197
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 68.4503
          Health check: 9.5222
          chef-complete: 0.0
          clean-static-libs: 0.1096
          openssl-customization: 0.0853
          version-manifest: 0.0535
          shebang-cleanup: 0.0076
          gem-permissions: 1.2205
          chef-remove-docs: 0.0346
          chef-appbundle: 31.2888
          chef: 54.7115
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 785.054
        builtOn: chef-windows-2008r2-builder-db26a1
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 172.9535
          Health check: 0.0312
          chef-complete: 0.0
          clean-static-libs: 0.156
          ruby-windows-devkit-bash: 0.0624
          ruby-windows-devkit: 10.842
          openssl-customization: 0.1872
          version-manifest: 0.0624
          shebang-cleanup: 1.4976
          gem-permissions: 0.0
          chef-remove-docs: 0.2964
          chef-appbundle: 42.0264
          chef: 130.3692
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-24T12:38:16-07:00'
        duration: 666.333
        builtOn: chef-windows-2008r2-i386-builder-de9752
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/22/
        omnibusTiming:
          Packaging: 110.1342
          Health check: 0.0156
          chef-complete: 0.0
          clean-static-libs: 0.1404
          ruby-windows-devkit-bash: 0.0624
          ruby-windows-devkit: 6.6143
          openssl-customization: 0.2028
          version-manifest: 0.0624
          shebang-cleanup: 1.5288
          gem-permissions: 0.0
          chef-remove-docs: 0.4056
          chef-appbundle: 46.3023
          chef: 137.0474
  chef-trigger-ad_hoc:
    result: SUCCESS
    timestamp: '2016-05-24T12:37:42-07:00'
    duration: 25.579
    url: http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/13/
    causes:
    - shortDescription: Started by user Adam Leff
      userId: adamleff
      userName: Adam Leff
    parameters:
      GIT_REF: adamleff/data_collector
      EXPIRE_CACHE: false
    runs: {}
