---
result: FAILURE
timestamp: '2016-03-23T14:19:20-07:00'
duration: 13621.162
version: 
git_commit: 8642eec99e35eed229f5c666021d3532284ebbb3
stages:
  chefdk-build:
    result: FAILURE
    failures:
      network reset rubygems.org: debian,el,ubuntu
      'omnibus Software: knife-spork': windows
    timestamp: '2016-03-23T14:19:30-07:00'
    duration: 13617.653
    url: http://manhattan.ci.chef.co/job/chefdk-build/126/
    parameters:
      GIT_REF: v0.12.3
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 8642eec99e35eed229f5c666021d3532284ebbb3
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '12'
      GIT_BRANCH: v0.12.3
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
    runs:
      debian-6:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 94.253
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/126/
        failureCause:
          cause: network reset
          detailedCause: network reset rubygems.org
          jenkinsBuildStep: Invoke XShell command
          suspiciousBlocks:
            194: |
              Installing aws-sdk-core 2.2.29
              Installing aws-sdk-resources 2.2.29

              Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/aws-sdk-2.2.29.gem)
              An error occurred while installing aws-sdk (2.2.29), and Bundler cannot
              continue.
              Make sure that `gem install aws-sdk -v '2.2.29'` succeeds before bundling.
        omnibusTiming: {}
      el-6:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 97.608
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/126/
        failureCause:
          cause: network reset
          detailedCause: network reset rubygems.org
          jenkinsBuildStep: Invoke XShell command
          suspiciousBlocks:
            195: |
              Installing aws-sdk-resources 2.2.29
              Installing aws-sdk 2.2.29

              Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/mixlib-config-2.2.1.gem)
              An error occurred while installing mixlib-config (2.2.1), and Bundler cannot
              continue.
              Make sure that `gem install mixlib-config -v '2.2.1'` succeeds before bundling.
        omnibusTiming: {}
      el-7:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 104.233
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/126/
        failureCause:
          cause: network reset
          detailedCause: network reset rubygems.org
          jenkinsBuildStep: Invoke XShell command
          suspiciousBlocks:
            199: |
              Installing mixlib-config 2.2.1
              Installing mixlib-shellout 2.2.6

              Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/chef-config-12.8.1.gem)
              An error occurred while installing chef-config (12.8.1), and Bundler cannot
              continue.
              Make sure that `gem install chef-config -v '12.8.1'` succeeds before bundling.
        omnibusTiming: {}
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 46.978
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/126/
        failureCause:
          cause: network reset
          detailedCause: network reset rubygems.org
          jenkinsBuildStep: Invoke XShell command
          suspiciousBlocks:
            189: |
              Fetching dependency metadata from https://rubygems.org/..
              Resolving dependencies........................................................

              Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/awesome_print-1.6.1.gem)
              An error occurred while installing awesome_print (1.6.1), and Bundler cannot
              continue.
              Make sure that `gem install awesome_print -v '1.6.1'` succeeds before bundling.
        omnibusTiming: {}
      windows-2008r2-i386:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 3788.758
        builtOn: chefdk-windows-2008r2-i386-builder-a728bb
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/126/
        failureCause:
          cause: omnibus
          detailedCause: 'omnibus Software: knife-spork'
          shellCommand:
            exitStatus: '128'
            command: git -c core.autocrlf=false fetch https://github.com/opscode/ohai.git
              f8522ea9ca3b1252af6a03a4c58057d320e8343c
            stderr: 'error: no such remote ref f8522ea9ca3b1252af6a03a4c58057d320e8343c'
          jenkinsBuildStep: Invoke XShell command
          lastOmnibusLine: "[Software: knife-spork] I | Resolving manifest entry for
            knife-spork"
          lastOmnibusStep: 'Software: knife-spork'
          stacktraces:
          - - C:/languages/ruby/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-798b2db8e34a/lib/omnibus/util.rb:101:in
              `rescue in shellout!'
            - C:/languages/ruby/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-798b2db8e34a/lib/omnibus/util.rb:97:in
              `shellout!'
            - C:/languages/ruby/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-798b2db8e34a/lib/omnibus/fetchers/git_fetcher.rb:213:in
              `git'
            - C:/languages/ruby/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-798b2db8e34a/lib/omnibus/fetchers/git_fetcher.rb:168:in
              `git_fetch'
            - C:/languages/ruby/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-798b2db8e34a/lib/omnibus/fetchers/git_fetcher.rb:65:in
              `fetch'
            - C:/languages/ruby/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-798b2db8e34a/lib/omnibus/software.rb:798:in
              `fetch'
            - C:/languages/ruby/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-798b2db8e34a/lib/omnibus/project.rb:1060:in
              `block (3 levels) in download'
        omnibusTiming: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 1769.775
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/126/
        omnibusTiming: {}
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-03-23T14:19:20-07:00'
    duration: 3.509
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/12/
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    parameters:
      GIT_REF: v0.12.3
      EXPIRE_CACHE: false
    runs: {}
