---
result: SUCCESS
timestamp: '2016-05-17T08:31:49-07:00'
duration: 4873.879
version: 0.14.27
git_commit: 791122929aa343d7155071ea84811fa0b218e87a
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-17T08:31:49-07:00'
    duration: 2.604
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/69/
    parameters:
      GIT_REF: v0.14.27
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-05-17T08:31:59-07:00'
    duration: 3058.943
    url: http://manhattan.ci.chef.co/job/chefdk-build/422/
    parameters:
      GIT_REF: v0.14.27
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 791122929aa343d7155071ea84811fa0b218e87a
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '69'
      GIT_BRANCH: v0.14.27
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
    runs: {}
  chefdk-test:
    result: SUCCESS
    timestamp: '2016-05-17T09:23:05-07:00'
    duration: 1800.825
    url: http://manhattan.ci.chef.co/job/chefdk-test/181/
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.27
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.27
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 791122929aa343d7155071ea84811fa0b218e87a
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '69'
      GIT_BRANCH: v0.14.27
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '422'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-69/69/2016-05-17_15-31-49
    runs: {}
  chefdk-promote:
    result: SUCCESS
    timestamp: '2016-05-17T09:53:16-07:00'
    duration: 11.507
    url: http://manhattan.ci.chef.co/job/chefdk-promote/77/
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.27
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.27
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 791122929aa343d7155071ea84811fa0b218e87a
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '69'
      GIT_BRANCH: v0.14.27
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '422'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-69/69/2016-05-17_15-31-49
    runs: {}
