---
result: SUCCESS
timestamp: '2016-05-17T08:31:49-07:00'
duration: 4873.879
version: 0.14.27
git_commit: 791122929aa343d7155071ea84811fa0b218e87a
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-17T08:31:49-07:00'
    duration: 2.604
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/69/
    parameters:
      GIT_REF: v0.14.27
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-05-17T08:31:59-07:00'
    duration: 3058.943
    url: http://manhattan.ci.chef.co/job/chefdk-build/422/
    parameters:
      GIT_REF: v0.14.27
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 791122929aa343d7155071ea84811fa0b218e87a
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '69'
      GIT_BRANCH: v0.14.27
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-17T08:31:59-07:00'
        duration: 1473.211
        builtOn: chefdk-windows-2008r2-i386-builder-53e13c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/422/
        omnibusTiming:
          chef-dk: 269.7559
          chef-dk-appbundle: 220.0072
          gem-permissions: 0.0
          chef-dk-env-customization: 0.1092
          chef-dk-powershell-scripts: 0.8112
          ruby-windows-devkit: 9.6097
          chef-dk-remove-docs: 0.3744
          rubygems-customization: 0.0936
          shebang-cleanup: 3.2916
          version-manifest: 0.0936
          openssl-customization: 0.2184
          clean-static-libs: 0.4524
          chef-dk-complete: 0.0
          Health check: 0.0312
          Packaging: 293.8264
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-17T08:31:59-07:00'
        duration: 1304.647
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/422/
        omnibusTiming:
          chef-dk: 204.629
          chef-dk-appbundle: 460.7814
          gem-permissions: 7.1569
          chef-dk-remove-docs: 0.1621
          rubygems-customization: 0.1476
          shebang-cleanup: 0.0229
          version-manifest: 0.1475
          openssl-customization: 0.1903
          clean-static-libs: 0.8143
          chef-dk-complete: 0.0
          Health check: 47.8121
          Packaging: 362.3896
      el-6:
        result: SUCCESS
        timestamp: '2016-05-17T08:31:59-07:00'
        duration: 1563.699
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/422/
        omnibusTiming:
          chef-dk: 232.1439
          chef-dk-appbundle: 506.9417
          gem-permissions: 8.5476
          chef-dk-remove-docs: 0.1942
          rubygems-customization: 0.2421
          shebang-cleanup: 0.0294
          version-manifest: 0.1713
          openssl-customization: 0.2309
          clean-static-libs: 1.0515
          chef-dk-complete: 0.0
          Health check: 55.1106
          Packaging: 486.4249
      el-7:
        result: SUCCESS
        timestamp: '2016-05-17T08:31:59-07:00'
        duration: 1095.121
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/422/
        omnibusTiming:
          chef-dk: 157.336
          chef-dk-appbundle: 355.8377
          gem-permissions: 4.6181
          chef-dk-remove-docs: 0.1041
          rubygems-customization: 0.0887
          shebang-cleanup: 0.0072
          version-manifest: 0.033
          openssl-customization: 0.0784
          clean-static-libs: 0.3424
          chef-dk-complete: 0.0
          Health check: 21.6377
          Packaging: 370.4326
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-17T08:31:59-07:00'
        duration: 608.544
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/422/
        omnibusTiming:
          chef-dk: 128.9831
          chef-dk-appbundle: 185.2868
          gem-permissions: 4.2407
          chef-dk-remove-docs: 0.0754
          rubygems-customization: 0.074
          shebang-cleanup: 0.0568
          version-manifest: 0.032
          openssl-customization: 0.0799
          clean-static-libs: 0.3858
          chef-dk-complete: 0.0
          Health check: 1.0091
          Packaging: 36.3454
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-17T08:31:59-07:00'
        duration: 1241.99
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/422/
        omnibusTiming:
          chef-dk: 192.5791
          chef-dk-appbundle: 447.1506
          gem-permissions: 5.8834
          chef-dk-remove-docs: 0.0891
          rubygems-customization: 0.1388
          shebang-cleanup: 0.0181
          version-manifest: 0.035
          openssl-customization: 0.139
          clean-static-libs: 0.4105
          chef-dk-complete: 0.0
          Health check: 24.3025
          Packaging: 383.1091
  chefdk-test:
    result: SUCCESS
    timestamp: '2016-05-17T09:23:05-07:00'
    duration: 1800.825
    url: http://manhattan.ci.chef.co/job/chefdk-test/181/
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.27
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.27
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 791122929aa343d7155071ea84811fa0b218e87a
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '69'
      GIT_BRANCH: v0.14.27
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '422'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-69/69/2016-05-17_15-31-49
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 577.967
        builtOn: chefdk-windows-2008r2-i386-tester-008788
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/181/
        omnibusTiming: {}
      acceptance:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 46.98
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/181/
        omnibusTiming: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 987.471
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/181/
        omnibusTiming: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 830.18
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/181/
        omnibusTiming: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 822.93
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/181/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 1700.034
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/181/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 662.807
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/181/
        omnibusTiming: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 568.904
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/181/
        omnibusTiming: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 454.505
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/181/
        omnibusTiming: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 548.343
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/181/
        omnibusTiming: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 711.484
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/181/
        omnibusTiming: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-17T09:23:05-07:00'
        duration: 902.566
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/181/
        omnibusTiming: {}
  chefdk-promote:
    result: SUCCESS
    timestamp: '2016-05-17T09:53:16-07:00'
    duration: 11.507
    url: http://manhattan.ci.chef.co/job/chefdk-promote/77/
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.27
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.27
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 791122929aa343d7155071ea84811fa0b218e87a
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '69'
      GIT_BRANCH: v0.14.27
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '422'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-69/69/2016-05-17_15-31-49
    runs: {}
