---
result: SUCCESS
timestamp: '2016-05-12T14:22:30-07:00'
duration: 5154.255000000001
version: 0.14.18
git_commit: 2ba2e197eb95a6229fb2b61ced477a79e8d9863c
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-12T14:22:30-07:00'
    duration: 6.419
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/59/
    parameters:
      GIT_REF: v0.14.18
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-05-12T14:22:45-07:00'
    duration: 1568.675
    url: http://manhattan.ci.chef.co/job/chefdk-build/393/
    runs:
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-12T14:22:45-07:00'
        duration: 1253.89
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/393/
        omnibus_timing:
          chef-dk: 199.3795
          chef-dk-appbundle: 454.6357
          gem-permissions: 6.3659
          chef-dk-remove-docs: 0.1387
          rubygems-customization: 0.1538
          shebang-cleanup: 0.026
          version-manifest: 0.1925
          openssl-customization: 0.2232
          clean-static-libs: 0.6757
          chef-dk-complete: 0.0
          Health check: 46.5606
          Packaging: 354.4009
      el-6:
        result: SUCCESS
        timestamp: '2016-05-12T14:22:45-07:00'
        duration: 1507.47
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/393/
        omnibus_timing:
          chef-dk: 226.8899
          chef-dk-appbundle: 494.4044
          gem-permissions: 8.1998
          chef-dk-remove-docs: 0.1775
          rubygems-customization: 0.1892
          shebang-cleanup: 0.1344
          version-manifest: 0.2086
          openssl-customization: 0.1642
          clean-static-libs: 0.9509
          chef-dk-complete: 0.0
          Health check: 54.5496
          Packaging: 477.9674
      el-7:
        result: SUCCESS
        timestamp: '2016-05-12T14:22:45-07:00'
        duration: 1074.099
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/393/
        omnibus_timing:
          chef-dk: 160.8052
          chef-dk-appbundle: 367.6886
          gem-permissions: 4.5863
          chef-dk-remove-docs: 0.1041
          rubygems-customization: 0.0792
          shebang-cleanup: 0.0328
          version-manifest: 0.0338
          openssl-customization: 0.0899
          clean-static-libs: 0.3215
          chef-dk-complete: 0.0
          Health check: 20.5049
          Packaging: 369.6849
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-12T14:22:45-07:00'
        duration: 632.544
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/393/
        omnibus_timing:
          chef-dk: 127.6859
          chef-dk-appbundle: 168.431
          gem-permissions: 4.3348
          chef-dk-remove-docs: 0.0985
          rubygems-customization: 0.0831
          shebang-cleanup: 0.0462
          version-manifest: 0.0233
          openssl-customization: 0.0949
          clean-static-libs: 0.6024
          chef-dk-complete: 0.0
          Health check: 1.4012
          Packaging: 38.5024
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-12T14:22:45-07:00'
        duration: 1211.743
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/393/
        omnibus_timing:
          chef-dk: 202.3175
          chef-dk-appbundle: 438.3191
          gem-permissions: 5.8629
          chef-dk-remove-docs: 0.0888
          rubygems-customization: 0.0887
          shebang-cleanup: 0.0247
          version-manifest: 0.0369
          openssl-customization: 0.1316
          clean-static-libs: 0.4015
          chef-dk-complete: 0.0
          Health check: 23.4644
          Packaging: 372.7774
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-12T14:22:45-07:00'
        duration: 1562.074
        builtOn: chefdk-windows-2008r2-i386-builder-53e13c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/393/
        omnibus_timing:
          chef-dk: 321.1109
          chef-dk-appbundle: 238.2124
          gem-permissions: 0.0
          chef-dk-env-customization: 0.0936
          chef-dk-powershell-scripts: 0.8268
          ruby-windows-devkit: 10.1712
          chef-dk-remove-docs: 0.4524
          rubygems-customization: 0.1092
          shebang-cleanup: 3.3852
          version-manifest: 0.0624
          openssl-customization: 0.2184
          clean-static-libs: 0.468
          chef-dk-complete: 0.0
          Health check: 0.0312
          Packaging: 316.4936
    parameters:
      GIT_REF: v0.14.18
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 2ba2e197eb95a6229fb2b61ced477a79e8d9863c
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '59'
      GIT_BRANCH: v0.14.18
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
  chefdk-test:
    result: SUCCESS
    timestamp: '2016-05-12T14:49:02-07:00'
    duration: 3567.579
    url: http://manhattan.ci.chef.co/job/chefdk-test/167/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 3566.549
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/167/
        omnibus_timing: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 959.528
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/167/
        omnibus_timing: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 743.795
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/167/
        omnibus_timing: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 822.297
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/167/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 1654.983
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/167/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 670.3
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/167/
        omnibus_timing: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 558.666
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/167/
        omnibus_timing: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 447.122
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/167/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 572.064
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/167/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 684.651
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/167/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 899.142
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/167/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-12T14:49:02-07:00'
        duration: 693.174
        builtOn: chefdk-windows-2008r2-i386-tester-008788
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/167/
        omnibus_timing: {}
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.18
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.18
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 2ba2e197eb95a6229fb2b61ced477a79e8d9863c
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '59'
      GIT_BRANCH: v0.14.18
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '393'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-59/59/2016-05-12_21-22-30
  chefdk-promote:
    result: SUCCESS
    timestamp: '2016-05-12T15:48:35-07:00'
    duration: 11.582
    url: http://manhattan.ci.chef.co/job/chefdk-promote/74/
    runs: {}
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.18
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.18
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 2ba2e197eb95a6229fb2b61ced477a79e8d9863c
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '59'
      GIT_BRANCH: v0.14.18
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '393'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-59/59/2016-05-12_21-22-30
