---
result: FAILURE
timestamp: '2016-05-05T08:43:29-07:00'
duration: 6044.030000000001
version: 0.14.9
git_commit: 3e38ce04a4d54cc4775ec15768b20efdf9df2d30
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-05T08:43:29-07:00'
    duration: 2.638
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/50/
    parameters:
      GIT_REF: v0.14.9
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-05-05T08:43:39-07:00'
    duration: 2767.309
    url: http://manhattan.ci.chef.co/job/chefdk-build/374/
    runs:
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-05T08:43:39-07:00'
        duration: 2313.628
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/374/
        omnibus_timing:
          chef-dk: 204.0083
          chef-dk-appbundle: 464.4255
          chef-dk-remove-docs: 0.0972
          rubygems-customization: 0.1607
          shebang-cleanup: 0.0347
          version-manifest: 0.1799
          openssl-customization: 0.1656
          rust: 7.1927
          delivery-cli: 683.1333
          rust-uninstall: 1.8839
          curl: 98.9713
          ncurses: 78.5132
          libedit: 23.5919
          pcre: 24.6764
          expat: 13.8756
          git: 27.3225
          clean-static-libs: 0.7684
          chef-dk-complete: 0.0
          Health check: 52.7593
          Packaging: 366.0808
      el-6:
        result: SUCCESS
        timestamp: '2016-05-05T08:43:39-07:00'
        duration: 2762.482
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/374/
        omnibus_timing:
          chef-dk: 231.7803
          chef-dk-appbundle: 518.5774
          chef-dk-remove-docs: 0.1843
          rubygems-customization: 0.205
          shebang-cleanup: 0.0929
          version-manifest: 0.2778
          openssl-customization: 0.26
          rust: 17.0661
          delivery-cli: 743.8519
          rust-uninstall: 3.589
          curl: 127.713
          ncurses: 115.2546
          libedit: 30.0968
          pcre: 30.2961
          expat: 18.6202
          git: 37.3927
          clean-static-libs: 1.0816
          chef-dk-complete: 0.0
          Health check: 61.7753
          Packaging: 495.1181
      el-7:
        result: SUCCESS
        timestamp: '2016-05-05T08:43:39-07:00'
        duration: 1973.318
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/374/
        omnibus_timing:
          chef-dk: 155.357
          chef-dk-appbundle: 354.0795
          chef-dk-remove-docs: 0.0558
          rubygems-customization: 0.0821
          shebang-cleanup: 0.0074
          version-manifest: 0.0323
          openssl-customization: 0.1146
          rust: 5.5114
          delivery-cli: 603.3882
          rust-uninstall: 1.0491
          curl: 63.6201
          ncurses: 59.7988
          libedit: 13.4006
          pcre: 14.0097
          expat: 7.342
          git: 21.3078
          clean-static-libs: 0.3174
          chef-dk-complete: 0.0
          Health check: 23.4807
          Packaging: 384.2334
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-05T08:43:39-07:00'
        duration: 1075.737
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/374/
        omnibus_timing:
          chef-dk: 174.4608
          chef-dk-appbundle: 182.9715
          chef-dk-remove-docs: 0.0316
          rubygems-customization: 0.0731
          shebang-cleanup: 0.0376
          version-manifest: 0.0244
          openssl-customization: 0.0807
          rust: 3.7224
          delivery-cli: 100.7204
          rust-uninstall: 1.0303
          curl: 48.3239
          ncurses: 68.0989
          libedit: 11.603
          pcre: 23.1968
          expat: 8.1626
          git: 41.3167
          clean-static-libs: 0.4549
          chef-dk-complete: 0.0
          Health check: 0.8257
          Packaging: 31.8283
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-05T08:43:39-07:00'
        duration: 2218.975
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/374/
        omnibus_timing:
          chef-dk: 207.7773
          chef-dk-appbundle: 443.3944
          chef-dk-remove-docs: 0.0624
          rubygems-customization: 0.1022
          shebang-cleanup: 0.0236
          version-manifest: 0.0366
          openssl-customization: 0.1331
          rust: 3.5201
          delivery-cli: 753.1974
          rust-uninstall: 0.7957
          curl: 63.6676
          ncurses: 55.5914
          libedit: 13.9069
          pcre: 16.5649
          expat: 7.5526
          git: 22.8454
          clean-static-libs: 0.3702
          chef-dk-complete: 0.0
          Health check: 26.5101
          Packaging: 384.2152
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-05T08:43:39-07:00'
        duration: 1787.822
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/374/
        omnibus_timing:
          chef-dk: 318.197
          chef-dk-appbundle: 301.4473
          chef-dk-env-customization: 0.2344
          chef-dk-powershell-scripts: 1.1562
          ruby-windows-devkit: 21.2808
          chef-dk-remove-docs: 1.0937
          rubygems-customization: 0.1875
          shebang-cleanup: 4.9218
          version-manifest: 0.0781
          openssl-customization: 0.375
          git-windows: 47.9522
          clean-static-libs: 0.6719
          chef-dk-complete: 0.0
          Health check: 0.0469
          Packaging: 532.9933
    parameters:
      GIT_REF: v0.14.9
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 3e38ce04a4d54cc4775ec15768b20efdf9df2d30
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '50'
      GIT_BRANCH: v0.14.9
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
  chefdk-test:
    result: FAILURE
    failures: bsd,debian,el,mac_os_x,ubuntu
    timestamp: '2016-05-05T09:29:56-07:00'
    duration: 3274.083
    url: http://manhattan.ci.chef.co/job/chefdk-test/149/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 3271.166
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/149/
        omnibus_timing: {}
      debian-6:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 1028.969
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/149/
      debian-7:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 741.06
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/149/
      debian-8:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 813.656
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/149/
      el-6:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 1667.237
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/149/
      el-7:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 749.132
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/149/
      mac_os_x-10.10:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 634.829
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/149/
      mac_os_x-10.11:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 498.12
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/149/
      mac_os_x-10.9:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 662.321
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/149/
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 697.428
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/149/
      ubuntu-14.04:
        result: FAILURE
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 900.42
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/149/
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-05T09:29:56-07:00'
        duration: 606.226
        builtOn: chefdk-windows-2008r2-i386-tester-e50cbf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/149/
        omnibus_timing: {}
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.9
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.9
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 3e38ce04a4d54cc4775ec15768b20efdf9df2d30
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '50'
      GIT_BRANCH: v0.14.9
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '374'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-50/50/2016-05-05_15-43-29
