---
result: FAILURE
timestamp: '2016-05-12T11:57:14-07:00'
duration: 5834.298000000001
version: 0.14.17
git_commit: a103175c18a9368b88f2d5258d434389e01546d2
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-12T11:57:14-07:00'
    duration: 5.932
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/58/
    parameters:
      GIT_REF: v0.14.17
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-05-12T11:57:26-07:00'
    duration: 1563.664
    url: http://manhattan.ci.chef.co/job/chefdk-build/392/
    parameters:
      GIT_REF: v0.14.17
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: a103175c18a9368b88f2d5258d434389e01546d2
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '58'
      GIT_BRANCH: v0.14.17
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-12T11:57:26-07:00'
        duration: 1468.726
        builtOn: chefdk-windows-2008r2-i386-builder-53e13c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/392/
        omnibusTiming:
          chef-dk: 277.5713
          chef-dk-appbundle: 221.9104
          gem-permissions: 0.0
          chef-dk-env-customization: 0.0936
          chef-dk-powershell-scripts: 0.8892
          ruby-windows-devkit: 9.9216
          chef-dk-remove-docs: 0.3432
          rubygems-customization: 0.0936
          shebang-cleanup: 3.3852
          version-manifest: 0.0624
          openssl-customization: 0.2184
          clean-static-libs: 0.4524
          chef-dk-complete: 0.0
          Health check: 0.0312
          Packaging: 313.1393
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-12T11:57:26-07:00'
        duration: 1279.57
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/392/
        omnibusTiming:
          chef-dk: 201.888
          chef-dk-appbundle: 461.5147
          gem-permissions: 6.5971
          chef-dk-remove-docs: 0.1373
          rubygems-customization: 0.1489
          shebang-cleanup: 0.0224
          version-manifest: 0.1413
          openssl-customization: 0.1577
          clean-static-libs: 0.7205
          chef-dk-complete: 0.0
          Health check: 47.7776
          Packaging: 362.5404
      el-6:
        result: SUCCESS
        timestamp: '2016-05-12T11:57:26-07:00'
        duration: 1558.646
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/392/
        omnibusTiming:
          chef-dk: 230.4093
          chef-dk-appbundle: 516.0576
          gem-permissions: 8.6969
          chef-dk-remove-docs: 0.1896
          rubygems-customization: 0.1991
          shebang-cleanup: 0.0355
          version-manifest: 0.1752
          openssl-customization: 0.2019
          clean-static-libs: 1.0571
          chef-dk-complete: 0.0
          Health check: 56.7106
          Packaging: 488.096
      el-7:
        result: SUCCESS
        timestamp: '2016-05-12T11:57:26-07:00'
        duration: 1131.488
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/392/
        omnibusTiming:
          chef-dk: 163.1544
          chef-dk-appbundle: 354.8316
          gem-permissions: 4.9005
          chef-dk-remove-docs: 0.123
          rubygems-customization: 0.0917
          shebang-cleanup: 0.0072
          version-manifest: 0.0341
          openssl-customization: 0.0942
          clean-static-libs: 0.3037
          chef-dk-complete: 0.0
          Health check: 21.7426
          Packaging: 374.7022
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-12T11:57:26-07:00'
        duration: 633.247
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/392/
        omnibusTiming:
          chef-dk: 128.2647
          chef-dk-appbundle: 177.1681
          gem-permissions: 3.5714
          chef-dk-remove-docs: 0.0889
          rubygems-customization: 0.09
          shebang-cleanup: 0.0606
          version-manifest: 0.0228
          openssl-customization: 0.0873
          clean-static-libs: 0.7427
          chef-dk-complete: 0.0
          Health check: 1.1923
          Packaging: 39.5628
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-12T11:57:26-07:00'
        duration: 1240.729
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/392/
        omnibusTiming:
          chef-dk: 199.0181
          chef-dk-appbundle: 441.2139
          gem-permissions: 6.0196
          chef-dk-remove-docs: 0.1054
          rubygems-customization: 0.1068
          shebang-cleanup: 0.0063
          version-manifest: 0.0373
          openssl-customization: 0.1056
          clean-static-libs: 0.3603
          chef-dk-complete: 0.0
          Health check: 24.7618
          Packaging: 381.8921
  chefdk-test:
    result: FAILURE
    failures: acceptance
    timestamp: '2016-05-12T12:23:37-07:00'
    duration: 4264.702
    url: http://manhattan.ci.chef.co/job/chefdk-test/166/
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.17
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.17
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: a103175c18a9368b88f2d5258d434389e01546d2
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '58'
      GIT_BRANCH: v0.14.17
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '392'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-58/58/2016-05-12_18-57-14
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 631.156
        builtOn: chefdk-windows-2008r2-i386-tester-008788
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/166/
        omnibusTiming: {}
      acceptance:
        result: FAILURE
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 2759.295
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/166/
        omnibusTiming: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 977.357
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/166/
        omnibusTiming: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 740.282
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/166/
        omnibusTiming: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 839.806
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/166/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 1660.186
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/166/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 680.875
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/166/
        omnibusTiming: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 554.782
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/166/
        omnibusTiming: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 441.467
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/166/
        omnibusTiming: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 556.231
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/166/
        omnibusTiming: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 699.895
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/166/
        omnibusTiming: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-12T12:23:37-07:00'
        duration: 882.666
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/166/
        omnibusTiming: {}
