---
result: FAILURE
timestamp: '2016-03-24T13:53:32-07:00'
duration: 10585.218
version: 0.13.1
git_commit: c152afaae4094b73f85cf9b97f54910e244cf6ea
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-03-24T13:53:32-07:00'
    duration: 2.314
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/15/
    parameters:
      GIT_REF: v0.13.1
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-03-24T13:53:42-07:00'
    duration: 8933.53
    url: http://manhattan.ci.chef.co/job/chefdk-build/139/
    parameters:
      GIT_REF: v0.13.1
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: c152afaae4094b73f85cf9b97f54910e244cf6ea
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '15'
      GIT_BRANCH: v0.13.1
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-03-24T13:53:42-07:00'
        duration: 4648.598
        builtOn: chefdk-windows-2008r2-i386-builder-4b316d
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/139/
        omnibusTiming: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-03-24T13:53:42-07:00'
        duration: 885.693
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/139/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-24T13:53:42-07:00'
        duration: 1122.098
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/139/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-24T13:53:42-07:00'
        duration: 836.236
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/139/
        omnibusTiming: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-24T13:53:42-07:00'
        duration: 1660.899
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/139/
        omnibusTiming: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-24T13:53:42-07:00'
        duration: 846.064
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/139/
        omnibusTiming: {}
  chefdk-test:
    result: FAILURE
    failures:
      chef_verify[test-kitchen]: debian,el,mac_os_x,ubuntu
    timestamp: '2016-03-24T16:22:44-07:00'
    duration: 1649.374
    url: http://manhattan.ci.chef.co/job/chefdk-test/61/
    parameters:
      OMNIBUS_BUILD_VERSION: 0.13.1
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.13.1
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: c152afaae4094b73f85cf9b97f54910e244cf6ea
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '15'
      GIT_BRANCH: v0.13.1
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '139'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-15/15/2016-03-24_20-53-32
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 1647.638
        builtOn: chefdk-windows-2008r2-i386-tester-e50cbf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/61/
        omnibusTiming: {}
      acceptance:
        result: SUCCESS
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 196.922
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/61/
        omnibusTiming: {}
        acceptanceTiming:
        - trivial:
            provision: '00:01:35'
            verify: '00:00:08'
            destroy: '00:00:08'
            Total: '00:02:05'
          Run:
            Total: '00:02:05'
      debian-6:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 678.878
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
      debian-7:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 554.227
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
      debian-8:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 591.259
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
      el-6:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 1298.776
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
      el-7:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 474.64
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
      mac_os_x-10.10:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 567.728
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
          suspiciousLines:
          - 'find: /Volumes/chefdk/.Trashes: Permission denied'
      mac_os_x-10.11:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 530.299
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
          suspiciousLines:
          - 'find: /Volumes/chefdk/.Trashes: Permission denied'
      mac_os_x-10.9:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 583.067
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
          suspiciousLines:
          - 'find: /Volumes/chefdk/.Trashes: Permission denied'
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 475.132
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
      ubuntu-14.04:
        result: FAILURE
        timestamp: '2016-03-24T16:22:44-07:00'
        duration: 1112.449
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/61/
        omnibusTiming: {}
        failureCause:
          cause: chef_verify
          detailedCause: chef_verify[test-kitchen]
          jenkinsBuildStep: Invoke XShell command
          tests:
            chef_verify:
            - test-kitchen
