---
result: FAILURE
timestamp: '2016-05-09T08:51:21-07:00'
duration: 8234.295
version: 
git_commit: 8afb870557320716dc7cfce8ef52b87a79047336
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-09T08:51:21-07:00'
    duration: 2.523
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/55/
    parameters:
      GIT_REF: v0.14.14
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: FAILURE
    failures: bsd,debian
    timestamp: '2016-05-09T08:51:31-07:00'
    duration: 8231.772
    url: http://manhattan.ci.chef.co/job/chefdk-build/383/
    runs:
      debian-6:
        result: FAILURE
        timestamp: '2016-05-09T08:51:31-07:00'
        duration: 1637.753
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/383/
      el-6:
        result: SUCCESS
        timestamp: '2016-05-09T08:51:31-07:00'
        duration: 4974.391
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/383/
        omnibus_timing:
          preparation: 0.0364
          zlib: 3.8361
          config_guess: 0.0198
          libiconv: 71.9755
          liblzma: 69.2489
          libxml2: 97.8611
          libxslt: 42.9708
          libarchive: 96.4981
          m4: 81.3355
          autoconf: 10.8086
          automake: 12.9342
          libtool: 38.205
          libsodium: 353.0316
          libzmq: 113.2847
          cacerts: 0.0556
          xproto: 13.0194
          util-macros: 3.1764
          pkg-config-lite: 14.9315
          makedepend: 12.9449
          openssl: 149.0698
          libffi: 25.4626
          libyaml: 23.6279
          ruby: 246.3213
          rubygems: 40.5718
          bundler: 1.9889
          chef-dk-gem-dep-selector-libgecode: 380.1415
          chef-dk-gem-ffi-rzmq: 8.8269
          chef-dk-gem-libyajl2: 10.4011
          chef-dk-gem-ffi-yajl: 13.72
          chef-dk-gem-json: 11.8007
          chef-dk-gem-mini_portile2: 8.6468
          chef-dk-gem-nokogiri: 19.963
          chef-dk-gem-ffi: 15.8625
          chef-dk-gem-ruby-prof: 16.6387
          chef-dk-gem-dep_selector: 13.7537
          chef-dk-gem-nio4r: 11.5515
          chef-dk-gem-byebug: 9.9549
          chef-dk-gem-yajl-ruby: 10.7331
          chef-dk-gem-hitimes: 11.4748
          chef-dk-gem-debug_inspector: 9.6072
          chef-dk-gem-binding_of_caller: 9.5256
          chef-dk-gem-cookstyle: 8.9545
          chef-dk-gem-ruby-shadow: 13.7078
          chef-dk: 240.4941
          chef-dk-appbundle: 518.7071
          gem-permissions: 8.6555
          chef-dk-remove-docs: 0.092
          rubygems-customization: 0.2162
          shebang-cleanup: 0.0247
          version-manifest: 0.3266
          openssl-customization: 0.2065
          rust: 21.607
          delivery-cli: 741.2278
          rust-uninstall: 3.5609
          curl: 139.5561
          ncurses: 149.0411
          libedit: 33.5854
          pcre: 33.2436
          expat: 19.1584
          git: 51.9239
          clean-static-libs: 1.0407
          chef-dk-complete: 0.0
          Health check: 62.0954
          Packaging: 497.2782
      el-7:
        result: SUCCESS
        timestamp: '2016-05-09T08:51:31-07:00'
        duration: 2920.143
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/383/
        omnibus_timing:
          preparation: 0.0045
          zlib: 1.8604
          config_guess: 0.0039
          libiconv: 33.4084
          liblzma: 40.1847
          libxml2: 48.5346
          libxslt: 19.3499
          libarchive: 53.9974
          m4: 42.9674
          autoconf: 5.5178
          automake: 6.5456
          libtool: 16.0365
          libsodium: 180.5848
          libzmq: 53.541
          cacerts: 0.0476
          xproto: 5.9319
          util-macros: 1.7361
          pkg-config-lite: 6.2749
          makedepend: 5.6366
          openssl: 80.3809
          libffi: 10.1833
          libyaml: 8.6759
          ruby: 129.3482
          rubygems: 27.7761
          bundler: 2.7535
          chef-dk-gem-dep-selector-libgecode: 38.4023
          chef-dk-gem-ffi-rzmq: 7.8171
          chef-dk-gem-libyajl2: 6.3091
          chef-dk-gem-ffi-yajl: 7.2368
          chef-dk-gem-json: 6.9016
          chef-dk-gem-mini_portile2: 5.2582
          chef-dk-gem-nokogiri: 13.0065
          chef-dk-gem-ffi: 9.8584
          chef-dk-gem-ruby-prof: 9.3893
          chef-dk-gem-dep_selector: 7.4105
          chef-dk-gem-nio4r: 7.0369
          chef-dk-gem-byebug: 5.888
          chef-dk-gem-yajl-ruby: 7.1802
          chef-dk-gem-hitimes: 6.2304
          chef-dk-gem-debug_inspector: 5.3756
          chef-dk-gem-binding_of_caller: 5.3728
          chef-dk-gem-cookstyle: 5.2428
          chef-dk-gem-ruby-shadow: 8.0227
          chef-dk: 158.2345
          chef-dk-appbundle: 359.0581
          gem-permissions: 4.7429
          chef-dk-remove-docs: 0.0578
          rubygems-customization: 0.089
          shebang-cleanup: 0.0068
          version-manifest: 0.0422
          openssl-customization: 0.0928
          rust: 9.4013
          delivery-cli: 608.2441
          rust-uninstall: 1.0832
          curl: 72.3552
          ncurses: 63.467
          libedit: 14.7873
          pcre: 14.5452
          expat: 7.3604
          git: 21.3496
          clean-static-libs: 0.3541
          chef-dk-complete: 0.0
          Health check: 23.761
          Packaging: 381.8093
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-09T08:51:31-07:00'
        duration: 1837.23
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/383/
        omnibus_timing:
          preparation: 0.0068
          zlib: 2.3835
          config_guess: 0.0079
          libiconv: 31.6069
          liblzma: 32.2816
          libxml2: 45.2409
          libxslt: 18.6905
          libarchive: 50.3052
          m4: 36.1182
          autoconf: 5.1652
          automake: 5.5096
          libtool: 13.0927
          libsodium: 81.5148
          libzmq: 49.4838
          cacerts: 0.0129
          xproto: 4.7405
          util-macros: 1.7181
          pkg-config-lite: 6.8621
          makedepend: 4.5064
          openssl: 73.2687
          libffi: 9.0349
          libyaml: 9.138
          ruby: 97.2661
          rubygems: 17.6569
          bundler: 1.7794
          chef-dk-gem-dep-selector-libgecode: 198.3191
          chef-dk-gem-ffi-rzmq: 5.5786
          chef-dk-gem-libyajl2: 4.9565
          chef-dk-gem-ffi-yajl: 5.7872
          chef-dk-gem-json: 5.432
          chef-dk-gem-mini_portile2: 3.8656
          chef-dk-gem-nokogiri: 12.2549
          chef-dk-gem-ffi: 8.4398
          chef-dk-gem-ruby-prof: 6.5432
          chef-dk-gem-dep_selector: 6.3715
          chef-dk-gem-nio4r: 4.3667
          chef-dk-gem-byebug: 3.7253
          chef-dk-gem-yajl-ruby: 4.3515
          chef-dk-gem-hitimes: 3.6547
          chef-dk-gem-debug_inspector: 3.2855
          chef-dk-gem-binding_of_caller: 3.043
          chef-dk-gem-cookstyle: 3.2405
          chef-dk-gem-ruby-shadow: 5.4674
          chef-dk: 133.6826
          chef-dk-appbundle: 193.3001
          gem-permissions: 3.8045
          chef-dk-remove-docs: 0.0403
          rubygems-customization: 0.0751
          shebang-cleanup: 0.0278
          version-manifest: 0.0218
          openssl-customization: 0.0852
          rust: 3.6269
          delivery-cli: 100.3455
          rust-uninstall: 1.024
          curl: 48.2437
          ncurses: 67.3695
          libedit: 13.0899
          pcre: 22.6793
          expat: 8.2046
          git: 41.5883
          clean-static-libs: 0.6375
          chef-dk-complete: 0.0
          Health check: 0.8792
          Packaging: 31.8944
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-09T08:51:31-07:00'
        duration: 3335.097
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/383/
        omnibus_timing:
          preparation: 0.0137
          zlib: 1.771
          config_guess: 0.0045
          libiconv: 34.1658
          liblzma: 40.4361
          libxml2: 56.2337
          libxslt: 19.9189
          libarchive: 53.9284
          m4: 45.5367
          autoconf: 5.5441
          automake: 6.9906
          libtool: 14.457
          libsodium: 205.2129
          libzmq: 60.9563
          cacerts: 0.0479
          xproto: 6.2167
          util-macros: 1.8383
          pkg-config-lite: 6.2815
          makedepend: 5.9654
          openssl: 90.3826
          libffi: 11.4283
          libyaml: 9.4691
          ruby: 147.6178
          rubygems: 35.7759
          bundler: 2.0734
          chef-dk-gem-dep-selector-libgecode: 53.6346
          chef-dk-gem-ffi-rzmq: 7.818
          chef-dk-gem-libyajl2: 7.4653
          chef-dk-gem-ffi-yajl: 8.9578
          chef-dk-gem-json: 16.3124
          chef-dk-gem-mini_portile2: 6.569
          chef-dk-gem-nokogiri: 17.1192
          chef-dk-gem-ffi: 11.6816
          chef-dk-gem-ruby-prof: 11.3509
          chef-dk-gem-dep_selector: 9.3723
          chef-dk-gem-nio4r: 8.3984
          chef-dk-gem-byebug: 7.2951
          chef-dk-gem-yajl-ruby: 7.9387
          chef-dk-gem-hitimes: 8.2903
          chef-dk-gem-debug_inspector: 7.9905
          chef-dk-gem-binding_of_caller: 7.0353
          chef-dk-gem-cookstyle: 6.7411
          chef-dk-gem-ruby-shadow: 10.1668
          chef-dk: 219.4932
          chef-dk-appbundle: 447.8555
          gem-permissions: 6.2111
          chef-dk-remove-docs: 0.0753
          rubygems-customization: 0.097
          shebang-cleanup: 0.0067
          version-manifest: 0.0363
          openssl-customization: 0.1066
          rust: 4.6385
          delivery-cli: 759.4374
          rust-uninstall: 0.7521
          curl: 64.5711
          ncurses: 57.2033
          libedit: 14.56
          pcre: 15.918
          expat: 7.2784
          git: 23.4864
          clean-static-libs: 0.4309
          chef-dk-complete: 0.0
          Health check: 26.7726
          Packaging: 388.8466
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-09T08:51:31-07:00'
        duration: 8226.415
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/383/
        omnibus_timing:
          preparation: 0.1719
          zlib: 79.4063
          config_guess: 0.1094
          libiconv: 277.0632
          liblzma: 222.8446
          libxml2: 467.5645
          libxslt: 298.9544
          libarchive: 435.9551
          libzmq4x-windows: 0.3125
          cacerts: 0.1719
          openssl: 672.1129
          libffi: 159.4384
          libyaml: 164.0632
          ruby: 1164.4423
          rubygems: 25.922
          bundler: 3.6719
          chef-dk-gem-dep-selector-libgecode: 834.9405
          chef-dk-gem-ffi-rzmq: 6.2502
          chef-dk-gem-libyajl2: 130.1766
          chef-dk-gem-ffi-yajl: 231.7738
          chef-dk-gem-json: 228.32
          chef-dk-gem-mini_portile2: 5.9064
          chef-dk-gem-nokogiri: 131.2855
          chef-dk-gem-ffi: 113.6911
          chef-dk-gem-ruby-prof: 105.3627
          chef-dk-gem-dep_selector: 99.6907
          chef-dk-gem-nio4r: 91.0653
          chef-dk-gem-byebug: 85.0652
          chef-dk-gem-yajl-ruby: 82.9711
          chef-dk-gem-hitimes: 82.9557
          chef-dk-gem-debug_inspector: 81.1741
          chef-dk-gem-binding_of_caller: 78.549
          chef-dk-gem-cookstyle: 5.8752
          chef-dk-gem-ruby-shadow: 0.0313
          chef-dk: 308.6174
          chef-dk-appbundle: 301.4452
          gem-permissions: 0.0
          chef-dk-env-customization: 0.1406
          chef-dk-powershell-scripts: 1.1719
          ruby-windows-devkit: 21.9537
          chef-dk-remove-docs: 1.3125
          rubygems-customization: 0.1406
          shebang-cleanup: 4.8908
          version-manifest: 0.0781
          openssl-customization: 0.3438
          git-windows: 40.8917
          clean-static-libs: 0.875
          chef-dk-complete: 0.0
          Health check: 0.0469
          Packaging: 503.4488
    parameters:
      GIT_REF: v0.14.14
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 8afb870557320716dc7cfce8ef52b87a79047336
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '55'
      GIT_BRANCH: v0.14.14
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
