---
result: FAILURE
timestamp: '2016-03-23T14:19:20-07:00'
duration: 13621.162
version: 
git_commit: 8642eec99e35eed229f5c666021d3532284ebbb3
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-03-23T14:19:20-07:00'
    duration: 3.509
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/12/
    parameters:
      GIT_REF: v0.12.3
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: FAILURE
    failures: bsd,debian,el,ubuntu,windows
    timestamp: '2016-03-23T14:19:30-07:00'
    duration: 13617.653
    url: http://manhattan.ci.chef.co/job/chefdk-build/126/
    runs:
      debian-6:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 94.253
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/126/
      el-6:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 97.608
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/126/
      el-7:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 104.233
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/126/
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 1769.775
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/126/
        omnibus_timing: {}
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 46.978
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/126/
      windows-2008r2-i386:
        result: FAILURE
        timestamp: '2016-03-23T14:19:30-07:00'
        duration: 3788.758
        builtOn: chefdk-windows-2008r2-i386-builder-a728bb
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/126/
    parameters:
      GIT_REF: v0.12.3
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 8642eec99e35eed229f5c666021d3532284ebbb3
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '12'
      GIT_BRANCH: v0.12.3
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
