---
result: FAILURE
timestamp: '2016-05-16T17:30:31-07:00'
duration: 6842.347
version: 0.14.24
git_commit: 13d4becd249f03a3e63d821b6facfe9182528584
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-16T17:30:31-07:00'
    duration: 4.075
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/66/
    parameters:
      GIT_REF: v0.14.24
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-05-16T17:30:41-07:00'
    duration: 4988.305
    url: http://manhattan.ci.chef.co/job/chefdk-build/414/
    parameters:
      GIT_REF: v0.14.24
      APPEND_TIMESTAMP: false
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 13d4becd249f03a3e63d821b6facfe9182528584
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '66'
      GIT_BRANCH: v0.14.24
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-16T17:30:41-07:00'
        duration: 1499.758
        builtOn: chefdk-windows-2008r2-i386-builder-53e13c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/414/
        omnibusTiming:
          chef-dk: 295.0592
          chef-dk-appbundle: 220.9896
          gem-permissions: 0.0
          chef-dk-env-customization: 0.0936
          chef-dk-powershell-scripts: 0.7956
          ruby-windows-devkit: 9.672
          chef-dk-remove-docs: 0.3276
          rubygems-customization: 0.0936
          shebang-cleanup: 3.276
          version-manifest: 0.0624
          openssl-customization: 0.2184
          clean-static-libs: 0.4524
          chef-dk-complete: 0.0
          Health check: 0.0468
          Packaging: 293.1089
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-16T17:30:41-07:00'
        duration: 1309.844
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/414/
        omnibusTiming:
          chef-dk: 208.545
          chef-dk-appbundle: 464.2798
          gem-permissions: 7.1511
          chef-dk-remove-docs: 0.2139
          rubygems-customization: 0.1336
          shebang-cleanup: 0.0268
          version-manifest: 0.1414
          openssl-customization: 0.1666
          clean-static-libs: 0.5269
          chef-dk-complete: 0.0
          Health check: 47.8518
          Packaging: 362.9046
      el-6:
        result: SUCCESS
        timestamp: '2016-05-16T17:30:41-07:00'
        duration: 1575.647
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/414/
        omnibusTiming:
          chef-dk: 229.0588
          chef-dk-appbundle: 505.3474
          gem-permissions: 8.4644
          chef-dk-remove-docs: 0.1976
          rubygems-customization: 0.1846
          shebang-cleanup: 0.0314
          version-manifest: 0.2175
          openssl-customization: 0.2585
          clean-static-libs: 1.0862
          chef-dk-complete: 0.0
          Health check: 54.8165
          Packaging: 487.3316
      el-7:
        result: SUCCESS
        timestamp: '2016-05-16T17:30:41-07:00'
        duration: 1094.836
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/414/
        omnibusTiming:
          chef-dk: 155.7903
          chef-dk-appbundle: 357.0455
          gem-permissions: 4.5851
          chef-dk-remove-docs: 0.322
          rubygems-customization: 0.0815
          shebang-cleanup: 0.007
          version-manifest: 0.0515
          openssl-customization: 0.092
          clean-static-libs: 0.3041
          chef-dk-complete: 0.0
          Health check: 21.5594
          Packaging: 369.9976
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-16T17:30:41-07:00'
        duration: 613.078
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/414/
        omnibusTiming:
          chef-dk: 130.724
          chef-dk-appbundle: 186.1854
          gem-permissions: 4.401
          chef-dk-remove-docs: 0.0926
          rubygems-customization: 0.0704
          shebang-cleanup: 0.034
          version-manifest: 0.022
          openssl-customization: 0.0792
          clean-static-libs: 0.6514
          chef-dk-complete: 0.0
          Health check: 1.0779
          Packaging: 36.3976
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-16T17:30:41-07:00'
        duration: 1246.111
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/414/
        omnibusTiming:
          chef-dk: 189.6821
          chef-dk-appbundle: 447.2178
          gem-permissions: 5.746
          chef-dk-remove-docs: 0.1046
          rubygems-customization: 0.1015
          shebang-cleanup: 0.0078
          version-manifest: 0.0382
          openssl-customization: 0.1068
          clean-static-libs: 0.4118
          chef-dk-complete: 0.0
          Health check: 24.6883
          Packaging: 383.8194
  chefdk-test:
    result: FAILURE
    failures: acceptance
    timestamp: '2016-05-16T18:54:00-07:00'
    duration: 1849.967
    url: http://manhattan.ci.chef.co/job/chefdk-test/174/
    parameters:
      OMNIBUS_BUILD_VERSION: 0.14.24
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: v0.14.24
      APPEND_TIMESTAMP: false
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'true'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: 13d4becd249f03a3e63d821b6facfe9182528584
      PROJECT: chefdk
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '66'
      GIT_BRANCH: v0.14.24
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-release
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "debian-6": [
              "debian-6",
              "debian-7",
              "debian-8"
            ],
            "ubuntu-12.04": [
              "ubuntu-12.04",
              "ubuntu-14.04",
              "acceptance"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ],
            "mac_os_x-10.9": [
              "mac_os_x-10.9",
              "mac_os_x-10.10",
              "mac_os_x-10.11"
            ],
            "windows-2008r2": [
              "windows-2008r2",
              "windows-2012",
              "windows-2012r2"
            ]
          },
          "test_to_build": {
            "debian-6": "debian-6",
            "debian-7": "debian-6",
            "debian-8": "debian-6",
            "ubuntu-12.04": "ubuntu-12.04",
            "ubuntu-14.04": "ubuntu-12.04",
            "acceptance": "ubuntu-12.04",
            "el-6": "el-6",
            "el-7": "el-7",
            "mac_os_x-10.9": "mac_os_x-10.9",
            "mac_os_x-10.10": "mac_os_x-10.9",
            "mac_os_x-10.11": "mac_os_x-10.9",
            "windows-2008r2": "windows-2008r2",
            "windows-2012": "windows-2008r2",
            "windows-2012r2": "windows-2008r2"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '414'
      PIPELINE_BUILD_JOB_NAME: chefdk-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chefdk-trigger-release-66/66/2016-05-17_00-30-31
    runs:
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 593.465
        builtOn: chefdk-windows-2008r2-i386-tester-008788
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/174/
        omnibusTiming: {}
      acceptance:
        result: FAILURE
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 37.697
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/174/
        omnibusTiming: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 1046.114
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/174/
        omnibusTiming: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 770.288
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/174/
        omnibusTiming: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 824.822
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/174/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 1674.781
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/174/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 701.495
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/174/
        omnibusTiming: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 548.796
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/174/
        omnibusTiming: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 436.696
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/174/
        omnibusTiming: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 571.669
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/174/
        omnibusTiming: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 717.575
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/174/
        omnibusTiming: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-16T18:54:00-07:00'
        duration: 916.065
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/174/
        omnibusTiming: {}
