---
version: 
result: ABORTED
timestamp: '2016-04-04T23:06:08-07:00'
duration: 537.7900000000001
git_commit: e9801a488de6c997982c731acb9449cee18fbc56
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-04T23:06:08-07:00'
    duration: 5.238
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/22/
    parameters:
      GIT_REF: jk/chef-dk-gemset
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user John Keiser
      userId: jkeiser
      userName: John Keiser
    runs: {}
  chefdk-build:
    result: ABORTED
    timestamp: '2016-04-04T23:06:20-07:00'
    duration: 532.552
    url: http://manhattan.ci.chef.co/job/chefdk-build/185/
    causes:
    - shortDescription: Aborted by jkeiser
    runs:
      debian-6:
        result: FAILURE
        timestamp: '2016-04-04T23:06:20-07:00'
        duration: 82.693
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/185/
      el-6:
        result: FAILURE
        timestamp: '2016-04-04T23:06:20-07:00'
        duration: 99.371
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/185/
      el-7:
        result: FAILURE
        timestamp: '2016-04-04T23:06:20-07:00'
        duration: 73.368
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/185/
      mac_os_x-10.9:
        result: FAILURE
        timestamp: '2016-04-04T23:06:20-07:00'
        duration: 54.733
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/185/
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-04-04T23:06:20-07:00'
        duration: 68.843
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/185/
      windows-2008r2-i386:
        result: ABORTED
        timestamp: '2016-04-04T23:06:20-07:00'
        duration: 528.288
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/185/
