---
version: 
result: FAILURE
timestamp: '2016-04-08T10:24:57-07:00'
duration: 1724.736
git_commit: af0567d672d177b0f422c57922f14ac6a8e5b9b4
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-08T10:24:57-07:00'
    duration: 4.537
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/31/
    parameters:
      GIT_REF: master
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user John Keiser
      userId: jkeiser
      userName: John Keiser
    runs: {}
  chefdk-build:
    result: FAILURE
    timestamp: '2016-04-08T10:25:10-07:00'
    duration: 1720.199
    url: http://manhattan.ci.chef.co/job/chefdk-build/229/
    runs:
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-08T10:25:10-07:00'
        duration: 1405.759
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/229/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-08T10:25:10-07:00'
        duration: 1639.44
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/229/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-08T10:25:10-07:00'
        duration: 1156.714
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/229/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-08T10:25:10-07:00'
        duration: 655.318
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/229/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-08T10:25:10-07:00'
        duration: 1328.12
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/229/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-08T10:25:10-07:00'
        duration: 1714.065
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/229/
        omnibus_builders: {}
