---
version: 0.13.15
result: SUCCESS
timestamp: '2016-04-08T19:34:28-07:00'
duration: 8125.741
git_commit: a520c3565c231f8e26b7547c0ad6ce7cf38e1dcb
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-08T19:34:28-07:00'
    duration: 8.997
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/33/
    parameters:
      GIT_REF: v0.13.15
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-04-08T19:34:43-07:00'
    duration: 2063.351
    url: http://manhattan.ci.chef.co/job/chefdk-build/234/
    runs:
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-08T19:34:43-07:00'
        duration: 1375.643
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/234/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-08T19:34:43-07:00'
        duration: 1598.302
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/234/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-08T19:34:43-07:00'
        duration: 1314.588
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/234/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-08T19:34:43-07:00'
        duration: 677.005
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/234/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-08T19:34:43-07:00'
        duration: 1362.785
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/234/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-08T19:34:43-07:00'
        duration: 2056.51
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/234/
        omnibus_timing: {}
  chefdk-test:
    result: SUCCESS
    timestamp: '2016-04-08T20:09:14-07:00'
    duration: 6041.007
    url: http://manhattan.ci.chef.co/job/chefdk-test/93/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 6040.684
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/93/
        omnibus_timing: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 1087.515
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/93/
        omnibus_timing: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 843.547
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/93/
        omnibus_timing: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 869.633
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/93/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 1682.332
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/93/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 697.225
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/93/
        omnibus_timing: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 554.415
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/93/
        omnibus_timing: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 432.992
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/93/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 562.163
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/93/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 765.442
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/93/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 989.363
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/93/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-08T20:09:14-07:00'
        duration: 512.041
        builtOn: chefdk-windows-2008r2-i386-tester-e50cbf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/93/
        omnibus_timing: {}
  chefdk-promote:
    result: SUCCESS
    timestamp: '2016-04-08T21:50:00-07:00'
    duration: 12.386
    url: http://manhattan.ci.chef.co/job/chefdk-promote/33/
    runs: {}
