---
version: 0.13.19
result: FAILURE
timestamp: '2016-04-12T10:12:08-07:00'
duration: 3463.0299999999997
git_commit: 577815f788a384c051fff7bb5c7cc703882f9669
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-12T10:12:08-07:00'
    duration: 10.526
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/37/
    parameters:
      GIT_REF: v0.13.19
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-04-12T10:12:28-07:00'
    duration: 1718.924
    url: http://manhattan.ci.chef.co/job/chefdk-build/238/
    runs:
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-12T10:12:28-07:00'
        duration: 1490.17
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/238/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-12T10:12:28-07:00'
        duration: 1681.722
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/238/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-12T10:12:28-07:00'
        duration: 1345.625
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/238/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-12T10:12:28-07:00'
        duration: 678.055
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/238/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-12T10:12:28-07:00'
        duration: 1397.417
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/238/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-12T10:12:28-07:00'
        duration: 1705.297
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/238/
        omnibus_builders: {}
  chefdk-test:
    result: FAILURE
    timestamp: '2016-04-12T12:28:59-07:00'
    duration: 1733.58
    url: http://manhattan.ci.chef.co/job/chefdk-test/98/
    causes:
    - shortDescription: Started by user Tyler Ball
      userId: tyler-ball
      userName: Tyler Ball
    runs:
      acceptance:
        result: FAILURE
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 211.546
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/98/
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 1129.864
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/98/
        omnibus_builders: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 827.669
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/98/
        omnibus_builders: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 876.581
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/98/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 1731.373
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/98/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 768.511
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/98/
        omnibus_builders: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 653.783
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/98/
        omnibus_builders: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 522.47
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/98/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 677.128
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/98/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 851.016
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/98/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 974.104
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/98/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-12T12:28:59-07:00'
        duration: 516.748
        builtOn: chefdk-windows-2008r2-i386-tester-e50cbf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/98/
        omnibus_builders: {}
    retryOf:
    - 97
