---
version: 
result: ABORTED
timestamp: '2016-03-15T12:07:43-07:00'
duration: 17004.041999999998
git_commit: 9d926d87e73be3d81c992c4a9a692d22dbe3b708
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-03-15T12:07:43-07:00'
    duration: 2.402
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/4/
    parameters:
      GIT_REF: master
      EXPIRE_CACHE: true
    causes:
    - shortDescription: Started by user Matt Wrock
      userId: mwrock
      userName: Matt Wrock
    runs: {}
  chefdk-build:
    result: ABORTED
    timestamp: '2016-03-15T12:07:54-07:00'
    duration: 17001.64
    url: http://manhattan.ci.chef.co/job/chefdk-build/94/
    runs:
      debian-6:
        result: ABORTED
        timestamp: '2016-03-15T12:07:54-07:00'
        duration: 14189.975
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/94/
      el-6:
        result: SUCCESS
        timestamp: '2016-03-15T12:07:54-07:00'
        duration: 3783.374
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/94/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-15T12:07:54-07:00'
        duration: 2428.066
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/94/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-15T12:07:54-07:00'
        duration: 1994.596
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/94/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-15T12:07:54-07:00'
        duration: 2386.866
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/94/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: FAILURE
        timestamp: '2016-03-15T12:07:54-07:00'
        duration: 3662.357
        builtOn: chefdk-windows-2008r2-i386-builder-4b316d
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/94/
