---
version: 0.13.23
result: SUCCESS
timestamp: '2016-04-21T18:33:24-07:00'
duration: 16840.608
git_commit: bdb57ce9c5d8826d4ca6c1f72c307ddc612800c7
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-21T18:33:24-07:00'
    duration: 2.468
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/41/
    parameters:
      GIT_REF: v0.13.23
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-04-21T18:33:34-07:00'
    duration: 10495.38
    url: http://manhattan.ci.chef.co/job/chefdk-build/312/
    runs:
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-21T18:33:34-07:00'
        duration: 1201.129
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/312/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-21T18:33:34-07:00'
        duration: 1483.973
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/312/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-21T18:33:34-07:00'
        duration: 1103.066
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/312/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-21T18:33:34-07:00'
        duration: 606.452
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/312/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-21T18:33:34-07:00'
        duration: 1151.139
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/312/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-21T18:33:34-07:00'
        duration: 1822.621
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/312/
        omnibus_timing: {}
  chefdk-test:
    result: SUCCESS
    timestamp: '2016-04-21T21:28:40-07:00'
    duration: 6330.402
    url: http://manhattan.ci.chef.co/job/chefdk-test/126/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 3624.601
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/126/
        omnibus_timing: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 1077.043
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/126/
        omnibus_timing: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 767.629
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/126/
        omnibus_timing: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 838.802
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/126/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 1624.4
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/126/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 646.055
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/126/
        omnibus_timing: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 497.843
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/126/
        omnibus_timing: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 421.295
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/126/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 495.754
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/126/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 695.541
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/126/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 934.836
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/126/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-21T21:28:40-07:00'
        duration: 523.891
        builtOn: chefdk-windows-2008r2-i386-tester-e50cbf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/126/
        omnibus_timing: {}
  chefdk-promote:
    result: SUCCESS
    timestamp: '2016-04-21T23:14:18-07:00'
    duration: 12.358
    url: http://manhattan.ci.chef.co/job/chefdk-promote/56/
    runs: {}
