---
version: 0.14.15
result: FAILURE
timestamp: '2016-05-10T08:06:00-07:00'
duration: 10090.244
git_commit: 0abe64153a9e614a520c1ab84999e80bd99005e9
stages:
  chefdk-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-10T08:06:00-07:00'
    duration: 3.599
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-release/56/
    parameters:
      GIT_REF: v0.14.15
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chefdk-build:
    result: SUCCESS
    timestamp: '2016-05-10T08:06:10-07:00'
    duration: 8486.546
    url: http://manhattan.ci.chef.co/job/chefdk-build/385/
    runs:
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-10T08:06:10-07:00'
        duration: 3702.32
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/385/
        omnibus_builders:
          config_guess: 0.0099
          libiconv: 53.6988
          liblzma: 56.9823
          libxml2: 77.6388
          libxslt: 33.7926
          libarchive: 69.4645
          m4: 62.9094
          autoconf: 9.0834
          automake: 10.1562
          libtool: 27.0471
          libsodium: 306.7494
          libzmq: 83.2008
          cacerts: 0.038
          xproto: 10.2014
          util-macros: 2.7852
          pkg-config-lite: 11.8176
          makedepend: 9.8528
          openssl: 102.2646
          libffi: 19.0356
          libyaml: 15.4326
          ruby: 183.7178
          rubygems: 36.7637
          bundler: 2.0018
          chef-dk-gem-dep-selector-libgecode: 43.4886
          chef-dk-gem-ffi-rzmq: 6.9905
          chef-dk-gem-libyajl2: 7.9686
          chef-dk-gem-ffi-yajl: 10.843
          chef-dk-gem-json: 10.5522
          chef-dk-gem-mini_portile2: 6.97
          chef-dk-gem-nokogiri: 16.7274
          chef-dk-gem-ffi: 12.8878
          chef-dk-gem-ruby-prof: 12.8748
          chef-dk-gem-dep_selector: 10.3178
          chef-dk-gem-nio4r: 9.4931
          chef-dk-gem-byebug: 8.177
          chef-dk-gem-yajl-ruby: 8.6228
          chef-dk-gem-hitimes: 8.5851
          chef-dk-gem-debug_inspector: 7.7641
          chef-dk-gem-binding_of_caller: 7.7126
          chef-dk-gem-cookstyle: 6.572
          chef-dk-gem-ruby-shadow: 11.2277
          chef-dk: 202.2857
          chef-dk-appbundle: 469.5734
          gem-permissions: 6.665
          chef-dk-remove-docs: 0.0803
          rubygems-customization: 0.1431
          shebang-cleanup: 0.0231
          version-manifest: 0.1818
          openssl-customization: 0.1769
          rust: 7.8014
          delivery-cli: 684.5474
          rust-uninstall: 1.8305
          curl: 97.3462
          ncurses: 77.5456
          libedit: 24.1472
          pcre: 24.6418
          expat: 13.8883
          git: 27.2537
          clean-static-libs: 0.7278
          chef-dk-complete: 0.0
          Health check: 52.7252
          Packaging: 363.5412
      el-6:
        result: SUCCESS
        timestamp: '2016-05-10T08:06:10-07:00'
        duration: 4657.183
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/385/
        omnibus_builders:
          config_guess: 0.0115
          libiconv: 71.0075
          liblzma: 70.5633
          libxml2: 96.5735
          libxslt: 42.7327
          libarchive: 97.0945
          m4: 81.2878
          autoconf: 10.3622
          automake: 12.5509
          libtool: 37.6954
          libsodium: 352.5805
          libzmq: 113.3161
          cacerts: 0.0531
          xproto: 12.9905
          util-macros: 3.1491
          pkg-config-lite: 14.8764
          makedepend: 12.9909
          openssl: 153.5845
          libffi: 25.3618
          libyaml: 22.9651
          ruby: 247.5924
          rubygems: 39.5927
          bundler: 2.2847
          chef-dk-gem-dep-selector-libgecode: 170.0015
          chef-dk-gem-ffi-rzmq: 8.6106
          chef-dk-gem-libyajl2: 10.0637
          chef-dk-gem-ffi-yajl: 13.3974
          chef-dk-gem-json: 11.4508
          chef-dk-gem-mini_portile2: 8.1498
          chef-dk-gem-nokogiri: 20.1934
          chef-dk-gem-ffi: 16.5046
          chef-dk-gem-ruby-prof: 16.173
          chef-dk-gem-dep_selector: 13.2225
          chef-dk-gem-nio4r: 11.962
          chef-dk-gem-byebug: 9.8825
          chef-dk-gem-yajl-ruby: 10.3485
          chef-dk-gem-hitimes: 10.3387
          chef-dk-gem-debug_inspector: 9.2489
          chef-dk-gem-binding_of_caller: 9.4975
          chef-dk-gem-cookstyle: 8.4968
          chef-dk-gem-ruby-shadow: 13.7477
          chef-dk: 229.89
          chef-dk-appbundle: 511.6069
          gem-permissions: 8.6658
          chef-dk-remove-docs: 0.2786
          rubygems-customization: 0.1984
          shebang-cleanup: 0.0242
          version-manifest: 0.2111
          openssl-customization: 0.1734
          rust: 23.4965
          delivery-cli: 720.9193
          rust-uninstall: 3.3189
          curl: 128.0039
          ncurses: 137.7056
          libedit: 30.7143
          pcre: 30.3328
          expat: 17.5509
          git: 46.3715
          clean-static-libs: 1.1616
          chef-dk-complete: 0.0
          Health check: 60.5687
          Packaging: 496.2714
      el-7:
        result: SUCCESS
        timestamp: '2016-05-10T08:06:10-07:00'
        duration: 2885.284
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/385/
        omnibus_builders:
          config_guess: 0.0195
          libiconv: 33.5036
          liblzma: 39.8177
          libxml2: 48.3839
          libxslt: 19.2633
          libarchive: 53.1094
          m4: 44.9809
          autoconf: 5.7954
          automake: 6.6035
          libtool: 15.8418
          libsodium: 177.9203
          libzmq: 53.3511
          cacerts: 0.0081
          xproto: 5.9188
          util-macros: 1.7108
          pkg-config-lite: 6.336
          makedepend: 5.5862
          openssl: 77.0001
          libffi: 10.086
          libyaml: 8.5423
          ruby: 128.9364
          rubygems: 28.4429
          bundler: 1.6446
          chef-dk-gem-dep-selector-libgecode: 45.3319
          chef-dk-gem-ffi-rzmq: 5.123
          chef-dk-gem-libyajl2: 5.7743
          chef-dk-gem-ffi-yajl: 7.1602
          chef-dk-gem-json: 6.2686
          chef-dk-gem-mini_portile2: 6.6109
          chef-dk-gem-nokogiri: 12.8018
          chef-dk-gem-ffi: 10.0787
          chef-dk-gem-ruby-prof: 9.5281
          chef-dk-gem-dep_selector: 7.2994
          chef-dk-gem-nio4r: 6.7664
          chef-dk-gem-byebug: 5.7968
          chef-dk-gem-yajl-ruby: 6.4744
          chef-dk-gem-hitimes: 6.1105
          chef-dk-gem-debug_inspector: 5.3051
          chef-dk-gem-binding_of_caller: 5.2589
          chef-dk-gem-cookstyle: 5.5228
          chef-dk-gem-ruby-shadow: 8.151
          chef-dk: 162.4971
          chef-dk-appbundle: 349.6717
          gem-permissions: 4.3
          chef-dk-remove-docs: 0.0983
          rubygems-customization: 0.09
          shebang-cleanup: 0.0067
          version-manifest: 0.0336
          openssl-customization: 0.0896
          rust: 9.4236
          delivery-cli: 593.6926
          rust-uninstall: 1.0883
          curl: 68.9832
          ncurses: 59.286
          libedit: 13.5575
          pcre: 13.649
          expat: 7.1422
          git: 20.8516
          clean-static-libs: 0.3442
          chef-dk-complete: 0.0
          Health check: 23.2888
          Packaging: 380.596
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-10T08:06:10-07:00'
        duration: 2062.39
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/385/
        omnibus_builders:
          config_guess: 0.0097
          libiconv: 40.376
          liblzma: 40.3221
          libxml2: 64.2658
          libxslt: 23.1499
          libarchive: 60.1278
          m4: 45.151
          autoconf: 6.159
          automake: 6.1966
          libtool: 15.3769
          libsodium: 94.6646
          libzmq: 61.6655
          cacerts: 0.0162
          xproto: 5.612
          util-macros: 2.0129
          pkg-config-lite: 8.5843
          makedepend: 6.2344
          openssl: 89.9052
          libffi: 12.94
          libyaml: 12.5703
          ruby: 121.3767
          rubygems: 20.9518
          bundler: 1.9296
          chef-dk-gem-dep-selector-libgecode: 278.429
          chef-dk-gem-ffi-rzmq: 3.3209
          chef-dk-gem-libyajl2: 4.1417
          chef-dk-gem-ffi-yajl: 4.4171
          chef-dk-gem-json: 4.0996
          chef-dk-gem-mini_portile2: 2.7387
          chef-dk-gem-nokogiri: 10.6422
          chef-dk-gem-ffi: 7.1683
          chef-dk-gem-ruby-prof: 5.0884
          chef-dk-gem-dep_selector: 6.1733
          chef-dk-gem-nio4r: 4.2692
          chef-dk-gem-byebug: 3.4807
          chef-dk-gem-yajl-ruby: 4.6642
          chef-dk-gem-hitimes: 3.4085
          chef-dk-gem-debug_inspector: 2.7755
          chef-dk-gem-binding_of_caller: 2.7443
          chef-dk-gem-cookstyle: 2.6927
          chef-dk-gem-ruby-shadow: 4.0423
          chef-dk: 126.2805
          chef-dk-appbundle: 190.521
          gem-permissions: 3.6305
          chef-dk-remove-docs: 0.0382
          rubygems-customization: 0.0761
          shebang-cleanup: 0.0354
          version-manifest: 0.0258
          openssl-customization: 0.0904
          rust: 4.0208
          delivery-cli: 99.934
          rust-uninstall: 1.0128
          curl: 49.3336
          ncurses: 68.2071
          libedit: 12.3547
          pcre: 24.2157
          expat: 8.5881
          git: 40.8207
          clean-static-libs: 0.4953
          chef-dk-complete: 0.0
          Health check: 0.9132
          Packaging: 35.6794
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-10T08:06:10-07:00'
        duration: 3316.388
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/385/
        omnibus_builders:
          config_guess: 0.0039
          libiconv: 33.9481
          liblzma: 41.7782
          libxml2: 56.9068
          libxslt: 20.1921
          libarchive: 54.1528
          m4: 43.9
          autoconf: 5.706
          automake: 6.8911
          libtool: 15.3644
          libsodium: 203.5186
          libzmq: 60.3717
          cacerts: 0.0215
          xproto: 6.0907
          util-macros: 1.7432
          pkg-config-lite: 7.2958
          makedepend: 5.8225
          openssl: 88.5319
          libffi: 10.817
          libyaml: 9.0979
          ruby: 148.1878
          rubygems: 35.6871
          bundler: 1.877
          chef-dk-gem-dep-selector-libgecode: 46.9434
          chef-dk-gem-ffi-rzmq: 6.7642
          chef-dk-gem-libyajl2: 7.2433
          chef-dk-gem-ffi-yajl: 8.8008
          chef-dk-gem-json: 12.1078
          chef-dk-gem-mini_portile2: 6.5442
          chef-dk-gem-nokogiri: 15.1069
          chef-dk-gem-ffi: 11.4785
          chef-dk-gem-ruby-prof: 11.7021
          chef-dk-gem-dep_selector: 8.9433
          chef-dk-gem-nio4r: 8.2162
          chef-dk-gem-byebug: 7.4777
          chef-dk-gem-yajl-ruby: 7.6687
          chef-dk-gem-hitimes: 7.6286
          chef-dk-gem-debug_inspector: 6.7746
          chef-dk-gem-binding_of_caller: 6.7615
          chef-dk-gem-cookstyle: 6.5144
          chef-dk-gem-ruby-shadow: 9.7809
          chef-dk: 197.0861
          chef-dk-appbundle: 442.7097
          gem-permissions: 5.904
          chef-dk-remove-docs: 0.0645
          rubygems-customization: 0.0937
          shebang-cleanup: 0.0073
          version-manifest: 0.0345
          openssl-customization: 0.1057
          rust: 3.356
          delivery-cli: 760.5916
          rust-uninstall: 1.0755
          curl: 68.0222
          ncurses: 57.1516
          libedit: 14.6914
          pcre: 14.8065
          expat: 7.1408
          git: 23.1388
          clean-static-libs: 0.3643
          chef-dk-complete: 0.0
          Health check: 26.8792
          Packaging: 391.7347
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-10T08:06:10-07:00'
        duration: 8481.213
        builtOn: chefdk-windows-2008r2-i386-builder-dcb6f4
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/385/
        omnibus_builders:
          config_guess: 0.125
          libiconv: 275.4691
          liblzma: 223.5313
          libxml2: 467.3439
          libxslt: 298.672
          libarchive: 436.1097
          libzmq4x-windows: 0.3438
          cacerts: 0.125
          openssl: 673.094
          libffi: 158.3594
          libyaml: 163.6406
          ruby: 1161.5161
          rubygems: 26.7656
          bundler: 3.375
          chef-dk-gem-dep-selector-libgecode: 843.5869
          chef-dk-gem-ffi-rzmq: 6.1411
          chef-dk-gem-libyajl2: 130.838
          chef-dk-gem-ffi-yajl: 230.7663
          chef-dk-gem-json: 228.0629
          chef-dk-gem-mini_portile2: 5.6254
          chef-dk-gem-nokogiri: 131.3527
          chef-dk-gem-ffi: 114.9292
          chef-dk-gem-ruby-prof: 104.3348
          chef-dk-gem-dep_selector: 100.272
          chef-dk-gem-nio4r: 91.4902
          chef-dk-gem-byebug: 83.7866
          chef-dk-gem-yajl-ruby: 83.2079
          chef-dk-gem-hitimes: 81.8328
          chef-dk-gem-debug_inspector: 80.7079
          chef-dk-gem-binding_of_caller: 79.1296
          chef-dk-gem-cookstyle: 6.2504
          chef-dk-gem-ruby-shadow: 0.0313
          chef-dk: 326.7684
          chef-dk-appbundle: 301.9218
          gem-permissions: 0.0
          chef-dk-env-customization: 0.1875
          chef-dk-powershell-scripts: 1.1563
          ruby-windows-devkit: 21.5949
          chef-dk-remove-docs: 2.4533
          rubygems-customization: 0.1406
          shebang-cleanup: 4.8909
          version-manifest: 0.0781
          openssl-customization: 0.4063
          git-windows: 34.8612
          clean-static-libs: 0.6563
          chef-dk-complete: 0.0
          Health check: 0.0469
          Packaging: 514.1013
  chefdk-test:
    result: FAILURE
    timestamp: '2016-05-10T10:27:47-07:00'
    duration: 1600.099
    url: http://manhattan.ci.chef.co/job/chefdk-test/160/
    runs:
      acceptance:
        result: FAILURE
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 826.201
        builtOn: chefdk-ubuntu-14.04-acceptance-6eb047
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/160/
      debian-6:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 1013.076
        builtOn: chefdk-debian-6-tester-31349b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-6,project=chefdk,role=tester/160/
        omnibus_builders: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 753.947
        builtOn: chefdk-debian-7-tester-6585d4
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-7,project=chefdk,role=tester/160/
        omnibus_builders: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 881.637
        builtOn: chefdk-debian-8-tester-b7ac3b
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=debian-8,project=chefdk,role=tester/160/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 1596.842
        builtOn: chefdk-rhel-6-tester-42bd5e
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-6,project=chefdk,role=tester/160/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 657.354
        builtOn: chefdk-rhel-7-tester-ce15ff
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/160/
        omnibus_builders: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 741.636
        builtOn: chefdk-mac_os_x-10.10-tester-f8e0cd
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.10,project=chefdk,role=tester/160/
        omnibus_builders: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 557.025
        builtOn: chefdk-mac_os_x-10.11-tester-fb35b7
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.11,project=chefdk,role=tester/160/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 752.529
        builtOn: chefdk-mac_os_x-10.9-tester-8a14ce
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=tester/160/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 756.581
        builtOn: chefdk-ubuntu-12.04-tester-d64e0a
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=tester/160/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 865.395
        builtOn: chefdk-ubuntu-14.04-tester-48c4bf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=x86_64,platform=ubuntu-14.04,project=chefdk,role=tester/160/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-05-10T10:27:47-07:00'
        duration: 739.15
        builtOn: chefdk-windows-2008r2-i386-tester-e50cbf
        url: http://manhattan.ci.chef.co/job/chefdk-test/architecture=i386,platform=windows-2008r2,project=chefdk,role=tester/160/
        omnibus_builders: {}
