---
result: FAILURE
timestamp: '2016-04-15T12:25:26-07:00'
duration: 13.359
triggeredBy: jkeiser
url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/163/
version: 
git_ref: jk/lock-deps
git_commit: 
failures: {}
stages:
  chefdk-trigger-ad_hoc:
    result: FAILURE
    timestamp: '2016-04-15T12:25:26-07:00'
    duration: 13.359
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/163/
    causes:
    - shortDescription: Started by user John Keiser
      userId: jkeiser
      userName: John Keiser
    parameters:
      GIT_REF: jk/lock-deps
      EXPIRE_CACHE: false
    runs: {}
