---
result: 
timestamp: '2016-05-24T13:36:32-07:00'
duration: 3.83
triggeredBy: chef-jenkins
url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/334/
version: 
git_ref: auto_dependency_bump_test
git_commit: d5cfb5c73882921a4f3c23b1d771446097406d86
failures:
  chefdk-build omnibus Licensing: mac_os_x
stages:
  chefdk-build:
    result: 
    failures:
      omnibus Licensing: mac_os_x
    timestamp: '2016-05-24T13:36:42-07:00'
    duration: 0.0
    url: http://manhattan.ci.chef.co/job/chefdk-build/480/
    parameters:
      GIT_REF: auto_dependency_bump_test
      APPEND_TIMESTAMP: true
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: false
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: d5cfb5c73882921a4f3c23b1d771446097406d86
      PROJECT: chefdk
      PROMOTE: 'false'
      PIPELINE_TRIGGER_BUILD_NUMBER: '334'
      ADHOC_BUILD: 'true'
      GIT_BRANCH: origin/auto_dependency_bump_test
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-ad_hoc
    runs:
      mac_os_x-10.9:
        result: FAILURE
        timestamp: '2016-05-24T13:36:42-07:00'
        duration: 467.41
        builtOn: chefdk-mac_os_x-10.9-builder-d736d1
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=mac_os_x-10.9,project=chefdk,role=builder/480/
        failureCause:
          cause: omnibus
          detailedCause: omnibus Licensing
          jenkinsBuildStep: Invoke XShell command
          lastOmnibusLine: "[Licensing] W | 2016-05-24T13:44:15-07:00 | Software 'chef-dk-appbundle'
            does not contain licensing information."
          lastOmnibusStep: Licensing
          suspiciousBlocks:
            11243: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:40:49-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:40:49-07:00 | $ /opt/chefdk/embedded/bin/bundle lock
                                        D | 2016-05-24T13:40:49-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:40:49-07:00 | Replaced Gemfile dependency berkshelf (["4.3.3", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:40:49-07:00 | Replaced Gemfile dependency rake (["~> 10.1", {:type=>:development}]) with (["11.1.2", {}])
            11275: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:41:01-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:41:01-07:00 | $ /opt/chefdk/embedded/bin/bundle check
                                        D | 2016-05-24T13:41:01-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:41:01-07:00 | Replaced Gemfile dependency berkshelf (["4.3.3", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:41:01-07:00 | Replaced Gemfile dependency rake (["~> 10.1", {:type=>:development}]) with (["11.1.2", {}])
            11330: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:41:08-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:41:08-07:00 | $ /opt/chefdk/embedded/bin/bundle lock
                                        D | 2016-05-24T13:41:08-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:41:08-07:00 | Replaced Gemfile dependency chef-vault (["2.9.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:41:08-07:00 | Replaced Gemfile dependency rake (["~> 10.4", {:type=>:development}]) with (["11.1.2", {}])
            11361: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:41:18-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:41:18-07:00 | $ /opt/chefdk/embedded/bin/bundle check
                                        D | 2016-05-24T13:41:18-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:41:18-07:00 | Replaced Gemfile dependency chef-vault (["2.9.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:41:18-07:00 | Replaced Gemfile dependency rake (["~> 10.4", {:type=>:development}]) with (["11.1.2", {}])
            11661: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:06-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:06-07:00 | $ /opt/chefdk/embedded/bin/bundle lock
                                        D | 2016-05-24T13:42:06-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:42:06-07:00 | Replaced Gemfile dependency test-kitchen (["1.8.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:42:06-07:00 | Replaced Gemfile dependency rake (["~> 10.0", {:type=>:development}]) with (["11.1.2", {}])
            11692: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:15-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:15-07:00 | $ /opt/chefdk/embedded/bin/bundle check
                                        D | 2016-05-24T13:42:15-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:42:15-07:00 | Replaced Gemfile dependency test-kitchen (["1.8.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:42:15-07:00 | Replaced Gemfile dependency rake (["~> 10.0", {:type=>:development}]) with (["11.1.2", {}])
            11830: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:34-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:34-07:00 | $ /opt/chefdk/embedded/bin/bundle lock
                                        D | 2016-05-24T13:42:34-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:42:34-07:00 | Replaced Gemfile dependency rake (["~> 10.0", {:type=>:development}]) with (["11.1.2", {}])
                                        D | 2016-05-24T13:42:38-07:00 | Fetching gem metadata from https://rubygems.org/
            11859: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:42-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:42-07:00 | $ /opt/chefdk/embedded/bin/bundle check
                                        D | 2016-05-24T13:42:42-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:42:42-07:00 | Replaced Gemfile dependency rake (["~> 10.0", {:type=>:development}]) with (["11.1.2", {}])
                                        D | 2016-05-24T13:42:43-07:00 | Resolving dependencies.....
            11912: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:46-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:46-07:00 | $ /opt/chefdk/embedded/bin/bundle lock
                                        D | 2016-05-24T13:42:47-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:42:47-07:00 | Replaced Gemfile dependency fauxhai (["3.4.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:42:50-07:00 | Fetching gem metadata from https://rubygems.org/
            11941: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:54-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:42:54-07:00 | $ /opt/chefdk/embedded/bin/bundle check
                                        D | 2016-05-24T13:42:54-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:42:54-07:00 | Replaced Gemfile dependency fauxhai (["3.4.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:42:55-07:00 | Resolving dependencies.....
            12030: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:09-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:09-07:00 | $ /opt/chefdk/embedded/bin/bundle lock
                                        D | 2016-05-24T13:43:09-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:43:09-07:00 | Replaced Gemfile dependency kitchen-vagrant (["0.20.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:43:13-07:00 | Fetching gem metadata from https://rubygems.org/
            12059: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:18-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:18-07:00 | $ /opt/chefdk/embedded/bin/bundle check
                                        D | 2016-05-24T13:43:18-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:43:18-07:00 | Replaced Gemfile dependency kitchen-vagrant (["0.20.0", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:43:19-07:00 | Resolving dependencies......
            12088: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:21-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:21-07:00 | $ /opt/chefdk/embedded/bin/bundle lock
                                        D | 2016-05-24T13:43:22-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:43:22-07:00 | Replaced Gemfile dependency knife-spork (["1.6.1", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:43:26-07:00 | Fetching gem metadata from https://rubygems.org/
            12117: |
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:30-07:00 |   PKG_CONFIG_PATH="/opt/chefdk/embedded/lib/pkgconfig"
              [Builder: chef-dk-appbundle] I | 2016-05-24T13:43:30-07:00 | $ /opt/chefdk/embedded/bin/bundle check
                                        D | 2016-05-24T13:43:31-07:00 | fatal: Not a git repository (or any of the parent directories): .git
                                        D | 2016-05-24T13:43:31-07:00 | Replaced Gemfile dependency knife-spork (["1.6.1", {}]) with ([{:path=>".", :glob=>nil, :platforms=>[:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :rbx]}])
                                        D | 2016-05-24T13:43:32-07:00 | Resolving dependencies.....
            12310: |2
                  Software 'chef-dk-appbundle' does not contain licensing information.

              /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-a36e70caedce/lib/omnibus/licensing.rb:72:in `create!'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-a36e70caedce/lib/omnibus/licensing.rb:32:in `create!'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-a36e70caedce/lib/omnibus/project.rb:1081:in `build'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-a36e70caedce/lib/omnibus/cli.rb:84:in `build'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-a36e70caedce/lib/omnibus/cli/base.rb:33:in `dispatch'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-a36e70caedce/lib/omnibus/cli.rb:42:in `execute!'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bundler/gems/omnibus-a36e70caedce/bin/omnibus:16:in `<top (required)>'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bin/omnibus:22:in `load'
                /Users/jenkins/workspace/chefdk-build/architecture/x86_64/platform/mac_os_x-10.9/project/chefdk/role/builder/omnibus/vendor/bundle/ruby/2.1.0/bin/omnibus:22:in `<main>'
              Build step 'Invoke XShell command' marked build as failure
              Archiving artifacts
              Recording fingerprints
        omnibusTiming:
          chef-dk-complete: 0.0
          clean-static-libs: 0.6598
          openssl-customization: 0.0781
          version-manifest: 0.0224
          shebang-cleanup: 0.0324
          rubygems-customization: 0.0747
          chef-dk-remove-docs: 0.0912
          gem-permissions: 3.7891
          chef-dk-appbundle: 180.1952
          chef-dk: 120.4847
      debian-6:
        result: 
        timestamp: '2016-05-24T13:36:42-07:00'
        duration: 0.0
        builtOn: chefdk-debian-6-builder-2ccc58
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=debian-6,project=chefdk,role=builder/480/
        omnibusTiming: {}
      el-6:
        result: 
        timestamp: '2016-05-24T13:36:42-07:00'
        duration: 0.0
        builtOn: chefdk-rhel-6-builder-02167c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-6,project=chefdk,role=builder/480/
        omnibusTiming: {}
      el-7:
        result: 
        timestamp: '2016-05-24T13:36:42-07:00'
        duration: 0.0
        builtOn: chefdk-rhel-7-builder-b67c93
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=el-7,project=chefdk,role=builder/480/
        omnibusTiming: {}
      ubuntu-12.04:
        result: 
        timestamp: '2016-05-24T13:36:42-07:00'
        duration: 0.0
        builtOn: chefdk-ubuntu-12.04-builder-efc2e0
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=x86_64,platform=ubuntu-12.04,project=chefdk,role=builder/480/
        omnibusTiming: {}
      windows-2008r2-i386:
        result: 
        timestamp: '2016-05-24T13:36:42-07:00'
        duration: 0.0
        builtOn: chefdk-windows-2008r2-i386-builder-53e13c
        url: http://manhattan.ci.chef.co/job/chefdk-build/architecture=i386,platform=windows-2008r2,project=chefdk,role=builder/480/
        omnibusTiming: {}
  chefdk-trigger-ad_hoc:
    result: SUCCESS
    timestamp: '2016-05-24T13:36:32-07:00'
    duration: 3.83
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/334/
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    parameters:
      GIT_REF: auto_dependency_bump_test
      EXPIRE_CACHE: false
    runs: {}
