---
result: FAILURE
timestamp: '2016-03-22T15:15:03-07:00'
duration: 2.833
version: 
git_commit: 
stages:
  chefdk-trigger-ad_hoc:
    result: FAILURE
    timestamp: '2016-03-22T15:15:03-07:00'
    duration: 2.833
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/58/
    causes:
    - shortDescription: Started by user Dan DeLeo
      userId: danielsdeleo
      userName: Dan DeLeo
    parameters:
      GIT_REF: 'fix-acceptance-vm-leaks '
      EXPIRE_CACHE: false
    runs: {}
