---
result: FAILURE
timestamp: '2016-03-22T15:13:18-07:00'
duration: 3.937
version: 
git_commit: 
stages:
  chefdk-trigger-ad_hoc:
    result: FAILURE
    timestamp: '2016-03-22T15:13:18-07:00'
    duration: 3.937
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/57/
    causes:
    - shortDescription: Started by user Dan DeLeo
      userId: danielsdeleo
      userName: Dan DeLeo
    parameters:
      GIT_REF: 'fix-acceptance-vm-leaks '
      EXPIRE_CACHE: false
    retryOf:
    - 56
    runs: {}
