---
result: ABORTED
timestamp: '2016-04-05T14:36:43-07:00'
duration: 23.592
version: 
git_commit: eba9a0b13452d0ca796531a2329b4576cb56c03e
stages:
  chefdk-build:
    result: ABORTED
    timestamp: '2016-04-05T14:37:07-07:00'
    duration: 6.959
    url: http://manhattan.ci.chef.co/job/chefdk-build/194/
    causes:
    - shortDescription: Aborted by jkeiser
    parameters:
      GIT_REF: jk/chef-dk-gemset
      APPEND_TIMESTAMP: true
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: true
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chefdk
      GIT_COMMIT: eba9a0b13452d0ca796531a2329b4576cb56c03e
      PROJECT: chefdk
      PROMOTE: 'false'
      PIPELINE_TRIGGER_BUILD_NUMBER: '112'
      ADHOC_BUILD: 'true'
      GIT_BRANCH: origin/jk/chef-dk-gemset
      PIPELINE_TRIGGER_JOB_NAME: chefdk-trigger-ad_hoc
    runs: {}
  chefdk-trigger-ad_hoc:
    result: SUCCESS
    timestamp: '2016-04-05T14:36:43-07:00'
    duration: 16.633
    url: http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/112/
    causes:
    - shortDescription: Started by user John Keiser
      userId: jkeiser
      userName: John Keiser
    parameters:
      GIT_REF: jk/chef-dk-gemset
      EXPIRE_CACHE: true
    runs: {}
