---
version: 12.8.6
result: SUCCESS
timestamp: '2016-03-23T18:25:20-07:00'
duration: 54766.35
git_commit: d55259b34cbcc6b9b7697cdb38800aa3aeef6f96
stages:
  chef-trigger-release:
    result: SUCCESS
    timestamp: '2016-03-23T18:25:20-07:00'
    duration: 23.398
    url: http://manhattan.ci.chef.co/job/chef-trigger-release/11/
    parameters:
      GIT_REF: v12.8.6
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chef-build:
    result: SUCCESS
    timestamp: '2016-03-23T18:25:50-07:00'
    duration: 7734.396
    url: http://manhattan.ci.chef.co/job/chef-build/280/
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 1295.69
        builtOn: chef-aix-6-powerpc-builder-bf6c4a
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/280/
        omnibus_builders: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 593.962
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/280/
        omnibus_builders: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 443.312
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/280/
        omnibus_builders: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 727.326
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/280/
        omnibus_builders: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 540.1
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/280/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 748.039
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/280/
        omnibus_builders: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 540.892
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/280/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 476.462
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/280/
        omnibus_builders: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 513.891
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/280/
        omnibus_builders: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 366.905
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/280/
        omnibus_builders: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 572.596
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/280/
        omnibus_builders: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 401.719
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/280/
        omnibus_builders: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 545.32
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/280/
        omnibus_builders: {}
      mac_os_x-10.8:
        result: SUCCESS
        timestamp: '2016-02-24T20:00:42-08:00'
        duration: 489.196
        delay: -2409908.0
        builtOn: chef-mac_os_x-10.8-builder-6c4b72
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.8,project=chef,role=builder/143/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 422.557
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/280/
        omnibus_builders: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 594.286
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/280/
        omnibus_builders: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 553.792
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/280/
        omnibus_builders: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 4506.305
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/280/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 561.81
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/280/
        omnibus_builders: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 430.141
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/280/
        omnibus_builders: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 7706.378
        builtOn: chef-windows-2008r2-builder-220d66
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/280/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-03-23T18:25:50-07:00'
        duration: 6314.477
        builtOn: chef-windows-2008r2-i386-builder-7b1255
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/280/
        omnibus_builders: {}
  chef-test:
    result: SUCCESS
    timestamp: '2016-03-23T20:34:53-07:00'
    duration: 46979.113
    url: http://manhattan.ci.chef.co/job/chef-test/177/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 5266.07
        builtOn: chef-ubuntu-14.04-acceptance-469d58
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=acceptance,project=chef,role=tester/177/
        omnibus_builders: {}
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1565.337
        builtOn: chef-aix-6-powerpc-tester-c5f3a4
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-6.1,project=chef,role=tester/177/
        omnibus_builders: {}
      aix-7.1-powerpc:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1517.276
        builtOn: chef-aix-7-powerpc-tester-58983e
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-7.1,project=chef,role=tester/177/
        omnibus_builders: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1176.096
        builtOn: chef-debian-6-tester-61fa80
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-6,project=chef,role=tester/177/
        omnibus_builders: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 623.703
        builtOn: chef-debian-6-i386-tester-52378a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-6,project=chef,role=tester/177/
        omnibus_builders: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 830.258
        builtOn: chef-debian-7-tester-c208ec
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-7,project=chef,role=tester/177/
        omnibus_builders: {}
      debian-7-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 641.728
        builtOn: chef-debian-7-i386-tester-d74358
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-7,project=chef,role=tester/177/
        omnibus_builders: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 878.061
        builtOn: chef-debian-8-tester-26c16f
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-8,project=chef,role=tester/177/
        omnibus_builders: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1973.538
        builtOn: chef-rhel-5-tester-3d4799
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-5,project=chef,role=tester/177/
        omnibus_builders: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1358.292
        builtOn: chef-rhel-5-i386-tester-6b2182
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-5,project=chef,role=tester/177/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 2907.999
        builtOn: chef-rhel-6-tester-ad4e43
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-6,project=chef,role=tester/177/
        omnibus_builders: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1833.644
        builtOn: chef-rhel-6-i386-tester-a310b5
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-6,project=chef,role=tester/177/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 756.899
        builtOn: chef-rhel-7-tester-ef80de
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-7,project=chef,role=tester/177/
        omnibus_builders: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 883.396
        builtOn: chef-freebsd-10-tester-0e44ab
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-10,project=chef,role=tester/177/
        omnibus_builders: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 547.491
        builtOn: chef-freebsd-10-i386-tester-f27513
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-10,project=chef,role=tester/177/
        omnibus_builders: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 988.404
        builtOn: chef-freebsd-9-tester-fe6076
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-9,project=chef,role=tester/177/
        omnibus_builders: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 623.314
        builtOn: chef-freebsd-9-i386-tester-f811ce
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-9,project=chef,role=tester/177/
        omnibus_builders: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 643.96
        builtOn: chef-ios_xr-6-tester-2f039d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ios_xr-6,project=chef,role=tester/177/
        omnibus_builders: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 717.55
        builtOn: chef-mac_os_x-10.10-tester-f93984
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.10,project=chef,role=tester/177/
        omnibus_builders: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 602.384
        builtOn: chef-mac_os_x-10.11-tester-bb5587
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.11,project=chef,role=tester/177/
        omnibus_builders: {}
      mac_os_x-10.8:
        result: SUCCESS
        timestamp: '2016-02-24T20:31:08-08:00'
        duration: 667.864
        delay: -2415825.0
        builtOn: chef-mac_os_x-10.8-tester-eb8870
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.8,project=chef,role=tester/97/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 693.693
        builtOn: chef-mac_os_x-10.9-tester-61d54d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=tester/177/
        omnibus_builders: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 756.999
        builtOn: chef-nexus-7-tester-fd11dc
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=nexus-7,project=chef,role=tester/177/
        omnibus_builders: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 426.542
        builtOn: chef-solaris-10-i86pc-tester-df8804
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-10,project=chef,role=tester/177/
        omnibus_builders: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 4874.59
        builtOn: chef-solaris-10-sun4v-tester-089b13
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-10,project=chef,role=tester/177/
        omnibus_builders: {}
      solaris-11-i86pc:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 697.063
        builtOn: chef-solaris-11-i86pc-tester-d2a1f7
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-11,project=chef,role=tester/177/
        omnibus_builders: {}
      solaris-11-sun4v:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 4751.345
        builtOn: chef-solaris-11-sun4v-tester-988f0a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-11,project=chef,role=tester/177/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 939.104
        builtOn: chef-ubuntu-10.04-tester-122b8b
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=tester/177/
        omnibus_builders: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 553.379
        builtOn: chef-ubuntu-10.04-i386-tester-eebef0
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-10.04,project=chef,role=tester/177/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1029.194
        builtOn: chef-ubuntu-12.04-tester-d79170
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-12.04,project=chef,role=tester/177/
        omnibus_builders: {}
      ubuntu-12.04-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 636.662
        builtOn: chef-ubuntu-12.04-i386-tester-a0fc88
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-12.04,project=chef,role=tester/177/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 824.53
        builtOn: chef-ubuntu-14.04-tester-eb4a2d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-14.04,project=chef,role=tester/177/
        omnibus_builders: {}
      ubuntu-14.04-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 635.186
        builtOn: chef-ubuntu-14.04-i386-tester-dd49dd
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-14.04,project=chef,role=tester/177/
        omnibus_builders: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1837.396
        builtOn: chef-windows-2008r2-tester-b8462c
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2008r2,project=chef,role=tester/177/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 2640.646
        builtOn: chef-windows-2008r2-i386-tester-7a4e69
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=windows-2008r2,project=chef,role=tester/177/
        omnibus_builders: {}
      windows-2012:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 1985.113
        builtOn: chef-windows-2012-tester-f1420a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012,project=chef,role=tester/177/
        omnibus_builders: {}
      windows-2012r2:
        result: SUCCESS
        timestamp: '2016-03-23T20:34:53-07:00'
        duration: 2092.18
        builtOn: chef-windows-2012r2-tester-a5e480
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012r2,project=chef,role=tester/177/
        omnibus_builders: {}
  chef-promote:
    result: SUCCESS
    timestamp: '2016-03-24T09:38:01-07:00'
    duration: 29.443
    url: http://manhattan.ci.chef.co/job/chef-promote/61/
    runs: {}
