---
result: FAILURE
timestamp: '2016-05-03T09:03:41-07:00'
duration: 1996.946
version: 
git_commit: 9b9f71d8a2e3ef16d00e4394dc914f24316d183f
stages:
  chef-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-03T09:03:41-07:00'
    duration: 47.857
    url: http://manhattan.ci.chef.co/job/chef-trigger-release/85/
    parameters:
      GIT_REF: v12.10.29
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chef-build:
    result: FAILURE
    failures: debian,el-5,el-5-i386,freebsd-9,freebsd-9-i386,ubuntu,windows
    timestamp: '2016-05-03T09:04:36-07:00'
    duration: 1949.089
    url: http://manhattan.ci.chef.co/job/chef-build/504/
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 1068.414
        builtOn: chef-aix-6-powerpc-builder-88f619
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/504/
        omnibus_timing: {}
      debian-6:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 620.038
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/504/
      debian-6-i386:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 616.073
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/504/
      el-5:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 567.985
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/504/
      el-5-i386:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 525.27
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/504/
      el-6:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 821.16
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/504/
        omnibus_timing: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 692.144
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/504/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 724.267
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/504/
        omnibus_timing: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 765.343
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/504/
        omnibus_timing: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 571.959
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/504/
        omnibus_timing: {}
      freebsd-9:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 668.565
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/504/
      freebsd-9-i386:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 532.547
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/504/
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 321.783
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/504/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 275.844
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/504/
        omnibus_timing: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 365.616
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/504/
        omnibus_timing: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 464.442
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/504/
        omnibus_timing: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 1909.476
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/504/
        omnibus_timing: {}
      ubuntu-10.04:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 594.455
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/504/
      ubuntu-10.04-i386:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 452.594
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/504/
      windows-2008r2:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 720.084
        builtOn: chef-windows-2008r2-builder-8b402f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/504/
      windows-2008r2-i386:
        result: FAILURE
        timestamp: '2016-05-03T09:04:36-07:00'
        duration: 541.286
        builtOn: chef-windows-2008r2-i386-builder-66fdc7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/504/
