---
result: FAILURE
timestamp: '2016-05-04T07:42:38-07:00'
duration: 1988.262
version: 
git_commit: db27c5675c8367fdf5615e507ddd35fac8420710
missingFromJenkins: true
stages:
  chef-trigger-release:
    result: SUCCESS
    timestamp: '2016-05-04T07:42:38-07:00'
    duration: 24.681
    url: http://manhattan.ci.chef.co/job/chef-trigger-release/88/
    parameters:
      GIT_REF: v12.10.32
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chef-build:
    result: FAILURE
    failures:
      unknown: debian,el-5,el-5-i386,freebsd-9,freebsd-9-i386,ubuntu,windows
    timestamp: '2016-05-04T07:43:13-07:00'
    duration: 1963.581
    url: http://manhattan.ci.chef.co/job/chef-build/514/
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 1054.187
        builtOn: chef-aix-6-powerpc-builder-88f619
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/514/
      debian-6:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 343.286
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/514/
      debian-6-i386:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 281.504
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/514/
      el-5:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 340.925
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/514/
      el-5-i386:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 300.777
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/514/
      el-6:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 561.84
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/514/
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 408.03
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/514/
      el-7:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 420.678
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/514/
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 510.065
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/514/
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 360.804
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/514/
      freebsd-9:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 433.964
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/514/
      freebsd-9-i386:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 328.506
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/514/
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 314.2
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/514/
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 234.615
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/514/
      nexus-7:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 380.808
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/514/
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 449.38
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/514/
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 1934.258
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/514/
      ubuntu-10.04:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 324.724
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/514/
      ubuntu-10.04-i386:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 274.075
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/514/
      windows-2008r2:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 719.989
        builtOn: chef-windows-2008r2-builder-8b402f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/514/
      windows-2008r2-i386:
        result: FAILURE
        timestamp: '2016-05-04T07:43:13-07:00'
        duration: 569.825
        builtOn: chef-windows-2008r2-i386-builder-66fdc7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/514/
