---
version: 12.9.29
result: SUCCESS
timestamp: '2016-04-05T14:13:31-07:00'
duration: 7323.553
git_commit: 5d1a312bbbfc651d4ee4dce1e8fe923002c8aaea
stages:
  chef-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-05T14:13:31-07:00'
    duration: 25.53
    url: http://manhattan.ci.chef.co/job/chef-trigger-release/44/
    parameters:
      GIT_REF: v12.9.29
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chef-build:
    result: SUCCESS
    timestamp: '2016-04-05T14:14:06-07:00'
    duration: 1903.087
    url: http://manhattan.ci.chef.co/job/chef-build/343/
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 1298.009
        builtOn: chef-aix-6-powerpc-builder-bf6c4a
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/343/
        omnibus_builders: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 815.461
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/343/
        omnibus_builders: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 661.634
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/343/
        omnibus_builders: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 796.175
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/343/
        omnibus_builders: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 672.799
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/343/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 840.776
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/343/
        omnibus_builders: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 681.85
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/343/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 765.078
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/343/
        omnibus_builders: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 742.834
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/343/
        omnibus_builders: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 704.241
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/343/
        omnibus_builders: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 775.758
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/343/
        omnibus_builders: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 692.429
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/343/
        omnibus_builders: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 711.376
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/343/
        omnibus_builders: {}
      mac_os_x-10.8:
        result: SUCCESS
        timestamp: '2016-02-24T20:00:42-08:00'
        duration: 489.196
        delay: -3518004.0
        builtOn: chef-mac_os_x-10.8-builder-6c4b72
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.8,project=chef,role=builder/143/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 548.59
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/343/
        omnibus_builders: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 740.135
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/343/
        omnibus_builders: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 710.821
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/343/
        omnibus_builders: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 1869.758
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/343/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 743.535
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/343/
        omnibus_builders: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 589.678
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/343/
        omnibus_builders: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 1673.308
        builtOn: chef-windows-2008r2-builder-8b402f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/343/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:14:06-07:00'
        duration: 1278.515
        builtOn: chef-windows-2008r2-i386-builder-66fdc7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/343/
        omnibus_builders: {}
  chef-test:
    result: SUCCESS
    timestamp: '2016-04-05T14:45:57-07:00'
    duration: 5365.522
    url: http://manhattan.ci.chef.co/job/chef-test/215/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 3188.591
        builtOn: chef-ubuntu-14.04-acceptance-469d58
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=acceptance,project=chef,role=tester/215/
        omnibus_builders: {}
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 2314.746
        builtOn: chef-aix-6-powerpc-tester-c5f3a4
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-6.1,project=chef,role=tester/215/
        omnibus_builders: {}
      aix-7.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 2174.706
        builtOn: chef-aix-7-powerpc-tester-58983e
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-7.1,project=chef,role=tester/215/
        omnibus_builders: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 1167.725
        builtOn: chef-debian-6-tester-61fa80
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-6,project=chef,role=tester/215/
        omnibus_builders: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 638.607
        builtOn: chef-debian-6-i386-tester-52378a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-6,project=chef,role=tester/215/
        omnibus_builders: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 827.788
        builtOn: chef-debian-7-tester-c208ec
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-7,project=chef,role=tester/215/
        omnibus_builders: {}
      debian-7-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 658.408
        builtOn: chef-debian-7-i386-tester-d74358
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-7,project=chef,role=tester/215/
        omnibus_builders: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 873.368
        builtOn: chef-debian-8-tester-26c16f
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-8,project=chef,role=tester/215/
        omnibus_builders: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 1970.254
        builtOn: chef-rhel-5-tester-3d4799
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-5,project=chef,role=tester/215/
        omnibus_builders: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 1377.116
        builtOn: chef-rhel-5-i386-tester-6b2182
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-5,project=chef,role=tester/215/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 3033.865
        builtOn: chef-rhel-6-tester-ad4e43
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-6,project=chef,role=tester/215/
        omnibus_builders: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 1794.908
        builtOn: chef-rhel-6-i386-tester-a310b5
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-6,project=chef,role=tester/215/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 764.935
        builtOn: chef-rhel-7-tester-ef80de
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-7,project=chef,role=tester/215/
        omnibus_builders: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 874.908
        builtOn: chef-freebsd-10-tester-0e44ab
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-10,project=chef,role=tester/215/
        omnibus_builders: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 542.978
        builtOn: chef-freebsd-10-i386-tester-f27513
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-10,project=chef,role=tester/215/
        omnibus_builders: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 987.621
        builtOn: chef-freebsd-9-tester-fe6076
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-9,project=chef,role=tester/215/
        omnibus_builders: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 630.632
        builtOn: chef-freebsd-9-i386-tester-f811ce
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-9,project=chef,role=tester/215/
        omnibus_builders: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 644.009
        builtOn: chef-ios_xr-6-tester-2f039d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ios_xr-6,project=chef,role=tester/215/
        omnibus_builders: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 726.343
        builtOn: chef-mac_os_x-10.10-tester-f93984
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.10,project=chef,role=tester/215/
        omnibus_builders: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 644.639
        builtOn: chef-mac_os_x-10.11-tester-bb5587
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.11,project=chef,role=tester/215/
        omnibus_builders: {}
      mac_os_x-10.8:
        result: SUCCESS
        timestamp: '2016-02-24T20:31:08-08:00'
        duration: 667.864
        delay: -3518089.0
        builtOn: chef-mac_os_x-10.8-tester-eb8870
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.8,project=chef,role=tester/97/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 730.831
        builtOn: chef-mac_os_x-10.9-tester-61d54d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=tester/215/
        omnibus_builders: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 583.774
        builtOn: chef-nexus-7-tester-fd11dc
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=nexus-7,project=chef,role=tester/215/
        omnibus_builders: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 964.891
        builtOn: chef-solaris-10-i86pc-tester-df8804
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-10,project=chef,role=tester/215/
        omnibus_builders: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 5167.428
        builtOn: chef-solaris-10-sun4v-tester-089b13
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-10,project=chef,role=tester/215/
        omnibus_builders: {}
      solaris-11-i86pc:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 962.782
        builtOn: chef-solaris-11-i86pc-tester-d2a1f7
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-11,project=chef,role=tester/215/
        omnibus_builders: {}
      solaris-11-sun4v:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 5363.967
        builtOn: chef-solaris-11-sun4v-tester-988f0a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-11,project=chef,role=tester/215/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 964.742
        builtOn: chef-ubuntu-10.04-tester-122b8b
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=tester/215/
        omnibus_builders: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 553.447
        builtOn: chef-ubuntu-10.04-i386-tester-eebef0
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-10.04,project=chef,role=tester/215/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 961.391
        builtOn: chef-ubuntu-12.04-tester-d79170
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-12.04,project=chef,role=tester/215/
        omnibus_builders: {}
      ubuntu-12.04-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 635.33
        builtOn: chef-ubuntu-12.04-i386-tester-a0fc88
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-12.04,project=chef,role=tester/215/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 838.321
        builtOn: chef-ubuntu-14.04-tester-eb4a2d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-14.04,project=chef,role=tester/215/
        omnibus_builders: {}
      ubuntu-14.04-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 635.23
        builtOn: chef-ubuntu-14.04-i386-tester-dd49dd
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-14.04,project=chef,role=tester/215/
        omnibus_builders: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 2442.879
        builtOn: chef-windows-2008r2-tester-b8462c
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2008r2,project=chef,role=tester/215/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 2697.071
        builtOn: chef-windows-2008r2-i386-tester-7a4e69
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=windows-2008r2,project=chef,role=tester/215/
        omnibus_builders: {}
      windows-2012:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 2476.254
        builtOn: chef-windows-2012-tester-f1420a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012,project=chef,role=tester/215/
        omnibus_builders: {}
      windows-2012r2:
        result: SUCCESS
        timestamp: '2016-04-05T14:45:57-07:00'
        duration: 2686.277
        builtOn: chef-windows-2012r2-tester-a5e480
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012r2,project=chef,role=tester/215/
        omnibus_builders: {}
  chef-promote:
    result: SUCCESS
    timestamp: '2016-04-05T16:15:30-07:00'
    duration: 29.414
    url: http://manhattan.ci.chef.co/job/chef-promote/67/
    runs: {}
