---
version: 12.8.0
result: SUCCESS
timestamp: '2016-03-02T17:16:50-08:00'
duration: 12846.306
git_commit: a4d98365c1d68d7a24fba62783538951d2bbd2e0
stages:
  chef-trigger-release:
    result: SUCCESS
    timestamp: '2016-03-02T17:16:50-08:00'
    duration: 21.894
    url: http://manhattan.ci.chef.co/job/chef-trigger-release/5/
    parameters:
      GIT_REF: master
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Matt Wrock
      userId: mwrock
      userName: Matt Wrock
    runs: {}
  chef-build:
    result: SUCCESS
    timestamp: '2016-03-02T17:17:19-08:00'
    duration: 7647.896
    url: http://manhattan.ci.chef.co/job/chef-build/187/
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1902.161
        builtOn: chef-aix-6-powerpc-builder-bf6c4a
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/187/
        omnibus_builders: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1354.404
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/187/
        omnibus_builders: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 896.234
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/187/
        omnibus_builders: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1393.84
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/187/
        omnibus_builders: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1050.255
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/187/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1575.755
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/187/
        omnibus_builders: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1135.603
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/187/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 993.522
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/187/
        omnibus_builders: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1677.496
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/187/
        omnibus_builders: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1012.535
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/187/
        omnibus_builders: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1196.448
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/187/
        omnibus_builders: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 746.649
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/187/
        omnibus_builders: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1294.384
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/187/
        omnibus_builders: {}
      mac_os_x-10.8:
        result: SUCCESS
        timestamp: '2016-02-24T20:00:42-08:00'
        duration: 489.196
        delay: -594997.0
        builtOn: chef-mac_os_x-10.8-builder-6c4b72
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.8,project=chef,role=builder/143/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 876.785
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/187/
        omnibus_builders: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1256.316
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/187/
        omnibus_builders: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1104.618
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/187/
        omnibus_builders: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 4493.662
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/187/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 1280.429
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/187/
        omnibus_builders: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 861.911
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/187/
        omnibus_builders: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 7457.668
        builtOn: chef-windows-2008r2-builder-8b402f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/187/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-03-02T17:17:19-08:00'
        duration: 7285.271
        builtOn: chef-windows-2008r2-i386-builder-7b1255
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/187/
        omnibus_builders: {}
  chef-test:
    result: SUCCESS
    timestamp: '2016-03-02T19:24:56-08:00'
    duration: 5145.139
    url: http://manhattan.ci.chef.co/job/chef-test/118/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 3821.806
        builtOn: chef-ubuntu-14.04-acceptance-469d58
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=acceptance,project=chef,role=tester/118/
        omnibus_builders: {}
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 1743.804
        builtOn: chef-aix-6-powerpc-tester-c5f3a4
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-6.1,project=chef,role=tester/118/
        omnibus_builders: {}
      aix-7.1-powerpc:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 1665.208
        builtOn: chef-aix-7-powerpc-tester-58983e
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-7.1,project=chef,role=tester/118/
        omnibus_builders: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 1159.139
        builtOn: chef-debian-6-tester-61fa80
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-6,project=chef,role=tester/118/
        omnibus_builders: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 620.728
        builtOn: chef-debian-6-i386-tester-52378a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-6,project=chef,role=tester/118/
        omnibus_builders: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 837.515
        builtOn: chef-debian-7-tester-c208ec
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-7,project=chef,role=tester/118/
        omnibus_builders: {}
      debian-7-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 637.896
        builtOn: chef-debian-7-i386-tester-d74358
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-7,project=chef,role=tester/118/
        omnibus_builders: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 901.158
        builtOn: chef-debian-8-tester-26c16f
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-8,project=chef,role=tester/118/
        omnibus_builders: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 1950.742
        builtOn: chef-rhel-5-tester-3d4799
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-5,project=chef,role=tester/118/
        omnibus_builders: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 1365.568
        builtOn: chef-rhel-5-i386-tester-6b2182
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-5,project=chef,role=tester/118/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 2814.637
        builtOn: chef-rhel-6-tester-ad4e43
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-6,project=chef,role=tester/118/
        omnibus_builders: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 1763.697
        builtOn: chef-rhel-6-i386-tester-a310b5
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-6,project=chef,role=tester/118/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 756.526
        builtOn: chef-rhel-7-tester-ef80de
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-7,project=chef,role=tester/118/
        omnibus_builders: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 885.239
        builtOn: chef-freebsd-10-tester-0e44ab
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-10,project=chef,role=tester/118/
        omnibus_builders: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 552.94
        builtOn: chef-freebsd-10-i386-tester-f27513
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-10,project=chef,role=tester/118/
        omnibus_builders: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 976.383
        builtOn: chef-freebsd-9-tester-fe6076
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-9,project=chef,role=tester/118/
        omnibus_builders: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 600.241
        builtOn: chef-freebsd-9-i386-tester-f811ce
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-9,project=chef,role=tester/118/
        omnibus_builders: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 710.421
        builtOn: chef-ios_xr-6-tester-2f039d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ios_xr-6,project=chef,role=tester/118/
        omnibus_builders: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 775.12
        builtOn: chef-mac_os_x-10.10-tester-f93984
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.10,project=chef,role=tester/118/
        omnibus_builders: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 645.59
        builtOn: chef-mac_os_x-10.11-tester-bb5587
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.11,project=chef,role=tester/118/
        omnibus_builders: {}
      mac_os_x-10.8:
        result: SUCCESS
        timestamp: '2016-02-24T20:31:08-08:00'
        duration: 667.864
        delay: -600828.0
        builtOn: chef-mac_os_x-10.8-tester-eb8870
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.8,project=chef,role=tester/97/
        omnibus_builders: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 759.963
        builtOn: chef-mac_os_x-10.9-tester-61d54d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=tester/118/
        omnibus_builders: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 824.385
        builtOn: chef-nexus-7-tester-fd11dc
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=nexus-7,project=chef,role=tester/118/
        omnibus_builders: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 863.61
        builtOn: chef-solaris-10-i86pc-tester-df8804
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-10,project=chef,role=tester/118/
        omnibus_builders: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 5002.75
        builtOn: chef-solaris-10-sun4v-tester-089b13
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-10,project=chef,role=tester/118/
        omnibus_builders: {}
      solaris-11-i86pc:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 827.869
        builtOn: chef-solaris-11-i86pc-tester-d2a1f7
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-11,project=chef,role=tester/118/
        omnibus_builders: {}
      solaris-11-sun4v:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 5143.842
        builtOn: chef-solaris-11-sun4v-tester-988f0a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-11,project=chef,role=tester/118/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 957.303
        builtOn: chef-ubuntu-10.04-tester-122b8b
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=tester/118/
        omnibus_builders: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 542.772
        builtOn: chef-ubuntu-10.04-i386-tester-eebef0
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-10.04,project=chef,role=tester/118/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 969.704
        builtOn: chef-ubuntu-12.04-tester-d79170
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-12.04,project=chef,role=tester/118/
        omnibus_builders: {}
      ubuntu-12.04-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 634.449
        builtOn: chef-ubuntu-12.04-i386-tester-a0fc88
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-12.04,project=chef,role=tester/118/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 826.492
        builtOn: chef-ubuntu-14.04-tester-eb4a2d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-14.04,project=chef,role=tester/118/
        omnibus_builders: {}
      ubuntu-14.04-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 609.356
        builtOn: chef-ubuntu-14.04-i386-tester-dd49dd
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-14.04,project=chef,role=tester/118/
        omnibus_builders: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 2350.097
        builtOn: chef-windows-2008r2-tester-b8462c
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2008r2,project=chef,role=tester/118/
        omnibus_builders: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 2479.655
        builtOn: chef-windows-2008r2-i386-tester-7a4e69
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=windows-2008r2,project=chef,role=tester/118/
        omnibus_builders: {}
      windows-2012:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 2535.394
        builtOn: chef-windows-2012-tester-f1420a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012,project=chef,role=tester/118/
        omnibus_builders: {}
      windows-2012r2:
        result: SUCCESS
        timestamp: '2016-03-02T19:24:56-08:00'
        duration: 2618.644
        builtOn: chef-windows-2012r2-tester-a5e480
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012r2,project=chef,role=tester/118/
        omnibus_builders: {}
  chef-promote:
    result: SUCCESS
    timestamp: '2016-03-02T20:50:47-08:00'
    duration: 31.377
    url: http://manhattan.ci.chef.co/job/chef-promote/40/
    runs: {}
