---
version: 12.10.4
result: SUCCESS
timestamp: '2016-04-14T12:35:53-07:00'
duration: 6730.445
git_commit: f99b3362694d9cd9f70aa808b96a3fe3420650e1
stages:
  chef-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-14T12:35:53-07:00'
    duration: 110.253
    url: http://manhattan.ci.chef.co/job/chef-trigger-release/61/
    parameters:
      GIT_REF: v12.10.4
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chef-build:
    result: SUCCESS
    timestamp: '2016-04-14T12:37:53-07:00'
    duration: 1753.126
    url: http://manhattan.ci.chef.co/job/chef-build/387/
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 1073.25
        builtOn: chef-aix-6-powerpc-builder-bf6c4a
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/387/
        omnibus_timing: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 810.783
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/387/
        omnibus_timing: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 697.958
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/387/
        omnibus_timing: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 850.933
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/387/
        omnibus_timing: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 705.043
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/387/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 897.9
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/387/
        omnibus_timing: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 751.136
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/387/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 726.435
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/387/
        omnibus_timing: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 787.104
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/387/
        omnibus_timing: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 670.884
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/387/
        omnibus_timing: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 847.632
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/387/
        omnibus_timing: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 652.101
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/387/
        omnibus_timing: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 323.67
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/387/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 308.708
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/387/
        omnibus_timing: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 381.634
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/387/
        omnibus_timing: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 479.913
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/387/
        omnibus_timing: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 1679.94
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/387/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 727.881
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/387/
        omnibus_timing: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 670.08
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/387/
        omnibus_timing: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 1585.682
        builtOn: chef-windows-2008r2-builder-8b402f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/387/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-14T12:37:53-07:00'
        duration: 1177.364
        builtOn: chef-windows-2008r2-i386-builder-66fdc7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/387/
        omnibus_timing: {}
  chef-test:
    result: SUCCESS
    timestamp: '2016-04-14T13:07:14-07:00'
    duration: 4838.299
    url: http://manhattan.ci.chef.co/job/chef-test/249/
    runs:
      acceptance:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 2999.354
        builtOn: chef-ubuntu-14.04-acceptance-469d58
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=acceptance,project=chef,role=tester/249/
        omnibus_timing: {}
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1371.023
        builtOn: chef-aix-6-powerpc-tester-c5f3a4
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-6.1,project=chef,role=tester/249/
        omnibus_timing: {}
      aix-7.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1283.819
        builtOn: chef-aix-7-powerpc-tester-58983e
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-7.1,project=chef,role=tester/249/
        omnibus_timing: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1151.097
        builtOn: chef-debian-6-tester-61fa80
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-6,project=chef,role=tester/249/
        omnibus_timing: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 622.793
        builtOn: chef-debian-6-i386-tester-52378a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-6,project=chef,role=tester/249/
        omnibus_timing: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 830.976
        builtOn: chef-debian-7-tester-c208ec
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-7,project=chef,role=tester/249/
        omnibus_timing: {}
      debian-7-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 647.555
        builtOn: chef-debian-7-i386-tester-d74358
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-7,project=chef,role=tester/249/
        omnibus_timing: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 928.022
        builtOn: chef-debian-8-tester-26c16f
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-8,project=chef,role=tester/249/
        omnibus_timing: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1992.515
        builtOn: chef-rhel-5-tester-3d4799
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-5,project=chef,role=tester/249/
        omnibus_timing: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1382.218
        builtOn: chef-rhel-5-i386-tester-6b2182
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-5,project=chef,role=tester/249/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 2967.437
        builtOn: chef-rhel-6-tester-ad4e43
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-6,project=chef,role=tester/249/
        omnibus_timing: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1799.639
        builtOn: chef-rhel-6-i386-tester-a310b5
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-6,project=chef,role=tester/249/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 772.444
        builtOn: chef-rhel-7-tester-ef80de
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-7,project=chef,role=tester/249/
        omnibus_timing: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 865.798
        builtOn: chef-freebsd-10-tester-0e44ab
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-10,project=chef,role=tester/249/
        omnibus_timing: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 563.56
        builtOn: chef-freebsd-10-i386-tester-f27513
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-10,project=chef,role=tester/249/
        omnibus_timing: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1043.3
        builtOn: chef-freebsd-9-tester-fe6076
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-9,project=chef,role=tester/249/
        omnibus_timing: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 627.895
        builtOn: chef-freebsd-9-i386-tester-f811ce
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-9,project=chef,role=tester/249/
        omnibus_timing: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 601.407
        builtOn: chef-ios_xr-6-tester-2f039d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ios_xr-6,project=chef,role=tester/249/
        omnibus_timing: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 570.82
        builtOn: chef-mac_os_x-10.10-tester-f93984
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.10,project=chef,role=tester/249/
        omnibus_timing: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 495.474
        builtOn: chef-mac_os_x-10.11-tester-bb5587
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.11,project=chef,role=tester/249/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 599.104
        builtOn: chef-mac_os_x-10.9-tester-61d54d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=tester/249/
        omnibus_timing: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 752.445
        builtOn: chef-nexus-7-tester-fd11dc
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=nexus-7,project=chef,role=tester/249/
        omnibus_timing: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 445.899
        builtOn: chef-solaris-10-i86pc-tester-df8804
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-10,project=chef,role=tester/249/
        omnibus_timing: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 4673.88
        builtOn: chef-solaris-10-sun4v-tester-089b13
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-10,project=chef,role=tester/249/
        omnibus_timing: {}
      solaris-11-i86pc:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 467.607
        builtOn: chef-solaris-11-i86pc-tester-d2a1f7
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-11,project=chef,role=tester/249/
        omnibus_timing: {}
      solaris-11-sun4v:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 4836.364
        builtOn: chef-solaris-11-sun4v-tester-988f0a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-11,project=chef,role=tester/249/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 973.006
        builtOn: chef-ubuntu-10.04-tester-122b8b
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=tester/249/
        omnibus_timing: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 553.776
        builtOn: chef-ubuntu-10.04-i386-tester-eebef0
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-10.04,project=chef,role=tester/249/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 945.662
        builtOn: chef-ubuntu-12.04-tester-d79170
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-12.04,project=chef,role=tester/249/
        omnibus_timing: {}
      ubuntu-12.04-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 636.236
        builtOn: chef-ubuntu-12.04-i386-tester-a0fc88
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-12.04,project=chef,role=tester/249/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 829.499
        builtOn: chef-ubuntu-14.04-tester-eb4a2d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-14.04,project=chef,role=tester/249/
        omnibus_timing: {}
      ubuntu-14.04-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 656.625
        builtOn: chef-ubuntu-14.04-i386-tester-dd49dd
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-14.04,project=chef,role=tester/249/
        omnibus_timing: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1416.985
        builtOn: chef-windows-2008r2-tester-b8462c
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2008r2,project=chef,role=tester/249/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1810.583
        builtOn: chef-windows-2008r2-i386-tester-7a4e69
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=windows-2008r2,project=chef,role=tester/249/
        omnibus_timing: {}
      windows-2012:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1556.834
        builtOn: chef-windows-2012-tester-f1420a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012,project=chef,role=tester/249/
        omnibus_timing: {}
      windows-2012r2:
        result: SUCCESS
        timestamp: '2016-04-14T13:07:14-07:00'
        duration: 1703.578
        builtOn: chef-windows-2012r2-tester-a5e480
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012r2,project=chef,role=tester/249/
        omnibus_timing: {}
  chef-promote:
    result: SUCCESS
    timestamp: '2016-04-14T14:28:02-07:00'
    duration: 28.767
    url: http://manhattan.ci.chef.co/job/chef-promote/84/
    runs: {}
