---
version: 12.10.14
result: FAILURE
timestamp: '2016-04-22T11:35:40-07:00'
duration: 6640.735000000001
git_commit: df49c733c5edcf60c3677faa969410ddd645285f
stages:
  chef-trigger-release:
    result: SUCCESS
    timestamp: '2016-04-22T11:35:40-07:00'
    duration: 75.988
    url: http://manhattan.ci.chef.co/job/chef-trigger-release/71/
    parameters:
      GIT_REF: v12.10.14
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Chef Jenkins User
      userId: chef-jenkins
      userName: Chef Jenkins User
    runs: {}
  chef-build:
    result: SUCCESS
    timestamp: '2016-04-22T11:37:05-07:00'
    duration: 1995.035
    url: http://manhattan.ci.chef.co/job/chef-build/449/
    runs:
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 1060.629
        builtOn: chef-aix-6-powerpc-builder-88f619
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=powerpc,platform=aix-6.1,project=chef,role=builder/449/
        omnibus_timing: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 689.853
        builtOn: chef-debian-6-builder-cdb146
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=debian-6,project=chef,role=builder/449/
        omnibus_timing: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 587.315
        builtOn: chef-debian-6-i386-builder-ade2b2
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=debian-6,project=chef,role=builder/449/
        omnibus_timing: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 730.479
        builtOn: chef-rhel-5-builder-0876aa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-5,project=chef,role=builder/449/
        omnibus_timing: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 635.549
        builtOn: chef-rhel-5-i386-builder-1d7cab
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-5,project=chef,role=builder/449/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 763.223
        builtOn: chef-rhel-6-builder-358778
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-6,project=chef,role=builder/449/
        omnibus_timing: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 634.286
        builtOn: chef-rhel-6-i386-builder-89c0c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=el-6,project=chef,role=builder/449/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 585.62
        builtOn: chef-rhel-7-builder-7777fa
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=el-7,project=chef,role=builder/449/
        omnibus_timing: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 695.939
        builtOn: chef-freebsd-10-builder-cd7c49
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-10,project=chef,role=builder/449/
        omnibus_timing: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 516.913
        builtOn: chef-freebsd-10-i386-builder-2758f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-10,project=chef,role=builder/449/
        omnibus_timing: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 770.662
        builtOn: chef-freebsd-9-builder-a75aff
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=freebsd-9,project=chef,role=builder/449/
        omnibus_timing: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 574.638
        builtOn: chef-freebsd-9-i386-builder-a4d0bd
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=freebsd-9,project=chef,role=builder/449/
        omnibus_timing: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 337.196
        builtOn: chef-ios_xr-6-builder-ff30c9
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ios_xr-6,project=chef,role=builder/449/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 261.266
        builtOn: chef-mac_os_x-10.9-builder-e394f7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=builder/449/
        omnibus_timing: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 380.924
        builtOn: chef-nexus-7-builder-bf8ea8
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=nexus-7,project=chef,role=builder/449/
        omnibus_timing: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 447.311
        builtOn: chef-solaris-10-i86pc-builder-438438
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i86pc,platform=solaris-10,project=chef,role=builder/449/
        omnibus_timing: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 1907.326
        builtOn: chef-solaris-10-sun4v-builder-a6fb8f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=sun4v,platform=solaris-10,project=chef,role=builder/449/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 677.592
        builtOn: chef-ubuntu-10.04-builder-a0c84f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=builder/449/
        omnibus_timing: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 585.94
        builtOn: chef-ubuntu-10.04-i386-builder-fe2059
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=ubuntu-10.04,project=chef,role=builder/449/
        omnibus_timing: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 1488.191
        builtOn: chef-windows-2008r2-builder-8b402f
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=x86_64,platform=windows-2008r2,project=chef,role=builder/449/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-22T11:37:05-07:00'
        duration: 1072.051
        builtOn: chef-windows-2008r2-i386-builder-66fdc7
        url: http://manhattan.ci.chef.co/job/chef-build/architecture=i386,platform=windows-2008r2,project=chef,role=builder/449/
        omnibus_timing: {}
  chef-test:
    result: FAILURE
    timestamp: '2016-04-22T12:10:30-07:00'
    duration: 4569.712
    url: http://manhattan.ci.chef.co/job/chef-test/280/
    runs:
      acceptance:
        result: FAILURE
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 3288.835
        builtOn: chef-ubuntu-14.04-acceptance-469d58
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=acceptance,project=chef,role=tester/280/
      aix-6.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1273.981
        builtOn: chef-aix-6-powerpc-tester-9495ea
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-6.1,project=chef,role=tester/280/
        omnibus_timing: {}
      aix-7.1-powerpc:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1199.534
        builtOn: chef-aix-7-powerpc-tester-c0a4cc
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=powerpc,platform=aix-7.1,project=chef,role=tester/280/
        omnibus_timing: {}
      debian-6:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1129.764
        builtOn: chef-debian-6-tester-61fa80
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-6,project=chef,role=tester/280/
        omnibus_timing: {}
      debian-6-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 600.442
        builtOn: chef-debian-6-i386-tester-52378a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-6,project=chef,role=tester/280/
        omnibus_timing: {}
      debian-7:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 802.778
        builtOn: chef-debian-7-tester-c208ec
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-7,project=chef,role=tester/280/
        omnibus_timing: {}
      debian-7-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 641.603
        builtOn: chef-debian-7-i386-tester-d74358
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=debian-7,project=chef,role=tester/280/
        omnibus_timing: {}
      debian-8:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 912.57
        builtOn: chef-debian-8-tester-26c16f
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=debian-8,project=chef,role=tester/280/
        omnibus_timing: {}
      el-5:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1940.841
        builtOn: chef-rhel-5-tester-3d4799
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-5,project=chef,role=tester/280/
        omnibus_timing: {}
      el-5-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1350.94
        builtOn: chef-rhel-5-i386-tester-6b2182
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-5,project=chef,role=tester/280/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 2873.512
        builtOn: chef-rhel-6-tester-ad4e43
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-6,project=chef,role=tester/280/
        omnibus_timing: {}
      el-6-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1760.184
        builtOn: chef-rhel-6-i386-tester-a310b5
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=el-6,project=chef,role=tester/280/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 755.586
        builtOn: chef-rhel-7-tester-ef80de
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=el-7,project=chef,role=tester/280/
        omnibus_timing: {}
      freebsd-10:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 856.595
        builtOn: chef-freebsd-10-tester-0e44ab
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-10,project=chef,role=tester/280/
        omnibus_timing: {}
      freebsd-10-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 526.772
        builtOn: chef-freebsd-10-i386-tester-f27513
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-10,project=chef,role=tester/280/
        omnibus_timing: {}
      freebsd-9:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 913.836
        builtOn: chef-freebsd-9-tester-fe6076
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=freebsd-9,project=chef,role=tester/280/
        omnibus_timing: {}
      freebsd-9-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 562.995
        builtOn: chef-freebsd-9-i386-tester-f811ce
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=freebsd-9,project=chef,role=tester/280/
        omnibus_timing: {}
      ios_xr-6:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 468.485
        builtOn: chef-ios_xr-6-tester-2f039d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ios_xr-6,project=chef,role=tester/280/
        omnibus_timing: {}
      mac_os_x-10.10:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 600.532
        builtOn: chef-mac_os_x-10.10-tester-f93984
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.10,project=chef,role=tester/280/
        omnibus_timing: {}
      mac_os_x-10.11:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 492.013
        builtOn: chef-mac_os_x-10.11-tester-bb5587
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.11,project=chef,role=tester/280/
        omnibus_timing: {}
      mac_os_x-10.9:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 562.565
        builtOn: chef-mac_os_x-10.9-tester-61d54d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=mac_os_x-10.9,project=chef,role=tester/280/
        omnibus_timing: {}
      nexus-7:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 620.64
        builtOn: chef-nexus-7-tester-fd11dc
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=nexus-7,project=chef,role=tester/280/
        omnibus_timing: {}
      solaris-10-i86pc:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 428.435
        builtOn: chef-solaris-10-i86pc-tester-df8804
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-10,project=chef,role=tester/280/
        omnibus_timing: {}
      solaris-10-sun4v:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 4426.294
        builtOn: chef-solaris-10-sun4v-tester-089b13
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-10,project=chef,role=tester/280/
        omnibus_timing: {}
      solaris-11-i86pc:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 453.282
        builtOn: chef-solaris-11-i86pc-tester-d2a1f7
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i86pc,platform=solaris-11,project=chef,role=tester/280/
        omnibus_timing: {}
      solaris-11-sun4v:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 4565.963
        builtOn: chef-solaris-11-sun4v-tester-988f0a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=sun4v,platform=solaris-11,project=chef,role=tester/280/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 957.329
        builtOn: chef-ubuntu-10.04-tester-122b8b
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-10.04,project=chef,role=tester/280/
        omnibus_timing: {}
      ubuntu-10.04-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 531.431
        builtOn: chef-ubuntu-10.04-i386-tester-eebef0
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-10.04,project=chef,role=tester/280/
        omnibus_timing: {}
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 812.95
        builtOn: chef-ubuntu-12.04-tester-d79170
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-12.04,project=chef,role=tester/280/
      ubuntu-12.04-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 621.462
        builtOn: chef-ubuntu-12.04-i386-tester-a0fc88
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-12.04,project=chef,role=tester/280/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 819.559
        builtOn: chef-ubuntu-14.04-tester-eb4a2d
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=ubuntu-14.04,project=chef,role=tester/280/
        omnibus_timing: {}
      ubuntu-14.04-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 619.106
        builtOn: chef-ubuntu-14.04-i386-tester-dd49dd
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=ubuntu-14.04,project=chef,role=tester/280/
        omnibus_timing: {}
      windows-2008r2:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1394.899
        builtOn: chef-windows-2008r2-tester-b8462c
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2008r2,project=chef,role=tester/280/
        omnibus_timing: {}
      windows-2008r2-i386:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1893.704
        builtOn: chef-windows-2008r2-i386-tester-7a4e69
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=i386,platform=windows-2008r2,project=chef,role=tester/280/
        omnibus_timing: {}
      windows-2012:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1513.93
        builtOn: chef-windows-2012-tester-f1420a
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012,project=chef,role=tester/280/
        omnibus_timing: {}
      windows-2012r2:
        result: SUCCESS
        timestamp: '2016-04-22T12:10:30-07:00'
        duration: 1616.008
        builtOn: chef-windows-2012r2-tester-a5e480
        url: http://manhattan.ci.chef.co/job/chef-test/architecture=x86_64,platform=windows-2012r2,project=chef,role=tester/280/
        omnibus_timing: {}
