---
version: 12.6.0+20160511134029
result: SUCCESS
timestamp: '2016-05-11T06:40:09-07:00'
duration: 4271.046
git_commit: 10a8dc952ea0b9366025ce6a738f9697956cd4e1
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-05-11T06:40:09-07:00'
    duration: 10.092
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/109/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-05-11T06:40:29-07:00'
    duration: 1268.669
    url: http://wilson.ci.chef.co/job/chef-server-12-build/268/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-05-11T06:40:29-07:00'
        duration: 1257.387
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/268/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-11T06:40:29-07:00'
        duration: 1183.857
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/268/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-11T06:40:29-07:00'
        duration: 1169.415
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/268/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-11T06:40:29-07:00'
        duration: 1018.638
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/268/
        omnibus_builders: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-05-11T07:01:45-07:00'
    duration: 2984.515
    url: http://wilson.ci.chef.co/job/chef-server-12-test/227/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-05-11T07:01:45-07:00'
        duration: 2923.591
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/227/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-11T07:01:45-07:00'
        duration: 2983.808
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/227/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-11T07:01:45-07:00'
        duration: 2299.242
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/227/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-11T07:01:45-07:00'
        duration: 2635.834
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/227/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-11T07:01:45-07:00'
        duration: 2614.837
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/227/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-11T07:01:45-07:00'
        duration: 2532.738
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/227/
        omnibus_builders: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-05-11T07:51:36-07:00'
    duration: 7.77
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/160/
    runs: {}
