---
version: 12.6.0+20160511213023
result: SUCCESS
timestamp: '2016-05-11T14:30:08-07:00'
duration: 10570.598
git_commit: 123168d1beec453fe98f0656ed91dcda77b6d555
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-05-11T14:30:08-07:00'
    duration: 9.197
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/111/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-05-11T14:30:23-07:00'
    duration: 7621.005
    url: http://wilson.ci.chef.co/job/chef-server-12-build/271/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-05-11T14:30:23-07:00'
        duration: 3772.059
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/271/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-11T14:30:23-07:00'
        duration: 3707.933
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/271/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-11T14:30:23-07:00'
        duration: 2805.849
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/271/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-11T14:30:23-07:00'
        duration: 2570.588
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/271/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-05-11T16:37:34-07:00'
    duration: 2932.898
    url: http://wilson.ci.chef.co/job/chef-server-12-test/230/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-05-11T16:37:34-07:00'
        duration: 2932.324
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/230/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-11T16:37:34-07:00'
        duration: 2924.918
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/230/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-11T16:37:34-07:00'
        duration: 2346.222
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/230/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-11T16:37:34-07:00'
        duration: 2643.018
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/230/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-11T16:37:34-07:00'
        duration: 2558.604
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/230/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-11T16:37:34-07:00'
        duration: 2568.019
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/230/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-05-11T17:26:36-07:00'
    duration: 7.498
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/163/
    runs: {}
