---
version: 12.6.0+20160512144030
result: SUCCESS
timestamp: '2016-05-12T07:40:10-07:00'
duration: 6821.676
git_commit: 329dc5bb39cbbf9c45a1e6e615e4d4989abda941
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-05-12T07:40:10-07:00'
    duration: 10.222
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/112/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-05-12T07:40:30-07:00'
    duration: 3769.245
    url: http://wilson.ci.chef.co/job/chef-server-12-build/272/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-05-12T07:40:30-07:00'
        duration: 3757.115
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/272/
        omnibus_builders:
          private-chef-ctl: 0.0584
          ncurses: 52.5515
          libedit: 11.4408
          pcre: 12.073
          openresty: 27.7109
          libossp-uuid: 9.1964
          postgresql92: 43.1587
          erlang: 269.0308
          server-jre: 0.4787
          pg-gem: 20.2171
          knife-opc: 1.9645
          popt: 9.0559
          perl: 166.7783
          cpanminus: 2.6043
          sqitch: 189.4444
          bzip2: 1.0361
          python: 217.7803
          nodejs: 48.2229
          knife-ec-backup: 4.7483
          gecode: 591.9623
          perl_pg_driver: 3.2281
          liblzma: 34.726
          libxml2: 34.7143
          libxslt: 19.0542
          nokogiri: 12.8472
          berkshelf2: 21.6412
          ohai: 14.7691
          appbundler: 5.2124
          private-chef-scripts: 0.0136
          ctl-man: 0.0033
          rb-readline: 0.1042
          redis-gem: 1.204
          openresty-lpeg: 0.4283
          runit: 15.426
          chef_backup-gem: 1.9963
          veil-gem: 2.5553
          rabbitmq: 0.1853
          redis: 10.641
          opscode-solr4: 0.7606
          haproxy: 10.3928
          opscode-expander: 13.3932
          gpg-key: 0.004
          keepalived: 6.0122
          bookshelf: 72.9256
          oc_bifrost: 63.0963
          oc_id: 92.1942
          logrotate: 0.7265
          partybus: 9.4158
          opscode-chef-mover: 161.5261
          oc_erchef: 176.9552
          oc-chef-pedant: 12.7058
          private-chef-upgrades: 0.0856
          private-chef-cookbooks: 6.3342
          chef-ha-plugin-config: 0.0021
          chef: 83.6804
          Health check: 135.638
          Packaging: 595.0608
      el-6:
        result: SUCCESS
        timestamp: '2016-05-12T07:40:30-07:00'
        duration: 3696.923
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/272/
        omnibus_builders:
          private-chef-ctl: 0.0892
          ncurses: 88.8589
          libedit: 14.9217
          pcre: 15.8093
          openresty: 54.4115
          libossp-uuid: 12.4339
          postgresql92: 98.3738
          erlang: 265.202
          server-jre: 0.4632
          pg-gem: 15.4399
          knife-opc: 1.9922
          popt: 11.1806
          perl: 230.6538
          cpanminus: 3.1626
          sqitch: 237.0244
          bzip2: 2.3599
          python: 108.5965
          nodejs: 124.0578
          knife-ec-backup: 4.5345
          gecode: 408.9918
          perl_pg_driver: 6.0923
          liblzma: 39.732
          libxml2: 56.7928
          libxslt: 20.004
          nokogiri: 14.2777
          berkshelf2: 20.5682
          ohai: 15.6352
          appbundler: 5.6713
          private-chef-scripts: 0.2429
          ctl-man: 0.002
          rb-readline: 0.2173
          redis-gem: 1.1785
          openresty-lpeg: 0.8108
          runit: 15.317
          chef_backup-gem: 1.5565
          veil-gem: 3.2734
          rabbitmq: 0.259
          redis: 14.1574
          opscode-solr4: 1.1473
          haproxy: 22.8471
          opscode-expander: 16.3487
          gpg-key: 0.0048
          keepalived: 8.407
          bookshelf: 72.7141
          oc_bifrost: 56.1249
          oc_id: 105.3443
          logrotate: 1.548
          partybus: 10.8237
          opscode-chef-mover: 148.6493
          oc_erchef: 152.5757
          oc-chef-pedant: 12.7213
          private-chef-upgrades: 0.1598
          private-chef-cookbooks: 10.7631
          chef-ha-plugin-config: 0.0029
          chef: 80.4273
          Health check: 131.0054
          Packaging: 542.0766
      el-7:
        result: SUCCESS
        timestamp: '2016-05-12T07:40:30-07:00'
        duration: 2852.896
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/272/
        omnibus_builders:
          private-chef-ctl: 0.0494
          ncurses: 50.777
          libedit: 7.8898
          pcre: 10.6976
          openresty: 38.5734
          libossp-uuid: 6.9056
          postgresql92: 53.9966
          erlang: 164.9214
          server-jre: 0.3725
          pg-gem: 12.0244
          knife-opc: 2.0582
          popt: 5.9701
          perl: 145.841
          cpanminus: 2.6589
          sqitch: 170.4288
          bzip2: 1.5245
          python: 63.5612
          nodejs: 54.0612
          knife-ec-backup: 4.7725
          gecode: 125.7856
          perl_pg_driver: 2.9111
          liblzma: 30.0378
          libxml2: 28.3939
          libxslt: 10.957
          nokogiri: 12.4313
          berkshelf2: 18.5118
          ohai: 14.3914
          appbundler: 5.2892
          private-chef-scripts: 0.0623
          ctl-man: 0.0035
          rb-readline: 0.0798
          redis-gem: 1.3011
          openresty-lpeg: 0.4438
          runit: 15.6398
          chef_backup-gem: 1.4684
          veil-gem: 2.2196
          rabbitmq: 0.2394
          redis: 7.3326
          opscode-solr4: 0.6332
          haproxy: 8.0634
          opscode-expander: 17.5344
          gpg-key: 0.0025
          keepalived: 5.827
          bookshelf: 70.6788
          oc_bifrost: 58.426
          oc_id: 110.3886
          logrotate: 0.4339
          partybus: 8.341
          opscode-chef-mover: 138.0479
          oc_erchef: 129.6716
          oc-chef-pedant: 11.5188
          private-chef-upgrades: 0.0383
          private-chef-cookbooks: 7.3668
          chef-ha-plugin-config: 0.0016
          chef: 62.083
          Health check: 58.1028
          Packaging: 669.6208
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-12T07:40:30-07:00'
        duration: 2546.642
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/272/
        omnibus_builders:
          private-chef-ctl: 0.0864
          ncurses: 39.601
          libedit: 9.4105
          pcre: 9.0411
          openresty: 21.2527
          libossp-uuid: 8.0804
          postgresql92: 47.669
          erlang: 202.3919
          server-jre: 0.5414
          pg-gem: 14.5651
          knife-opc: 1.7604
          popt: 8.0002
          perl: 174.6436
          cpanminus: 3.3008
          sqitch: 203.6938
          bzip2: 1.3002
          python: 57.9732
          nodejs: 46.4584
          knife-ec-backup: 4.4137
          gecode: 19.5246
          perl_pg_driver: 3.7988
          liblzma: 28.2306
          libxml2: 27.9707
          libxslt: 15.8032
          nokogiri: 10.7064
          berkshelf2: 19.4455
          ohai: 13.9357
          appbundler: 6.1951
          private-chef-scripts: 0.0846
          ctl-man: 0.0021
          rb-readline: 0.1203
          redis-gem: 1.2973
          openresty-lpeg: 0.2603
          runit: 14.5113
          chef_backup-gem: 1.5908
          veil-gem: 2.0905
          rabbitmq: 0.1951
          redis: 8.2905
          opscode-solr4: 0.6495
          haproxy: 18.1005
          opscode-expander: 12.8671
          gpg-key: 0.0037
          keepalived: 5.3986
          bookshelf: 66.1888
          oc_bifrost: 60.0586
          oc_id: 94.4057
          logrotate: 0.3541
          partybus: 9.9556
          opscode-chef-mover: 141.6645
          oc_erchef: 143.4323
          oc-chef-pedant: 11.7235
          private-chef-upgrades: 0.1559
          private-chef-cookbooks: 8.2905
          chef-ha-plugin-config: 0.0023
          chef: 67.8014
          Health check: 85.4318
          Packaging: 404.2887
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-05-12T08:43:30-07:00'
    duration: 3034.481
    url: http://wilson.ci.chef.co/job/chef-server-12-test/231/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-05-12T08:43:30-07:00'
        duration: 3033.564
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/231/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-05-12T08:43:30-07:00'
        duration: 2993.493
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/231/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-05-12T08:43:30-07:00'
        duration: 2509.919
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/231/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-05-12T08:43:30-07:00'
        duration: 2599.168
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/231/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-05-12T08:43:30-07:00'
        duration: 2655.916
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/231/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-05-12T08:43:30-07:00'
        duration: 2530.802
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/231/
        omnibus_builders: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-05-12T09:34:10-07:00'
    duration: 7.728
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/164/
    runs: {}
