---
version: 12.3.1+20160121011025
result: FAILURE
timestamp: '2016-01-20T17:10:10-08:00'
duration: 4914.239
git_commit: 32d4098eca186514d2aaa06e14568089a6318bba
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-01-20T17:10:10-08:00'
    duration: 6.379
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/19/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-01-20T17:10:25-08:00'
    duration: 2025.265
    url: http://wilson.ci.chef.co/job/chef-server-12-build/47/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-20T17:10:25-08:00'
        duration: 2016.627
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/47/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-20T17:10:25-08:00'
        duration: 1846.837
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/47/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-20T17:10:25-08:00'
        duration: 1876.739
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/47/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-20T17:10:25-08:00'
        duration: 1110.244
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/47/
        omnibus_builders: {}
  chef-server-12-test:
    result: FAILURE
    timestamp: '2016-01-20T17:44:20-08:00'
    duration: 2882.595
    url: http://wilson.ci.chef.co/job/chef-server-12-test/46/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-20T17:44:20-08:00'
        duration: 2817.418
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/46/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-20T17:44:20-08:00'
        duration: 2864.85
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/46/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-20T17:44:20-08:00'
        duration: 2340.365
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/46/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-20T17:44:20-08:00'
        duration: 2725.097
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/46/
        omnibus_builders: {}
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-01-20T17:44:20-08:00'
        duration: 2882.333
        builtOn: chef-server-ubuntu-12.04-tester-5b0c0e
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/46/
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-01-20T17:44:20-08:00'
        duration: 2570.16
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/46/
        omnibus_builders: {}
