---
result: FAILURE
timestamp: '2015-12-14T09:00:12-08:00'
duration: 2797.3559999999998
version: 12.3.1+20151214170022
git_commit: 31a8526a5c6b780230edbfd29440de068327e05d
stages:
  chef-server-12-test:
    result: FAILURE
    failures:
      unknown: all
    timestamp: '2015-12-14T09:39:53-08:00'
    duration: 431.081
    url: http://wilson.ci.chef.co/job/chef-server-12-test/6/
    parameters:
      GIT_REF: origin/master
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 31a8526a5c6b780230edbfd29440de068327e05d
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '5'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "ubuntu-10.04": [
              "ubuntu-10.04",
              "ubuntu-12.04",
              "ubuntu-14.04"
            ],
            "el-5": [
              "el-5"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ]
          },
          "test_to_build": {
            "ubuntu-10.04": "ubuntu-10.04",
            "ubuntu-12.04": "ubuntu-10.04",
            "ubuntu-14.04": "ubuntu-10.04",
            "el-5": "el-5",
            "el-6": "el-6",
            "el-7": "el-7"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '6'
      PIPELINE_BUILD_JOB_NAME: chef-server-12-build
      OMNIBUS_BUILD_VERSION: 12.3.1+20151214170022
    runs:
      el-5:
        result: FAILURE
        timestamp: '2015-12-14T09:39:53-08:00'
        duration: 430.119
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/6/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      el-6:
        result: FAILURE
        timestamp: '2015-12-14T09:39:53-08:00'
        duration: 275.137
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/6/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      el-7:
        result: FAILURE
        timestamp: '2015-12-14T09:39:53-08:00'
        duration: 353.642
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/6/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      ubuntu-10.04:
        result: FAILURE
        timestamp: '2015-12-14T09:39:53-08:00'
        duration: 287.975
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/6/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2015-12-14T09:39:53-08:00'
        duration: 305.454
        builtOn: chef-server-ubuntu-12.04-tester-5b0c0e
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/6/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      ubuntu-14.04:
        result: FAILURE
        timestamp: '2015-12-14T09:39:53-08:00'
        duration: 279.877
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/6/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2015-12-14T09:00:22-08:00'
    duration: 2363.863
    url: http://wilson.ci.chef.co/job/chef-server-12-build/6/
    parameters:
      GIT_REF: origin/master
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 31a8526a5c6b780230edbfd29440de068327e05d
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '5'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2015-12-14T09:00:22-08:00'
        duration: 2294.497
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/6/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2015-12-14T09:00:22-08:00'
        duration: 1759.589
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/6/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2015-12-14T09:00:22-08:00'
        duration: 1798.785
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/6/
        omnibusTiming: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2015-12-14T09:00:22-08:00'
        duration: 1255.698
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/6/
        omnibusTiming: {}
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2015-12-14T09:00:12-08:00'
    duration: 2.412
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/5/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
