---
result: FAILURE
timestamp: '2015-12-15T05:10:08-08:00'
duration: 2575.553
version: 12.3.1+20151215131023
git_commit: 2b81d4acab3a1b3218dbc7dfb1afec72ef35db77
stages:
  chef-server-12-test:
    result: FAILURE
    failures:
      unknown: all
    timestamp: '2015-12-15T05:47:28-08:00'
    duration: 350.094
    url: http://wilson.ci.chef.co/job/chef-server-12-test/8/
    parameters:
      OMNIBUS_BUILD_VERSION: 12.3.1+20151215131023
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: origin/master
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 2b81d4acab3a1b3218dbc7dfb1afec72ef35db77
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '6'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "ubuntu-10.04": [
              "ubuntu-10.04",
              "ubuntu-12.04",
              "ubuntu-14.04"
            ],
            "el-5": [
              "el-5"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ]
          },
          "test_to_build": {
            "ubuntu-10.04": "ubuntu-10.04",
            "ubuntu-12.04": "ubuntu-10.04",
            "ubuntu-14.04": "ubuntu-10.04",
            "el-5": "el-5",
            "el-6": "el-6",
            "el-7": "el-7"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '8'
      PIPELINE_BUILD_JOB_NAME: chef-server-12-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-6/6/2015-12-15_13-10-08
    runs:
      el-5:
        result: FAILURE
        timestamp: '2015-12-15T05:47:28-08:00'
        duration: 349.37
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/8/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      el-6:
        result: FAILURE
        timestamp: '2015-12-15T05:47:28-08:00'
        duration: 279.256
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/8/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      el-7:
        result: FAILURE
        timestamp: '2015-12-15T05:47:28-08:00'
        duration: 340.461
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/8/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      ubuntu-10.04:
        result: FAILURE
        timestamp: '2015-12-15T05:47:28-08:00'
        duration: 280.702
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/8/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2015-12-15T05:47:28-08:00'
        duration: 308.748
        builtOn: chef-server-ubuntu-12.04-tester-5b0c0e
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/8/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      ubuntu-14.04:
        result: FAILURE
        timestamp: '2015-12-15T05:47:28-08:00'
        duration: 265.727
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/8/
        failureCause:
          jenkinsBuildStep: Invoke XShell command
          suspiciousLines:
          - 'ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to
            exception'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2015-12-15T05:10:23-08:00'
    duration: 2218.297
    url: http://wilson.ci.chef.co/job/chef-server-12-build/8/
    parameters:
      GIT_REF: origin/master
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 2b81d4acab3a1b3218dbc7dfb1afec72ef35db77
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '6'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2015-12-15T05:10:23-08:00'
        duration: 2156.16
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/8/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2015-12-15T05:10:23-08:00'
        duration: 1795.241
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/8/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2015-12-15T05:10:23-08:00'
        duration: 1494.887
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/8/
        omnibusTiming: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2015-12-15T05:10:23-08:00'
        duration: 1164.356
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/8/
        omnibusTiming: {}
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2015-12-15T05:10:08-08:00'
    duration: 7.162
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/6/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
