---
result: FAILURE
timestamp: '2016-03-02T15:10:07-08:00'
duration: 4237.043000000001
version: 
git_commit: 0a0513218b88eef66f60829b8b7c535e8bfb774c
stages:
  chef-server-12-build:
    result: FAILURE
    failures:
      'omnibus GitFetcher: rebar': all
    timestamp: '2016-03-02T15:10:23-08:00'
    duration: 4227.859
    url: http://wilson.ci.chef.co/job/chef-server-12-build/143/
    parameters:
      GIT_REF: origin/master
      APPEND_TIMESTAMP: true
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 0a0513218b88eef66f60829b8b7c535e8bfb774c
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '61'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
    runs:
      el-5:
        result: FAILURE
        timestamp: '2016-03-02T15:10:23-08:00'
        duration: 115.677
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/143/
        failureCause:
          cause: omnibus
          detailedCause: 'omnibus GitFetcher: rebar'
          jenkinsBuildStep: Invoke XShell command
          lastOmnibusLine: "[GitFetcher: rebar] I | Fetching from `https://github.com/rebar/rebar.git'"
          lastOmnibusStep: 'GitFetcher: rebar'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      el-6:
        result: FAILURE
        timestamp: '2016-03-02T15:10:23-08:00'
        duration: 108.617
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/143/
        failureCause:
          cause: omnibus
          detailedCause: 'omnibus GitFetcher: rebar'
          jenkinsBuildStep: Invoke XShell command
          lastOmnibusLine: "[GitFetcher: rebar] I | Fetching from `https://github.com/rebar/rebar.git'"
          lastOmnibusStep: 'GitFetcher: rebar'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      el-7:
        result: FAILURE
        timestamp: '2016-03-02T15:10:23-08:00'
        duration: 133.252
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/143/
        failureCause:
          cause: omnibus
          detailedCause: 'omnibus GitFetcher: rebar'
          jenkinsBuildStep: Invoke XShell command
          lastOmnibusLine: "[GitFetcher: rebar] I | Fetching from `https://github.com/rebar/rebar.git'"
          lastOmnibusStep: 'GitFetcher: rebar'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
      ubuntu-10.04:
        result: FAILURE
        timestamp: '2016-03-02T15:10:23-08:00'
        duration: 125.637
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/143/
        failureCause:
          cause: omnibus
          detailedCause: 'omnibus GitFetcher: rebar'
          jenkinsBuildStep: Invoke XShell command
          lastOmnibusLine: "[GitFetcher: rebar] I | Fetching from `https://github.com/rebar/rebar.git'"
          lastOmnibusStep: 'GitFetcher: rebar'
        failureReason:
          jenkinsBuildStep: Invoke XShell command
        omnibusTiming: {}
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-02T15:10:07-08:00'
    duration: 9.184
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/61/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
