---
result: FAILURE
timestamp: '2016-03-02T15:20:08-08:00'
duration: 3718.283
version: 
git_commit: fe19e28de26157c05740824ed3bc923cefec87df
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-02T15:20:08-08:00'
    duration: 8.598
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/62/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: FAILURE
    failures: all
    timestamp: '2016-03-02T15:20:23-08:00'
    duration: 3709.685
    url: http://wilson.ci.chef.co/job/chef-server-12-build/144/
    parameters:
      GIT_REF: origin/master
      APPEND_TIMESTAMP: true
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: fe19e28de26157c05740824ed3bc923cefec87df
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '62'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
    runs:
      el-5:
        result: FAILURE
        timestamp: '2016-03-02T15:20:23-08:00'
        duration: 86.828
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/144/
        omnibusTiming: {}
      el-6:
        result: FAILURE
        timestamp: '2016-03-02T15:20:23-08:00'
        duration: 84.106
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/144/
        omnibusTiming: {}
      el-7:
        result: FAILURE
        timestamp: '2016-03-02T15:20:23-08:00'
        duration: 86.13
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/144/
        omnibusTiming: {}
      ubuntu-10.04:
        result: FAILURE
        timestamp: '2016-03-02T15:20:23-08:00'
        duration: 85.347
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/144/
        omnibusTiming: {}
