---
result: SUCCESS
timestamp: '2016-01-29T14:50:09-08:00'
duration: 8934.009
version: 12.4.0+20160129225024
git_commit: 1488ceb22783c6172cc2432fc88ad63bcfe1ee12
stages:
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-01-29T17:19:19-08:00'
    duration: 7.752
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/39/
    parameters:
      OMNIBUS_BUILD_VERSION: 12.4.0+20160129225024
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: origin/master
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 1488ceb22783c6172cc2432fc88ad63bcfe1ee12
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '40'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "ubuntu-10.04": [
              "ubuntu-10.04",
              "ubuntu-12.04",
              "ubuntu-14.04"
            ],
            "el-5": [
              "el-5"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ]
          },
          "test_to_build": {
            "ubuntu-10.04": "ubuntu-10.04",
            "ubuntu-12.04": "ubuntu-10.04",
            "ubuntu-14.04": "ubuntu-10.04",
            "el-5": "el-5",
            "el-6": "el-6",
            "el-7": "el-7"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '81'
      PIPELINE_BUILD_JOB_NAME: chef-server-12-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-40/40/2016-01-29_22-50-09
    runs: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-01-29T16:04:47-08:00'
    duration: 4465.222
    url: http://wilson.ci.chef.co/job/chef-server-12-test/76/
    parameters:
      OMNIBUS_BUILD_VERSION: 12.4.0+20160129225024
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: origin/master
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 1488ceb22783c6172cc2432fc88ad63bcfe1ee12
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '40'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "ubuntu-10.04": [
              "ubuntu-10.04",
              "ubuntu-12.04",
              "ubuntu-14.04"
            ],
            "el-5": [
              "el-5"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ]
          },
          "test_to_build": {
            "ubuntu-10.04": "ubuntu-10.04",
            "ubuntu-12.04": "ubuntu-10.04",
            "ubuntu-14.04": "ubuntu-10.04",
            "el-5": "el-5",
            "el-6": "el-6",
            "el-7": "el-7"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '81'
      PIPELINE_BUILD_JOB_NAME: chef-server-12-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-40/40/2016-01-29_22-50-09
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-29T16:04:47-08:00'
        duration: 2843.348
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/76/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-29T16:04:47-08:00'
        duration: 2962.614
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/76/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-29T16:04:47-08:00'
        duration: 2286.718
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/76/
        omnibusTiming: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-29T16:04:47-08:00'
        duration: 2596.892
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/76/
        omnibusTiming: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-01-29T16:04:47-08:00'
        duration: 2646.02
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/76/
        omnibusTiming: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-01-29T16:04:47-08:00'
        duration: 2500.76
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/76/
        omnibusTiming: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-01-29T14:50:24-08:00'
    duration: 4454.091
    url: http://wilson.ci.chef.co/job/chef-server-12-build/81/
    parameters:
      GIT_REF: origin/master
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 1488ceb22783c6172cc2432fc88ad63bcfe1ee12
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '40'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-29T14:50:24-08:00'
        duration: 1996.789
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/81/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-29T14:50:24-08:00'
        duration: 1775.146
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/81/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-29T14:50:24-08:00'
        duration: 1398.524
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/81/
        omnibusTiming: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-29T14:50:24-08:00'
        duration: 1239.219
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/81/
        omnibusTiming: {}
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-01-29T14:50:09-08:00'
    duration: 6.944
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/40/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    retries:
    - url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/41/
      result: SUCCESS
      timestamp: '2016-02-01T14:49:38-08:00'
      duration: 7.094
      number: 41
      job: chef-server-12-trigger-git_poll
      causes:
      - shortDescription: Started by an SCM change
      - shortDescription: Started by user Stephen Delano
        userId: sdelano
        userName: Stephen Delano
      parameters: {}
      retryOf:
      - 40
      downstreams:
      - url: http://wilson.ci.chef.co/job/chef-server-12-build/84/
        result: SUCCESS
        timestamp: '2016-02-01T14:49:52-08:00'
        duration: 2016.171
        number: 84
        job: chef-server-12-build
        parameters:
          GIT_REF: origin/master
          DELIVERY_CHANGE: ''
          DELIVERY_SHA: ''
          EXPIRE_CACHE: 'false'
          RELEASE_BUILD: 'false'
          PIPELINE_NAME: chef-server-12
          GIT_COMMIT: 1488ceb22783c6172cc2432fc88ad63bcfe1ee12
          PROJECT: chef-server
          PROMOTE: 'true'
          PIPELINE_TRIGGER_BUILD_NUMBER: '41'
          GIT_BRANCH: origin/master
          PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
          BUILD_USER: SCMTrigger
        upstreams:
        - job: chef-server-12-trigger-git_poll
          number: 41
        downstreams:
        - url: http://wilson.ci.chef.co/job/chef-server-12-test/79/
          result: SUCCESS
          timestamp: '2016-02-01T15:23:37-08:00'
          duration: 2914.481
          number: 79
          job: chef-server-12-test
          parameters:
            OMNIBUS_BUILD_VERSION: 12.4.0+20160201224952
            DELIVERY_CHANGE: ''
            DELIVERY_SHA: ''
            GIT_REF: origin/master
            EXPIRE_CACHE: 'false'
            RELEASE_BUILD: 'false'
            PIPELINE_NAME: chef-server-12
            GIT_COMMIT: 1488ceb22783c6172cc2432fc88ad63bcfe1ee12
            PROJECT: chef-server
            PROMOTE: 'true'
            PIPELINE_TRIGGER_BUILD_NUMBER: '41'
            GIT_BRANCH: origin/master
            PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
            BUILD_USER: SCMTrigger
            PLATFORM_MAPPINGS_JSON: |-
              {
                "build_to_test": {
                  "ubuntu-10.04": [
                    "ubuntu-10.04",
                    "ubuntu-12.04",
                    "ubuntu-14.04"
                  ],
                  "el-5": [
                    "el-5"
                  ],
                  "el-6": [
                    "el-6"
                  ],
                  "el-7": [
                    "el-7"
                  ]
                },
                "test_to_build": {
                  "ubuntu-10.04": "ubuntu-10.04",
                  "ubuntu-12.04": "ubuntu-10.04",
                  "ubuntu-14.04": "ubuntu-10.04",
                  "el-5": "el-5",
                  "el-6": "el-6",
                  "el-7": "el-7"
                }
              }
            PIPELINE_BUILD_JOB_NUMBER: '84'
            PIPELINE_BUILD_JOB_NAME: chef-server-12-build
            PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-41/41/2016-02-01_22-49-38
          upstreams:
          - job: chef-server-12-build
            number: 84
          downstreams:
          - url: http://wilson.ci.chef.co/job/chef-server-12-promote/42/
            result: SUCCESS
            timestamp: '2016-02-01T16:12:18-08:00'
            duration: 7.772
            number: 42
            job: chef-server-12-promote
            parameters:
              OMNIBUS_BUILD_VERSION: 12.4.0+20160201224952
              DELIVERY_CHANGE: ''
              DELIVERY_SHA: ''
              GIT_REF: origin/master
              EXPIRE_CACHE: 'false'
              RELEASE_BUILD: 'false'
              PIPELINE_NAME: chef-server-12
              GIT_COMMIT: 1488ceb22783c6172cc2432fc88ad63bcfe1ee12
              PROJECT: chef-server
              PROMOTE: 'true'
              PIPELINE_TRIGGER_BUILD_NUMBER: '41'
              GIT_BRANCH: origin/master
              PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
              BUILD_USER: SCMTrigger
              PLATFORM_MAPPINGS_JSON: |-
                {
                  "build_to_test": {
                    "ubuntu-10.04": [
                      "ubuntu-10.04",
                      "ubuntu-12.04",
                      "ubuntu-14.04"
                    ],
                    "el-5": [
                      "el-5"
                    ],
                    "el-6": [
                      "el-6"
                    ],
                    "el-7": [
                      "el-7"
                    ]
                  },
                  "test_to_build": {
                    "ubuntu-10.04": "ubuntu-10.04",
                    "ubuntu-12.04": "ubuntu-10.04",
                    "ubuntu-14.04": "ubuntu-10.04",
                    "el-5": "el-5",
                    "el-6": "el-6",
                    "el-7": "el-7"
                  }
                }
              PIPELINE_BUILD_JOB_NUMBER: '84'
              PIPELINE_BUILD_JOB_NAME: chef-server-12-build
              PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-41/41/2016-02-01_22-49-38
            upstreams:
            - job: chef-server-12-test
              number: 79
    runs: {}
