---
result: SUCCESS
timestamp: '2016-02-03T21:00:09-08:00'
duration: 7777.739
version: 12.4.2+20160204050029
git_commit: 06f8817492272074cbc777ab3e29694dfb2cf8ab
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-02-03T21:00:09-08:00'
    duration: 13.248
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/45/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    retries:
    - url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/46/
      result: SUCCESS
      timestamp: '2016-02-05T07:01:58-08:00'
      duration: 18.154
      number: 46
      job: chef-server-12-trigger-git_poll
      causes:
      - shortDescription: Started by an SCM change
      - shortDescription: Started by user Seth Chisamore
        userId: schisamo
        userName: Seth Chisamore
      parameters: {}
      retryOf:
      - 45
      downstreams:
      - url: http://wilson.ci.chef.co/job/chef-server-12-build/96/
        result: SUCCESS
        timestamp: '2016-02-05T07:02:24-08:00'
        duration: 2615.684
        number: 96
        job: chef-server-12-build
        parameters:
          GIT_REF: origin/master
          DELIVERY_CHANGE: ''
          DELIVERY_SHA: ''
          EXPIRE_CACHE: 'false'
          RELEASE_BUILD: 'false'
          PIPELINE_NAME: chef-server-12
          GIT_COMMIT: 06f8817492272074cbc777ab3e29694dfb2cf8ab
          PROJECT: chef-server
          PROMOTE: 'true'
          PIPELINE_TRIGGER_BUILD_NUMBER: '46'
          GIT_BRANCH: origin/master
          PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
          BUILD_USER: SCMTrigger
        upstreams:
        - job: chef-server-12-trigger-git_poll
          number: 46
        downstreams:
        - url: http://wilson.ci.chef.co/job/chef-server-12-test/88/
          result: SUCCESS
          timestamp: '2016-02-05T07:46:09-08:00'
          duration: 2912.437
          number: 88
          job: chef-server-12-test
          parameters:
            OMNIBUS_BUILD_VERSION: 12.4.2+20160205150224
            DELIVERY_CHANGE: ''
            DELIVERY_SHA: ''
            GIT_REF: origin/master
            EXPIRE_CACHE: 'false'
            RELEASE_BUILD: 'false'
            PIPELINE_NAME: chef-server-12
            GIT_COMMIT: 06f8817492272074cbc777ab3e29694dfb2cf8ab
            PROJECT: chef-server
            PROMOTE: 'true'
            PIPELINE_TRIGGER_BUILD_NUMBER: '46'
            GIT_BRANCH: origin/master
            PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
            BUILD_USER: SCMTrigger
            PLATFORM_MAPPINGS_JSON: |-
              {
                "build_to_test": {
                  "ubuntu-10.04": [
                    "ubuntu-10.04",
                    "ubuntu-12.04",
                    "ubuntu-14.04"
                  ],
                  "el-5": [
                    "el-5"
                  ],
                  "el-6": [
                    "el-6"
                  ],
                  "el-7": [
                    "el-7"
                  ]
                },
                "test_to_build": {
                  "ubuntu-10.04": "ubuntu-10.04",
                  "ubuntu-12.04": "ubuntu-10.04",
                  "ubuntu-14.04": "ubuntu-10.04",
                  "el-5": "el-5",
                  "el-6": "el-6",
                  "el-7": "el-7"
                }
              }
            PIPELINE_BUILD_JOB_NUMBER: '96'
            PIPELINE_BUILD_JOB_NAME: chef-server-12-build
            PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-46/46/2016-02-05_15-01-58
          upstreams:
          - job: chef-server-12-build
            number: 96
          downstreams:
          - url: http://wilson.ci.chef.co/job/chef-server-12-promote/51/
            result: SUCCESS
            timestamp: '2016-02-05T08:34:49-08:00'
            duration: 9.005
            number: 51
            job: chef-server-12-promote
            parameters:
              OMNIBUS_BUILD_VERSION: 12.4.2+20160205150224
              DELIVERY_CHANGE: ''
              DELIVERY_SHA: ''
              GIT_REF: origin/master
              EXPIRE_CACHE: 'false'
              RELEASE_BUILD: 'false'
              PIPELINE_NAME: chef-server-12
              GIT_COMMIT: 06f8817492272074cbc777ab3e29694dfb2cf8ab
              PROJECT: chef-server
              PROMOTE: 'true'
              PIPELINE_TRIGGER_BUILD_NUMBER: '46'
              GIT_BRANCH: origin/master
              PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
              BUILD_USER: SCMTrigger
              PLATFORM_MAPPINGS_JSON: |-
                {
                  "build_to_test": {
                    "ubuntu-10.04": [
                      "ubuntu-10.04",
                      "ubuntu-12.04",
                      "ubuntu-14.04"
                    ],
                    "el-5": [
                      "el-5"
                    ],
                    "el-6": [
                      "el-6"
                    ],
                    "el-7": [
                      "el-7"
                    ]
                  },
                  "test_to_build": {
                    "ubuntu-10.04": "ubuntu-10.04",
                    "ubuntu-12.04": "ubuntu-10.04",
                    "ubuntu-14.04": "ubuntu-10.04",
                    "el-5": "el-5",
                    "el-6": "el-6",
                    "el-7": "el-7"
                  }
                }
              PIPELINE_BUILD_JOB_NUMBER: '96'
              PIPELINE_BUILD_JOB_NAME: chef-server-12-build
              PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-46/46/2016-02-05_15-01-58
            upstreams:
            - job: chef-server-12-test
              number: 88
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-02-03T21:00:29-08:00'
    duration: 4891.376
    url: http://wilson.ci.chef.co/job/chef-server-12-build/93/
    parameters:
      GIT_REF: origin/master
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 06f8817492272074cbc777ab3e29694dfb2cf8ab
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '45'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-02-03T21:00:29-08:00'
        duration: 4662.922
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/93/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-02-03T21:00:29-08:00'
        duration: 4880.574
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/93/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-02-03T21:00:29-08:00'
        duration: 4633.352
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/93/
        omnibusTiming: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-02-03T21:00:29-08:00'
        duration: 2949.957
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/93/
        omnibusTiming: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-02-03T22:22:09-08:00'
    duration: 2865.41
    url: http://wilson.ci.chef.co/job/chef-server-12-test/85/
    parameters:
      OMNIBUS_BUILD_VERSION: 12.4.2+20160204050029
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: origin/master
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 06f8817492272074cbc777ab3e29694dfb2cf8ab
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '45'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "ubuntu-10.04": [
              "ubuntu-10.04",
              "ubuntu-12.04",
              "ubuntu-14.04"
            ],
            "el-5": [
              "el-5"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ]
          },
          "test_to_build": {
            "ubuntu-10.04": "ubuntu-10.04",
            "ubuntu-12.04": "ubuntu-10.04",
            "ubuntu-14.04": "ubuntu-10.04",
            "el-5": "el-5",
            "el-6": "el-6",
            "el-7": "el-7"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '93'
      PIPELINE_BUILD_JOB_NAME: chef-server-12-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-45/45/2016-02-04_05-00-09
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-02-03T22:22:09-08:00'
        duration: 2807.818
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/85/
        omnibusTiming: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-02-03T22:22:09-08:00'
        duration: 2864.575
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/85/
        omnibusTiming: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-02-03T22:22:09-08:00'
        duration: 2510.381
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/85/
        omnibusTiming: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-02-03T22:22:09-08:00'
        duration: 2557.527
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/85/
        omnibusTiming: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-02-03T22:22:09-08:00'
        duration: 2587.667
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/85/
        omnibusTiming: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-02-03T22:22:09-08:00'
        duration: 2626.978
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/85/
        omnibusTiming: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-02-03T23:10:00-08:00'
    duration: 7.705
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/48/
    parameters:
      OMNIBUS_BUILD_VERSION: 12.4.2+20160204050029
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      GIT_REF: origin/master
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 06f8817492272074cbc777ab3e29694dfb2cf8ab
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '45'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
      PLATFORM_MAPPINGS_JSON: |-
        {
          "build_to_test": {
            "ubuntu-10.04": [
              "ubuntu-10.04",
              "ubuntu-12.04",
              "ubuntu-14.04"
            ],
            "el-5": [
              "el-5"
            ],
            "el-6": [
              "el-6"
            ],
            "el-7": [
              "el-7"
            ]
          },
          "test_to_build": {
            "ubuntu-10.04": "ubuntu-10.04",
            "ubuntu-12.04": "ubuntu-10.04",
            "ubuntu-14.04": "ubuntu-10.04",
            "el-5": "el-5",
            "el-6": "el-6",
            "el-7": "el-7"
          }
        }
      PIPELINE_BUILD_JOB_NUMBER: '93'
      PIPELINE_BUILD_JOB_NAME: chef-server-12-build
      PIPELINE_RUN_FINGERPRINT: jenkins-chef-server-12-trigger-git_poll-45/45/2016-02-04_05-00-09
    runs: {}
