---
result: ABORTED
timestamp: '2016-02-03T15:00:19-08:00'
duration: 3506.1420000000003
version: 
git_commit: 299df1447e897e792f9e0eec0d471330cc4530c0
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-02-03T15:00:19-08:00'
    duration: 10.925
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/42/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: ABORTED
    failures:
      aborted: all
    timestamp: '2016-02-03T15:00:36-08:00'
    duration: 3495.217
    url: http://wilson.ci.chef.co/job/chef-server-12-build/89/
    causes:
    - shortDescription: Aborted by sdelano
    parameters:
      GIT_REF: origin/master
      DELIVERY_CHANGE: ''
      DELIVERY_SHA: ''
      EXPIRE_CACHE: 'false'
      RELEASE_BUILD: 'false'
      PIPELINE_NAME: chef-server-12
      GIT_COMMIT: 299df1447e897e792f9e0eec0d471330cc4530c0
      PROJECT: chef-server
      PROMOTE: 'true'
      PIPELINE_TRIGGER_BUILD_NUMBER: '42'
      GIT_BRANCH: origin/master
      PIPELINE_TRIGGER_JOB_NAME: chef-server-12-trigger-git_poll
      BUILD_USER: SCMTrigger
    runs:
      el-5:
        result: ABORTED
        timestamp: '2016-02-03T15:00:36-08:00'
        duration: 3485.877
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/89/
        failureCause:
          cause: aborted
          detailedCause: aborted
          lastOmnibusLine: "[Builder: opscode-chef-mover] I | $ gmake omnibus"
          lastOmnibusStep: 'Builder: opscode-chef-mover'
          suspiciousLines:
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
        failureReason: {}
        omnibusTiming: {}
      el-6:
        result: ABORTED
        timestamp: '2016-02-03T15:00:36-08:00'
        duration: 3485.96
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/89/
        failureCause:
          cause: aborted
          detailedCause: aborted
          lastOmnibusLine: "[Builder: gecode] I | $ gmake -j 3"
          lastOmnibusStep: 'Builder: gecode'
          suspiciousLines:
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
        failureReason: {}
        omnibusTiming: {}
      el-7:
        result: ABORTED
        timestamp: '2016-02-03T15:00:36-08:00'
        duration: 3485.863
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/89/
        failureCause:
          cause: aborted
          detailedCause: aborted
          lastOmnibusLine: "[Builder: opscode-chef-mover] I | $ gmake omnibus"
          lastOmnibusStep: 'Builder: opscode-chef-mover'
          suspiciousLines:
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /usr/sbin/ldconfig: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
        failureReason: {}
        omnibusTiming: {}
      ubuntu-10.04:
        result: ABORTED
        timestamp: '2016-02-03T15:00:36-08:00'
        duration: 3485.977
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/89/
        failureCause:
          cause: aborted
          detailedCause: aborted
          lastOmnibusLine: "[Packager::DEB] D | Remove directory `/tmp/chef-server-core20160203-16289-1md6i9d'"
          lastOmnibusStep: Packager::DEB
          suspiciousLines:
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
          - 'D | /sbin/ldconfig.real: Can''t create temporary cache file /etc/ld.so.cache~:
            Permission denied'
        failureReason: {}
        omnibusTiming: {}
