---
version: 
result: ABORTED
timestamp: '2016-01-27T10:50:07-08:00'
duration: 649.006
git_commit: 0bba9c78bf6615fe6cc5636d08026b13bd6bbd59
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-01-27T10:50:07-08:00'
    duration: 8.371
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/32/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: ABORTED
    timestamp: '2016-01-27T10:50:22-08:00'
    duration: 640.635
    url: http://wilson.ci.chef.co/job/chef-server-12-build/70/
    causes:
    - shortDescription: Aborted by sdelano
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-27T10:49:12-08:00'
        duration: 4683.134
        delay: -70.0
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/69/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-27T10:49:12-08:00'
        duration: 5027.864
        delay: -70.0
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/69/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-27T10:49:12-08:00'
        duration: 4602.455
        delay: -70.0
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/69/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-27T10:49:12-08:00'
        duration: 3077.115
        delay: -70.0
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/69/
        omnibus_builders: {}
