---
version: 12.4.0+20160127214032
result: SUCCESS
timestamp: '2016-01-27T13:40:12-08:00'
duration: 4911.324
git_commit: 4eac9bb9aa83aa778403b7d781f992efaafaec47
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-01-27T13:40:12-08:00'
    duration: 12.164
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/34/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-01-27T13:40:32-08:00'
    duration: 2005.104
    url: http://wilson.ci.chef.co/job/chef-server-12-build/72/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-27T13:40:32-08:00'
        duration: 1997.306
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/72/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-27T13:40:32-08:00'
        duration: 1639.213
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/72/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-27T13:40:32-08:00'
        duration: 1646.413
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/72/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-27T13:40:32-08:00'
        duration: 1165.233
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/72/
        omnibus_builders: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-01-27T14:14:03-08:00'
    duration: 2893.176
    url: http://wilson.ci.chef.co/job/chef-server-12-test/68/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-27T14:14:03-08:00'
        duration: 2783.312
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/68/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-27T14:14:03-08:00'
        duration: 2892.934
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/68/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-27T14:14:03-08:00'
        duration: 2303.973
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/68/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-27T14:14:03-08:00'
        duration: 2735.02
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/68/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-01-27T14:14:03-08:00'
        duration: 2614.337
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/68/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-01-27T14:14:03-08:00'
        duration: 2524.035
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/68/
        omnibus_builders: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-01-27T15:02:25-08:00'
    duration: 0.88
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/32/
    runs: {}
