---
version: 12.4.0+20160129130025
result: FAILURE
timestamp: '2016-01-29T05:00:10-08:00'
duration: 4914.159
git_commit: 57c8313fcade7777346e43762dc3218aa5e6ead1
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-01-29T05:00:10-08:00'
    duration: 8.923
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/38/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-01-29T05:00:25-08:00'
    duration: 1877.003
    url: http://wilson.ci.chef.co/job/chef-server-12-build/76/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-29T05:00:25-08:00'
        duration: 1859.866
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/76/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-29T05:00:25-08:00'
        duration: 1316.899
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/76/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-29T05:00:25-08:00'
        duration: 1247.307
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/76/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-29T05:00:25-08:00'
        duration: 909.266
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/76/
        omnibus_timing: {}
  chef-server-12-test:
    result: FAILURE
    timestamp: '2016-01-29T05:31:50-08:00'
    duration: 3028.233
    url: http://wilson.ci.chef.co/job/chef-server-12-test/72/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-01-29T05:31:50-08:00'
        duration: 2927.246
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/72/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-01-29T05:31:50-08:00'
        duration: 3026.065
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/72/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-01-29T05:31:50-08:00'
        duration: 2325.382
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/72/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-01-29T05:31:50-08:00'
        duration: 2684.537
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/72/
        omnibus_timing: {}
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-01-29T05:31:50-08:00'
        duration: 2704.358
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/72/
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-01-29T05:31:50-08:00'
        duration: 2551.713
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/72/
        omnibus_timing: {}
