---
version: 
result: ABORTED
timestamp: '2016-02-03T15:50:09-08:00'
duration: 534.48
git_commit: 7de37c0a067971ee13e9cdb3570532a28430113e
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-02-03T15:50:09-08:00'
    duration: 9.753
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/44/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: ABORTED
    timestamp: '2016-02-03T15:50:29-08:00'
    duration: 524.727
    url: http://wilson.ci.chef.co/job/chef-server-12-build/92/
    causes:
    - shortDescription: Aborted by sdelano
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 2208.93
        delay: -2548.0
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/90/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 3013.264
        delay: -2548.0
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/90/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 1807.143
        delay: -2548.0
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/90/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 1094.54
        delay: -2548.0
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/90/
        omnibus_builders: {}
