---
version: 12.4.2+20160225171028
result: SUCCESS
timestamp: '2016-02-25T09:10:08-08:00'
duration: 5128.35
git_commit: 218579549024b26b3b97c9958503ff3651e3fb16
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-02-25T09:10:08-08:00'
    duration: 11.51
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/55/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-02-25T09:10:28-08:00'
    duration: 2111.087
    url: http://wilson.ci.chef.co/job/chef-server-12-build/110/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-02-25T09:10:28-08:00'
        duration: 2101.134
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/110/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-02-25T09:10:28-08:00'
        duration: 1519.982
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/110/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-02-25T09:10:28-08:00'
        duration: 1432.328
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/110/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-02-25T09:10:28-08:00'
        duration: 1059.182
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/110/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-02-25T09:45:49-08:00'
    duration: 2997.606
    url: http://wilson.ci.chef.co/job/chef-server-12-test/102/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-02-25T09:45:49-08:00'
        duration: 2997.514
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/102/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-02-25T09:45:49-08:00'
        duration: 2829.713
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/102/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-02-25T09:45:49-08:00'
        duration: 2420.196
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/102/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-02-25T09:45:49-08:00'
        duration: 2701.227
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/102/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-02-25T09:45:49-08:00'
        duration: 2602.648
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/102/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-02-25T09:45:49-08:00'
        duration: 2563.585
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/102/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-02-25T10:35:54-08:00'
    duration: 8.147
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/62/
    runs: {}
