---
version: 12.4.2+20160303184035
result: FAILURE
timestamp: '2016-03-03T10:40:10-08:00'
duration: 3032.6189999999997
git_commit: 83ba83552a34d41f55f40f56c5b969174c3fdd8c
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-03T10:40:10-08:00'
    duration: 14.823
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/65/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-03-03T10:40:35-08:00'
    duration: 2586.798
    url: http://wilson.ci.chef.co/job/chef-server-12-build/148/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-03T10:40:35-08:00'
        duration: 1241.098
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/148/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-03T10:40:35-08:00'
        duration: 1043.432
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/148/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-03T10:40:35-08:00'
        duration: 1148.878
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/148/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-03T10:40:35-08:00'
        duration: 964.376
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/148/
        omnibus_timing: {}
  chef-server-12-test:
    result: FAILURE
    timestamp: '2016-03-03T11:23:51-08:00'
    duration: 430.998
    url: http://wilson.ci.chef.co/job/chef-server-12-test/120/
    runs:
      el-5:
        result: FAILURE
        timestamp: '2016-03-03T11:23:51-08:00'
        duration: 429.692
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/120/
      el-6:
        result: FAILURE
        timestamp: '2016-03-03T11:23:51-08:00'
        duration: 261.485
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/120/
      el-7:
        result: FAILURE
        timestamp: '2016-03-03T11:23:51-08:00'
        duration: 299.91
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/120/
      ubuntu-10.04:
        result: FAILURE
        timestamp: '2016-03-03T11:23:51-08:00'
        duration: 271.959
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/120/
      ubuntu-12.04:
        result: FAILURE
        timestamp: '2016-03-03T11:23:51-08:00'
        duration: 281.616
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/120/
      ubuntu-14.04:
        result: FAILURE
        timestamp: '2016-03-03T11:23:51-08:00'
        duration: 258.467
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/120/
