---
version: 12.4.2+20160309002026
result: SUCCESS
timestamp: '2016-03-08T16:20:06-08:00'
duration: 6497.919
git_commit: 792fbb1d7a48d5392c68b862132b86db4a1d9f9e
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-08T16:20:06-08:00'
    duration: 10.88
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/68/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-03-08T16:20:26-08:00'
    duration: 3794.889
    url: http://wilson.ci.chef.co/job/chef-server-12-build/156/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-08T16:20:26-08:00'
        duration: 3784.54
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/156/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-08T16:20:26-08:00'
        duration: 3510.462
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/156/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-08T16:20:26-08:00'
        duration: 2735.504
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/156/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-08T16:20:26-08:00'
        duration: 2739.4
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/156/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-03-08T17:23:48-08:00'
    duration: 2682.513
    url: http://wilson.ci.chef.co/job/chef-server-12-test/127/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-08T17:23:48-08:00'
        duration: 2681.654
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/127/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-08T17:23:48-08:00'
        duration: 2678.436
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/127/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-08T17:23:48-08:00'
        duration: 2146.26
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/127/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-08T17:23:48-08:00'
        duration: 2440.433
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/127/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-08T17:23:48-08:00'
        duration: 2358.067
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/127/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-08T17:23:48-08:00'
        duration: 2671.188
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/127/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-03-08T18:08:39-08:00'
    duration: 9.637
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/82/
    runs: {}
