---
version: 12.4.2+20160310224028
result: SUCCESS
timestamp: '2016-03-10T14:40:08-08:00'
duration: 4524.254
git_commit: f8c46ac047439e0aa141d82a0c7f309a7bc638b4
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-10T14:40:08-08:00'
    duration: 10.335
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/69/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-03-10T14:40:28-08:00'
    duration: 1666.255
    url: http://wilson.ci.chef.co/job/chef-server-12-build/165/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-10T14:40:28-08:00'
        duration: 1654.555
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/165/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-10T14:40:28-08:00'
        duration: 1435.322
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/165/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-10T14:40:28-08:00'
        duration: 1489.219
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/165/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-10T14:40:28-08:00'
        duration: 1298.581
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/165/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-03-10T15:08:24-08:00'
    duration: 2840.017
    url: http://wilson.ci.chef.co/job/chef-server-12-test/134/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-10T15:08:24-08:00'
        duration: 2839.579
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/134/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-10T15:08:24-08:00'
        duration: 2809.014
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/134/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-10T15:08:24-08:00'
        duration: 2595.264
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/134/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-10T15:08:24-08:00'
        duration: 2726.798
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/134/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-10T15:08:24-08:00'
        duration: 2558.896
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/134/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-10T15:08:24-08:00'
        duration: 2451.986
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/134/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-03-10T15:55:50-08:00'
    duration: 7.647
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/85/
    runs: {}
