---
version: 12.4.2+20160316152028
result: SUCCESS
timestamp: '2016-03-16T08:20:08-07:00'
duration: 4191.768999999999
git_commit: 32be69a5e45d00d0a1eb6430bd0a6782e21213e8
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-16T08:20:08-07:00'
    duration: 9.461
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/72/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-03-16T08:20:28-07:00'
    duration: 1437.357
    url: http://wilson.ci.chef.co/job/chef-server-12-build/176/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-16T08:20:28-07:00'
        duration: 1425.05
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/176/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-16T08:20:28-07:00'
        duration: 1130.465
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/176/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-16T08:20:28-07:00'
        duration: 1265.249
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/176/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-16T08:20:28-07:00'
        duration: 1030.33
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/176/
        omnibus_builders: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-03-16T08:44:34-07:00'
    duration: 2737.39
    url: http://wilson.ci.chef.co/job/chef-server-12-test/143/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-16T08:44:34-07:00'
        duration: 2736.402
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/143/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-16T08:44:34-07:00'
        duration: 2704.271
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/143/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-16T08:44:34-07:00'
        duration: 2255.21
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/143/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-16T08:44:34-07:00'
        duration: 2400.097
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/143/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-16T08:44:34-07:00'
        duration: 2519.0
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/143/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-16T08:44:34-07:00'
        duration: 2428.31
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/143/
        omnibus_builders: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-03-16T09:30:21-07:00'
    duration: 7.561
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/93/
    runs: {}
