---
version: 12.4.2+20160322002027
result: SUCCESS
timestamp: '2016-03-21T17:20:07-07:00'
duration: 4780.515
git_commit: ed05d000c34232cbaf6e50e254002b6292962949
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-21T17:20:07-07:00'
    duration: 9.655
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/78/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-03-21T17:20:27-07:00'
    duration: 2029.111
    url: http://wilson.ci.chef.co/job/chef-server-12-build/194/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-21T17:20:27-07:00'
        duration: 2018.354
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/194/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-21T17:20:27-07:00'
        duration: 1876.738
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/194/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-21T17:20:27-07:00'
        duration: 1908.781
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/194/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-21T17:20:27-07:00'
        duration: 1680.516
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/194/
        omnibus_builders: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-03-21T17:54:23-07:00'
    duration: 2734.271
    url: http://wilson.ci.chef.co/job/chef-server-12-test/159/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-21T17:54:23-07:00'
        duration: 2733.296
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/159/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-21T17:54:23-07:00'
        duration: 2721.827
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/159/
        omnibus_builders: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-21T17:54:23-07:00'
        duration: 2415.93
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/159/
        omnibus_builders: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-21T17:54:23-07:00'
        duration: 2432.491
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/159/
        omnibus_builders: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-21T17:54:23-07:00'
        duration: 2409.12
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/159/
        omnibus_builders: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-21T17:54:23-07:00'
        duration: 2419.355
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/159/
        omnibus_builders: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-03-21T18:40:04-07:00'
    duration: 7.478
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/105/
    runs: {}
