---
version: 
result: FAILURE
timestamp: '2016-03-21T22:10:11-07:00'
duration: 1381.74
git_commit: c495febbbf04fca9b2c4115dfeb793ea0a317d8a
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-21T22:10:11-07:00'
    duration: 9.538
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/79/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: FAILURE
    timestamp: '2016-03-21T22:10:31-07:00'
    duration: 1372.202
    url: http://wilson.ci.chef.co/job/chef-server-12-build/195/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-21T22:10:31-07:00'
        duration: 1358.546
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/195/
        omnibus_builders: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-21T22:10:31-07:00'
        duration: 1154.496
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/195/
        omnibus_builders: {}
      el-7:
        result: FAILURE
        timestamp: '2016-03-21T22:10:31-07:00'
        duration: 77.213
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/195/
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-21T22:10:31-07:00'
        duration: 1003.439
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/195/
        omnibus_builders: {}
