---
version: 12.5.0+20160331192116
result: SUCCESS
timestamp: '2016-03-31T12:20:11-07:00'
duration: 4438.629
git_commit: 4f0dbaa72fc1d68a2c9ba207ded220eb0ec4217c
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-03-31T12:20:11-07:00'
    duration: 57.364
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/82/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-03-31T12:21:16-07:00'
    duration: 1572.623
    url: http://wilson.ci.chef.co/job/chef-server-12-build/201/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-31T12:21:16-07:00'
        duration: 1459.394
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/201/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-31T12:21:16-07:00'
        duration: 1359.686
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/201/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-31T12:21:16-07:00'
        duration: 1551.29
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/201/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-31T12:21:16-07:00'
        duration: 1151.595
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/201/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-03-31T12:47:36-07:00'
    duration: 2801.089
    url: http://wilson.ci.chef.co/job/chef-server-12-test/165/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-31T12:47:36-07:00'
        duration: 2734.344
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/165/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-31T12:47:36-07:00'
        duration: 2800.956
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/165/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-31T12:47:36-07:00'
        duration: 2180.13
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/165/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-31T12:47:36-07:00'
        duration: 2476.54
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/165/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-31T12:47:36-07:00'
        duration: 2444.19
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/165/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-31T12:47:36-07:00'
        duration: 2407.07
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/165/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-03-31T13:34:27-07:00'
    duration: 7.553
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/111/
    runs: {}
