---
version: 12.5.0+20160420233034
result: SUCCESS
timestamp: '2016-04-20T16:30:09-07:00'
duration: 4405.615
git_commit: b648ed7467f4194daa08c6d7cf4ad837b2875228
stages:
  chef-server-12-trigger-git_poll:
    result: SUCCESS
    timestamp: '2016-04-20T16:30:09-07:00'
    duration: 15.999
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-git_poll/90/
    causes:
    - shortDescription: Started by an SCM change
    parameters: {}
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-04-20T16:30:34-07:00'
    duration: 1258.854
    url: http://wilson.ci.chef.co/job/chef-server-12-build/228/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-04-20T16:30:34-07:00'
        duration: 1246.932
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/228/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-20T16:30:34-07:00'
        duration: 1225.626
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/228/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-20T16:30:34-07:00'
        duration: 1202.906
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/228/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-20T16:30:34-07:00'
        duration: 1046.403
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/228/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-04-20T16:51:40-07:00'
    duration: 3122.913
    url: http://wilson.ci.chef.co/job/chef-server-12-test/191/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-04-20T16:51:40-07:00'
        duration: 2947.514
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/191/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-04-20T16:51:40-07:00'
        duration: 3122.158
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/191/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-04-20T16:51:40-07:00'
        duration: 2298.601
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/191/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-04-20T16:51:40-07:00'
        duration: 2656.378
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/191/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-04-20T16:51:40-07:00'
        duration: 2688.786
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/191/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-04-20T16:51:40-07:00'
        duration: 2820.743
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/191/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-04-20T17:43:53-07:00'
    duration: 7.849
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/129/
    runs: {}
