---
version: 12.4.1
result: SUCCESS
timestamp: '2016-02-03T15:07:43-08:00'
duration: 8995.961
git_commit: 299df1447e897e792f9e0eec0d471330cc4530c0
stages:
  chef-server-12-trigger-release:
    result: SUCCESS
    timestamp: '2016-02-03T15:07:43-08:00'
    duration: 8.591
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-release/2/
    parameters:
      GIT_REF: 12.4.1
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user David McCown
      userId: dmccown
      userName: David McCown
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-02-03T15:08:01-08:00'
    duration: 6074.231
    url: http://wilson.ci.chef.co/job/chef-server-12-build/90/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 2208.93
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/90/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 3013.264
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/90/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 1807.143
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/90/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-02-03T15:08:01-08:00'
        duration: 1094.54
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/90/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-02-03T16:49:26-08:00'
    duration: 2904.102
    url: http://wilson.ci.chef.co/job/chef-server-12-test/84/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-02-03T16:49:26-08:00'
        duration: 2903.698
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/84/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-02-03T16:49:26-08:00'
        duration: 2809.747
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/84/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-02-03T16:49:26-08:00'
        duration: 2292.348
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/84/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-02-03T16:49:26-08:00'
        duration: 2625.879
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/84/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-02-03T16:49:26-08:00'
        duration: 2603.641
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/84/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-02-03T16:49:26-08:00'
        duration: 2511.642
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/84/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-02-03T17:37:57-08:00'
    duration: 9.037
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/47/
    runs: {}
