---
version: 12.5.0
result: SUCCESS
timestamp: '2016-03-22T16:26:56-07:00'
duration: 6831.465999999999
git_commit: bb28b489960c8fae6ac061bf2dab5800142b22a3
stages:
  chef-server-12-trigger-release:
    result: SUCCESS
    timestamp: '2016-03-22T16:26:56-07:00'
    duration: 9.826
    url: http://wilson.ci.chef.co/job/chef-server-12-trigger-release/3/
    parameters:
      GIT_REF: 12.5.0
      EXPIRE_CACHE: false
    causes:
    - shortDescription: Started by user Kartik Null Cating-Subramanian
      userId: ksubrama
      userName: Kartik Null Cating-Subramanian
    runs: {}
  chef-server-12-build:
    result: SUCCESS
    timestamp: '2016-03-22T16:27:15-07:00'
    duration: 4087.186
    url: http://wilson.ci.chef.co/job/chef-server-12-build/197/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-22T16:27:15-07:00'
        duration: 3992.379
        builtOn: chef-server-rhel-5-builder-dd11b6
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-5,project=chef-server,role=builder/197/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-22T16:27:15-07:00'
        duration: 4075.229
        builtOn: chef-server-rhel-6-builder-f4b641
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-6,project=chef-server,role=builder/197/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-22T16:27:15-07:00'
        duration: 3277.792
        builtOn: chef-server-rhel-7-builder-1d11c3
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=el-7,project=chef-server,role=builder/197/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-22T16:27:15-07:00'
        duration: 2971.699
        builtOn: chef-server-ubuntu-10.04-builder-6f743f
        url: http://wilson.ci.chef.co/job/chef-server-12-build/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=builder/197/
        omnibus_timing: {}
  chef-server-12-test:
    result: SUCCESS
    timestamp: '2016-03-22T17:35:29-07:00'
    duration: 2726.823
    url: http://wilson.ci.chef.co/job/chef-server-12-test/161/
    runs:
      el-5:
        result: SUCCESS
        timestamp: '2016-03-22T17:35:29-07:00'
        duration: 2726.683
        builtOn: chef-server-rhel-5-tester-4e6602
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-5,project=chef-server,role=tester/161/
        omnibus_timing: {}
      el-6:
        result: SUCCESS
        timestamp: '2016-03-22T17:35:29-07:00'
        duration: 2699.824
        builtOn: chef-server-rhel-6-tester-8151c8
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-6,project=chef-server,role=tester/161/
        omnibus_timing: {}
      el-7:
        result: SUCCESS
        timestamp: '2016-03-22T17:35:29-07:00'
        duration: 2233.085
        builtOn: chef-server-rhel-7-tester-d586ce
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=el-7,project=chef-server,role=tester/161/
        omnibus_timing: {}
      ubuntu-10.04:
        result: SUCCESS
        timestamp: '2016-03-22T17:35:29-07:00'
        duration: 2434.336
        builtOn: chef-server-ubuntu-10.04-tester-f80d1f
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-10.04,project=chef-server,role=tester/161/
        omnibus_timing: {}
      ubuntu-12.04:
        result: SUCCESS
        timestamp: '2016-03-22T17:35:29-07:00'
        duration: 2398.366
        builtOn: chef-server-ubuntu-12.04-tester-28c735
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-12.04,project=chef-server,role=tester/161/
        omnibus_timing: {}
      ubuntu-14.04:
        result: SUCCESS
        timestamp: '2016-03-22T17:35:29-07:00'
        duration: 2391.233
        builtOn: chef-server-ubuntu-14.04-tester-69fc04
        url: http://wilson.ci.chef.co/job/chef-server-12-test/architecture=x86_64,platform=ubuntu-14.04,project=chef-server,role=tester/161/
        omnibus_timing: {}
  chef-server-12-promote:
    result: SUCCESS
    timestamp: '2016-03-22T18:21:02-07:00'
    duration: 7.631
    url: http://wilson.ci.chef.co/job/chef-server-12-promote/107/
    runs: {}
